phrasesList={
"arab":'Standard Arabic, Hausa, Kashmiri, Persian, Urdu',
"armn":'Armenian',
"bali":'Balinese',
"cans":'Inuktitut',
"cher":'Cherokee',
"cyrl":'Kazakh, Kyrghyz, Russian',
"deva":'Hindi, Kashmiri, Nepali',
"egyp":'Ancient Egyptian',
"ethi":'Amharic',
"grek":'Modern Greek',
"guru":'Punjabi',
"hani":'SC Mandarin, TC Mandarin',
"hebr":'Hebrew',
"jpan":'Japanese',
"knda":'Kannada',
"khmr":'Khmer',
"kore":'Korean',
"latn":'IPA (en-GB), Akan, Hungarian, Hausa, Venda, Welsh',
"mong":'Mongolian',
"mymr":'Burmese',
"syrc":'Assyrian Neo-Aramaic',
"telu":'Telugu',
"tfng":'Standard Moroccan Tamazight',
"thai":'Thai',
"tibt":'Dzongka',
}