langTag = 'syl'
window.version = 'v29'
window.scriptName = 'Syloti Nagri'
window.ghDirectory = 'sylo'
window.blockDirectory = 'sylo'
window.languageList = ['syl'] // lang tags for each orthography handled
window.detailsfileList = ['syl'] // first part of xx-details for each orthography
window.scriptISO = 'sylo'
window.webfonts = ["Surma WF"]
window.defaultSize = '24px'
hideBlockName = "SYLOTI NAGRI"
