window.version = 'v29'
window.scriptName = 'Tai Tham'
window.ghDirectory = 'lana'
window.blockDirectory = 'lana'
window.languageList = ['kkh','nod'] // lang tags for each orthography handled
window.detailsfileList = ['kkh','nod'] // first part of xx-details for each orthography
window.scriptISO = 'lana'
window.webfonts = ["Hariphunchai WF", "Lamphun WF", "Noto Serif Tai Tham WF", "Lanna Alif WF", "A Tai Tham KH New WF"]
hideBlockName = "TAI THAM"
