langTag = 'en'
window.version = 'v29'
window.scriptName = ''
window.ghDirectory = 'currencysymbols'
window.blockDirectory = 'currencysymbols'
window.languageList = ['en'] // lang tags for each orthography handled
window.detailsfileList = ['en'] // first part of xx-details for each orthography
window.scriptISO = 'latn'
window.webfonts = ["Noto Sans WF"]
window.defaultSize = '24px'
hideBlockName = ""
