// if there is a * after a transcription it has been autogenerated and needs checking

autoExpandExamples.ar = `
آب|August|ʔaːb
آب|water|āb
آثار|effects|ʔaːθaːr
أجور|wages|ʔud͡ʒuːr
أفعًى|snake|afʕan
أنا|I|ˈʔana
أنكر|denial|ʔɪnkar
أوتوبيس|bus|otobiːs
أوتيل|hotel|oːteːl
أوّل|first|ʔawːal
أُذُن|ear|ʔʊðʊn
أُكتُوبِر|October|oktoːbɪr
أُوتِيل|hotel|oːteːl
إدارة|administration|ʔɪdaːraʰ
إنتاج|caution|intaːj
إيقاف|parking|iːqaːf
الآن|now|alʔaːn
العَرَبِيَّة|Arabic ((al-ʻarabīyah))
اللّٰه|Allah
انتباه|caution|intibah
اَلآن|now|alʔaːn
اِسْم|name|ɪsm
باريس|Paris|paːriːs
باكستان|Pakistan|pakistaːn
بناء|builder|bannaːʔ
بناء|building|binaːʔ
بنطلون|trousers|bant̴aloːn
بيت|house|bajt
تاجر، تجّار|trader, traders|tad͡ʒir, tud͡ʒd͡ʒaːr
تاريخ|history|tɑːriːx
تلك|that|tɪlka
تنبّؤ|forecast|tanabbuʔ
ثلاثة|three|θalaːθaʰ
جبل|mountain|d͡ʒabal
جزء|portion|d͡ʒuzʔ
جنيف|Geneva|d͡ʒɪneːv
حتّى|until|ħatːaː
خلال|through|xɪlaːla
دينار|dinar|diːnaːr
ديوان|poetry.|diːwaːn
دُودَة|worm|duːda
ذهب|gold|ðahab
ذَاتِيَّة|identity|ðaːtiːja
ذٰلِكَ|that
رؤوس|heads|rʊʔuːs
رئيس|President|raʔiːs
رسميًا|officially|rasmiːjan
رَمَى|to throw|ramaː
رِيح|wind|riːħ
زائر|visitor|zaːʔɪr
زيارة|visit|zɪjaːra
سأل|to question|saʔala
سؤال|question|suʔaːl
سكرتير|secretary |sɪkrɪteːr
سنة|year|sanaʰ
سيارة|car|sajaːra
سَاق|leg|saːq
شمس|sun|ʃams
شيء|thing|ʃajʔ
صحيفة|newspaper|sˤaħiːfaʰ
ضمان|guarantee|dˤamaːn
طريق|road|tˤariːq
ظلام|darkness|ðˤalaːm
ظلمة|darkness|ðˤʊlmaʰ
عادةً|usually|ʕaːdatan
على|over|ʕalaː
عمر|Omar|ʕʊmar
عمرو|Amr|ʕamr
عَوْد|return|ʕawd
عَيْن|eye|ʕajn
غابة|forest|ɣaːba
فقيد|lost|faqiːd
فندق|hotel|ˈfʊndʊq
فورًا|immediately|fuːran
في|in|fiː
فيروس|virus|virus
قدم|foot|qadam
قرأ|to read|qaraʔ
قراءة|reading|qiraːʔa
قلوب|hearts|quluːb
قليلاً|a little|qaliːlan
قَدَم|foot|qadam
كيف|how|kajfa
لَحم|meat|laħm
لَيْلَة|night|lajla
مأمور|public official|maʔmuːr
مؤمن|believer|muʔmin
مدرسة|school|madrasa
مدرستنا|our school|madrasat-naː
مستشفى|hospital|mʊstaʃfaː
مليء|full|maliːʔ
منذ|since|mʊnðʊ
مَا ٱسْمُكَ|What's your name? (mā smuka)
مَدرَسَة|school|madrasa
مَدرَسَتنَا|our school|madrasat-naː
مَكْتَب|desk|maktab
مَكْتَب|office|maktab
مُمَثِّلْ|representative|mumaθθil
نائم|asleep|naːʔɪm
نائم|sleeping|nɑːʔim
نحو|toward|naħwa
نقود|money|nʊquːd
نهائي|final|nihaːʔiː
هناك|there|hʊnaːka
هَٰذَا|this
وفى أوفياء|complete (sing+pl)|wafiː awfɪjaːʔ
ولد، أولاد|boy|walad, ʔawlaːd
يؤثر|prefer|juʔaθːir
يَابَانِية|Japanese|jaːbaːniːja
يَوْم|day|yawm
پاريس|Paris|paːriːs
چاكارتا|Jakarta|jaːkaːrta
ڤيينا|Vienna|vijeːna

`

