var desc = []   // unicode v11

desc[2946]="• not used in Tamil"
desc[2947]="= aytham¶• just as for the Tamil pulli, the glyph for aytham may use either dots or rings"
desc[2964]="≡ 0B92 0BD7"
desc[2969]="• also denotes the measure kuruni/marakkaal"
desc[2980]="• also denotes the measure tuuni"
desc[2986]="= maa¶• also denotes the fraction one twentieth"
desc[2995]="• also denotes the measure kalam"
desc[2997]="= kaal¶• also denotes the fraction one quarter"
desc[3014]="• stands to the left of the consonant"
desc[3015]="• stands to the left of the consonant"
desc[3016]="• stands to the left of the consonant"
desc[3018]="≡ 0BC6 0BBE"
desc[3019]="≡ 0BC7 0BBE"
desc[3020]="≡ 0BC6 0BD7"
desc[3021]="= pulli"
desc[3044]="→ (devanagari danda - 0964)"
desc[3045]="→ (devanagari double danda - 0965)"
desc[3059]="= naal, naali/padi¶• denotes a measure of grain that equals 2 uri or 4 ulakku¶= pillaiyaar suli¶• denotes auspiciousness"
desc[3060]="= maatham"
desc[3061]="= varudam"
desc[3062]="= patru"
desc[3063]="= eduppu¶• denotes incoming cash which is set aside for unknown expenses¶• sometimes used as the credit sign; the traditional credit sign is distinct"
desc[3064]="= merpadi"
desc[3065]="= rupai"
desc[3066]="= enn, niluvai¶• denotes balance¶• sometimes used as the number sign; the traditional number sign is distinct"
