
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"4",
  
  "macros":[{
      "function":"__e"
    },{
      "function":"__v",
      "vtp_name":"gtm.elementId",
      "vtp_dataLayerVersion":1
    },{
      "function":"__gas",
      "vtp_cookieDomain":["template","auto",["macro",1]],
      "vtp_doubleClick":false,
      "vtp_setTrackerName":false,
      "vtp_useDebugVersion":false,
      "vtp_useHashAutoLink":false,
      "vtp_decorateFormsAutoLink":false,
      "vtp_enableLinkId":false,
      "vtp_enableEcommerce":false,
      "vtp_trackingId":"UA-53866465-1",
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableGA4Schema":false
    },{
      "function":"__e"
    },{
      "function":"__v",
      "vtp_name":"gtm.element",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.elementClasses",
      "vtp_dataLayerVersion":1
    },{
      "function":"__dbg"
    }],
  "tags":[{
      "function":"__gaawc",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_sendPageView":true,
      "vtp_measurementId":"G-D5QZB7YF55",
      "vtp_enableUserProperties":true,
      "tag_id":16
    }],
  "predicates":[{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.js"
    }],
  "rules":[
    [["if",0],["add",0]]]
},
"runtime":[]




};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var g,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ca=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ea="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ia;a:{var ja={a:!0},ka={};try{ka.__proto__=ja;ia=ka.a;break a}catch(a){}ia=!1}fa=ia?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var la=fa,na=function(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(la)la(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ri=b.prototype},oa=this||self,pa=function(a){return a};var qa={},ra=function(a,b){qa[a]=qa[a]||[];qa[a][b]=!0},sa=function(a){for(var b=[],c=qa[a]||[],d=0;d<c.length;d++)c[d]&&(b[Math.floor(d/6)]^=1<<d%6);for(var e=0;e<b.length;e++)b[e]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(b[e]||0);return b.join("")};var ta=function(){},ua=function(a){return"function"==typeof a},m=function(a){return"string"==typeof a},va=function(a){return"number"==typeof a&&!isNaN(a)},wa=function(a){var b="[object Array]"==Object.prototype.toString.call(Object(a));Array.isArray?Array.isArray(a)!==b&&ra("TAGGING",4):ra("TAGGING",5);return b},Ba=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},Da=function(a,b){if(a&&wa(a))for(var c=
0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},Ea=function(a,b){if(!va(a)||!va(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Ha=function(a,b){for(var c=new Ga,d=0;d<a.length;d++)c.set(a[d],!0);for(var e=0;e<b.length;e++)if(c.get(b[e]))return!0;return!1},Ia=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])},Ka=function(a){return!!a&&("[object Arguments]"==Object.prototype.toString.call(a)||Object.prototype.hasOwnProperty.call(a,"callee"))},La=
function(a){return Math.round(Number(a))||0},Ma=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Na=function(a){var b=[];if(wa(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Oa=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},Qa=function(){return(new Date).getTime()},Ga=function(){this.prefix="gtm.";this.values={}};Ga.prototype.set=function(a,b){this.values[this.prefix+a]=b};Ga.prototype.get=function(a){return this.values[this.prefix+a]};
var Ua=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Va=function(a){var b=a;return function(){if(b){var c=b;b=void 0;try{c()}catch(d){}}}},Xa=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Za=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1},$a=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},ab=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c},bb=/^\w{1,9}$/,
cb=function(a){var b=[];Ia(a,function(c,d){bb.test(c)&&d&&b.push(c)});return b.join(",")};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var db=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,fb=function(a){if(null==a)return String(a);var b=db.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},hb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ib=function(a){if(!a||"object"!=fb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!hb(a,"constructor")&&!hb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||hb(a,b)},B=function(a,b){var c=b||("array"==fb(a)?[]:{}),d;for(d in a)if(hb(a,d)){var e=a[d];"array"==fb(e)?("array"!=fb(c[d])&&(c[d]=[]),c[d]=B(e,c[d])):ib(e)?(ib(c[d])||(c[d]={}),c[d]=B(e,c[d])):c[d]=e}return c};var jb=function(a){if(void 0===a||wa(a)||ib(a))return!0;switch(typeof a){case "boolean":case "number":case "string":case "function":return!0}return!1};var kb=function(){var a=function(b){return{toString:function(){return b}}};return{Sf:a("consent"),Tf:a("consent_always_fire"),de:a("convert_case_to"),ee:a("convert_false_to"),fe:a("convert_null_to"),he:a("convert_true_to"),ie:a("convert_undefined_to"),Zh:a("debug_mode_metadata"),Ta:a("function"),Fg:a("instance_name"),Hg:a("live_only"),Ig:a("malware_disabled"),Jg:a("metadata"),bi:a("original_activity_id"),ci:a("original_vendor_template_id"),Lg:a("once_per_event"),Xe:a("once_per_load"),ei:a("priority_override"),
fi:a("respected_consent_types"),df:a("setup_tags"),ef:a("tag_id"),ff:a("teardown_tags")}}();var Mb;
var Nb=[],Ob=[],Pb=[],Qb=[],Rb=[],Sb={},Tb,Ub,Vb,Wb=function(a,b){var c=a["function"];if(!c)throw Error("Error: No function name given for function call.");var d=Sb[c],e={},f;for(f in a)if(a.hasOwnProperty(f))if(0===f.indexOf("vtp_"))d&&b&&b.nf&&b.nf(a[f]),e[void 0!==d?f:f.substr(4)]=a[f];else if(f===kb.Tf.toString()&&a[f]){}return void 0!==d?d(e):Mb(c,e,b)},Yb=function(a,b,c){c=c||[];var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=Xb(a[e],b,c));return d},Xb=function(a,b,c){if(wa(a)){var d;switch(a[0]){case "function_id":return a[1];case "list":d=[];for(var e=1;e<a.length;e++)d.push(Xb(a[e],b,c));return d;case "macro":var f=a[1];if(c[f])return;var h=Nb[f];if(!h||b.Jd(h))return;c[f]=!0;try{var k=Yb(h,b,c);k.vtp_gtmEventId=b.id;
d=Wb(k,b);Vb&&(d=Vb.Zg(d,k))}catch(z){b.Af&&b.Af(z,Number(f)),d=!1}c[f]=!1;return d;case "map":d={};for(var l=1;l<a.length;l+=2)d[Xb(a[l],b,c)]=Xb(a[l+1],b,c);return d;case "template":d=[];for(var n=!1,p=1;p<a.length;p++){var q=Xb(a[p],b,c);Ub&&(n=n||q===Ub.sc);d.push(q)}return Ub&&n?Ub.bh(d):d.join("");case "escape":d=Xb(a[1],b,c);if(Ub&&wa(a[1])&&"macro"===a[1][0]&&Ub.uh(a))return Ub.Ih(d);d=String(d);for(var r=2;r<a.length;r++)lb[a[r]]&&(d=lb[a[r]](d));return d;case "tag":var t=a[1];if(!Qb[t])throw Error("Unable to resolve tag reference "+
t+".");return d={vf:a[2],index:t};case "zb":var u={arg0:a[2],arg1:a[3],ignore_case:a[5]};u["function"]=a[1];var v=Zb(u,b,c),x=!!a[4];return x||2!==v?x!==(1===v):null;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},Zb=function(a,b,c){try{return Tb(Yb(a,b,c))}catch(d){JSON.stringify(a)}return 2};var bc=function(a){function b(r){for(var t=0;t<r.length;t++)d[r[t]]=!0}for(var c=[],d=[],e=$b(a),f=0;f<Ob.length;f++){var h=Ob[f],k=ac(h,e);if(k){for(var l=h.add||[],n=0;n<l.length;n++)c[l[n]]=!0;b(h.block||[])}else null===k&&b(h.block||[]);}for(var p=[],q=0;q<Qb.length;q++)c[q]&&!d[q]&&(p[q]=!0);return p},ac=function(a,b){for(var c=a["if"]||[],d=0;d<c.length;d++){var e=b(c[d]);if(0===e)return!1;if(2===e)return null}for(var f=
a.unless||[],h=0;h<f.length;h++){var k=b(f[h]);if(2===k)return null;if(1===k)return!1}return!0},$b=function(a){var b=[];return function(c){void 0===b[c]&&(b[c]=Zb(Pb[c],a));return b[c]}};var cc={Zg:function(a,b){b[kb.de]&&"string"===typeof a&&(a=1==b[kb.de]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(kb.fe)&&null===a&&(a=b[kb.fe]);b.hasOwnProperty(kb.ie)&&void 0===a&&(a=b[kb.ie]);b.hasOwnProperty(kb.he)&&!0===a&&(a=b[kb.he]);b.hasOwnProperty(kb.ee)&&!1===a&&(a=b[kb.ee]);return a}};var E={Hb:"_ee",yc:"_syn_or_mod",gi:"_uei",md:"_eu",di:"_pci",$c:"event_callback",ic:"event_timeout",fa:"gtag.config",za:"gtag.get",oa:"purchase",ib:"refund",Oa:"begin_checkout",fb:"add_to_cart",hb:"remove_from_cart",bg:"view_cart",ne:"add_to_wishlist",ya:"view_item",me:"view_promotion",ke:"select_promotion",Vc:"select_item",bc:"view_item_list",je:"add_payment_info",ag:"add_shipping_info",Ka:"value_key",Ja:"value_callback",qa:"allow_ad_personalization_signals",mc:"restricted_data_processing",Ab:"allow_google_signals",
ra:"cookie_expires",Bb:"cookie_update",Fb:"session_duration",nc:"session_engaged_time",Ca:"user_properties",Ba:"transport_url",O:"ads_data_redaction",ld:"user_data",Cb:"first_party_collection",B:"ad_storage",D:"analytics_storage",be:"region",ce:"wait_for_update",Qa:"conversion_linker",Pa:"conversion_cookie_prefix",ja:"value",ba:"currency",Ne:"trip_type",W:"items",He:"passengers"};E.Qe=[E.oa,E.ib,E.Oa,E.fb,E.hb,E.bg,E.ne,E.ya,E.me,E.ke,E.bc,E.Vc,E.je,E.ag];
E.Pe=[E.qa,E.Ab,E.Bb];E.Re=[E.ra,E.ic,E.Fb,E.nc];var Bc=function(a){ra("GTM",a)};var Cc=function(a,b){this.m=a;this.defaultValue=void 0===b?!1:b};var Dc=new Cc(1936,!0),Ec=new Cc(1933);var Fc=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d},Gc=function(a){var b=a;return function(){if(b){var c=b;b=null;c()}}};var Hc,Ic=function(){if(void 0===Hc){var a=null,b=oa.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:pa,createScript:pa,createScriptURL:pa})}catch(c){oa.console&&oa.console.error(c.message)}Hc=a}else Hc=a}return Hc};var Kc=function(a,b){this.m=b===Jc?a:""};Kc.prototype.toString=function(){return this.m+""};var Jc={};var Lc=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var Mc;a:{var Tc=oa.navigator;if(Tc){var Uc=Tc.userAgent;if(Uc){Mc=Uc;break a}}Mc=""}var Vc=function(a){return-1!=Mc.indexOf(a)};var Xc=function(a,b,c){this.m=c===Wc?a:""};Xc.prototype.toString=function(){return this.m.toString()};var Yc=function(a){return a instanceof Xc&&a.constructor===Xc?a.m:"type_error:SafeHtml"},Wc={},Zc=function(a){var b=Ic(),c=b?b.createHTML(a):a;return new Xc(c,null,Wc)},$c=new Xc(oa.trustedTypes&&oa.trustedTypes.emptyHTML||"",0,Wc);var ad=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);var c=a.firstChild.firstChild;a.innerHTML=Yc($c);return!c.parentElement}),bd=function(a,b){if(ad())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=Yc(b)},cd=null,dd=/^[\w+/_-]+[=]{0,2}$/,ed=function(a){if(!a.querySelector)return"";var b=a.querySelector("script[nonce]");if(b){var c=
b.nonce||b.getAttribute("nonce");if(c&&dd.test(c))return c}return""};var G=window,I=document,fd=navigator,gd=I.currentScript&&I.currentScript.src,hd=function(a,b){var c=G[a];G[a]=void 0===c?b:c;return G[a]},id=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},jd=function(a,b,c){var d=I.createElement("script");d.type="text/javascript";d.async=!0;var e,f=Ic(),h=f?f.createScriptURL(a):a;e=new Kc(h,Jc);d.src=e instanceof Kc&&e.constructor===Kc?e.m:"type_error:TrustedResourceUrl";
var k;var l=d.ownerDocument&&d.ownerDocument.defaultView;l&&l!=oa?k=ed(l.document):(null===cd&&(cd=ed(oa.document)),k=cd);var n=k;n&&d.setAttribute("nonce",n);id(d,b);c&&(d.onerror=c);var p=I.getElementsByTagName("script")[0]||I.body||I.head;p.parentNode.insertBefore(d,p);return d},kd=function(){if(gd){var a=gd.toLowerCase();if(0===a.indexOf("https://"))return 2;if(0===a.indexOf("http://"))return 3}return 1},ld=function(a,b){var c=I.createElement("iframe");c.height="0";c.width="0";c.style.display=
"none";c.style.visibility="hidden";var d=I.body&&I.body.lastChild||I.body||I.head;d.parentNode.insertBefore(c,d);id(c,b);void 0!==a&&(c.src=a);return c},md=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a;return d},nd=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},od=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+
b,c)},J=function(a){G.setTimeout(a,0)},sd=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},td=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},ud=function(a){var b=I.createElement("div"),c=Zc("A<div>"+a+"</div>");bd(b,c);b=b.lastChild;for(var d=[];b.firstChild;)d.push(b.removeChild(b.firstChild));return d},vd=function(a,b,c){c=c||100;for(var d={},e=0;e<
b.length;e++)d[b[e]]=!0;for(var f=a,h=0;f&&h<=c;h++){if(d[String(f.tagName).toLowerCase()])return f;f=f.parentElement}return null},wd=function(a){fd.sendBeacon&&fd.sendBeacon(a)||md(a)},xd=function(a,b){var c=a[b];c&&"string"===typeof c.animVal&&(c=c.animVal);return c};var yd=function(){var a={};this.m=function(b,c){return null!=a[b]?a[b]:c};this.o=function(){a[Ec.m]=!0}};yd.m=void 0;yd.o=function(){return yd.m?yd.m:yd.m=new yd};var zd=function(a){return yd.o().m(a.m,a.defaultValue)};var Ad=[];function Bd(){var a=hd("google_tag_data",{});a.ics||(a.ics={entries:{},set:Cd,update:Dd,addListener:Ed,notifyListeners:Fd,active:!1,usedDefault:!1});return a.ics}
function Cd(a,b,c,d,e,f){var h=Bd();h.active=!0;h.usedDefault=!0;if(void 0!=b){var k=h.entries,l=k[a]||{},n=l.region,p=c&&m(c)?c.toUpperCase():void 0;d=d.toUpperCase();e=e.toUpperCase();if(""===d||p===e||(p===d?n!==e:!p&&!n)){var q=!!(f&&0<f&&void 0===l.update),r={region:p,initial:"granted"===b,update:l.update,quiet:q};if(""!==d||!1!==l.initial)k[a]=r;q&&G.setTimeout(function(){k[a]===r&&r.quiet&&(r.quiet=!1,Gd(a),Fd(),ra("TAGGING",2))},f)}}}
function Dd(a,b){var c=Bd();c.active=!0;if(void 0!=b){var d=Hd(a),e=c.entries,f=e[a]=e[a]||{};f.update="granted"===b;var h=Hd(a);f.quiet?(f.quiet=!1,Gd(a)):h!==d&&Gd(a)}}function Ed(a,b){Ad.push({zd:a,kh:b})}function Gd(a){for(var b=0;b<Ad.length;++b){var c=Ad[b];wa(c.zd)&&-1!==c.zd.indexOf(a)&&(c.Df=!0)}}function Fd(a){for(var b=0;b<Ad.length;++b){var c=Ad[b];if(c.Df){c.Df=!1;try{c.kh({pf:a})}catch(d){}}}}
var Hd=function(a){var b=Bd().entries[a]||{};return void 0!==b.update?b.update:void 0!==b.initial?b.initial:void 0},Id=function(a){return(Bd().entries[a]||{}).initial},Jd=function(a){return!(Bd().entries[a]||{}).quiet},Kd=function(){return zd(Ec)?Bd().active:!1},Ld=function(){return Bd().usedDefault},Md=function(a,b){Bd().addListener(a,b)},Nd=function(a,b){function c(){for(var e=0;e<b.length;e++)if(!Jd(b[e]))return!0;return!1}if(c()){var d=!1;Md(b,function(e){d||c()||(d=!0,a(e))})}else a({})},Od=
function(a,b){function c(){for(var f=[],h=0;h<d.length;h++){var k=d[h];!1===Hd(k)||e[k]||(f.push(k),e[k]=!0)}return f}var d=m(b)?[b]:b,e={};c().length!==d.length&&Md(d,function(f){var h=c();0<h.length&&(f.zd=h,a(f))})};function Pd(a){for(var b=[],c=0;c<Qd.length;c++){var d=a(Qd[c]);b[c]=!0===d?"1":!1===d?"0":"-"}return b.join("")}
var Qd=[E.B,E.D],Rd=function(a){var b=a[E.be];b&&Bc(40);var c=a[E.ce];c&&Bc(41);for(var d=wa(b)?b:[b],e=0;e<d.length;++e)for(var f in a)if(a.hasOwnProperty(f)&&f!==E.be&&f!==E.ce)if(-1<Ba(Qd,f)){var h=f,k=a[f],l=d[e];Bd().set(h,k,l,"GB","GB-ENG",c)}else{}},Sd=function(a,
b){for(var c in a)if(a.hasOwnProperty(c))if(-1<Ba(Qd,c)){var d=c,e=a[c];Bd().update(d,e)}else{}Bd().notifyListeners(b)},N=function(a){var b=Hd(a);return void 0!=b?b:!0},Td=function(){return"G1"+Pd(Hd)},Ud=function(a,b){Od(a,b)},Vd=function(a,b){Nd(a,b)};var Xd=function(a){return Wd?I.querySelectorAll(a):null},Yd=function(a,b){if(!Wd)return null;if(Element.prototype.closest)try{return a.closest(b)}catch(e){return null}var c=Element.prototype.matches||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,d=a;if(!I.documentElement.contains(d))return null;do{try{if(c.call(d,b))return d}catch(e){break}d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType);
return null},Zd=!1;if(I.querySelectorAll)try{var $d=I.querySelectorAll(":root");$d&&1==$d.length&&$d[0]==I.documentElement&&(Zd=!0)}catch(a){}var Wd=Zd;var ae=function(a){if(I.hidden)return!0;var b=a.getBoundingClientRect();if(b.top==b.bottom||b.left==b.right||!G.getComputedStyle)return!0;var c=G.getComputedStyle(a,null);if("hidden"===c.visibility)return!0;for(var d=a,e=c;d;){if("none"===e.display)return!0;var f=e.opacity,h=e.filter;if(h){var k=h.indexOf("opacity(");0<=k&&(h=h.substring(k+8,h.indexOf(")",k)),"%"==h.charAt(h.length-1)&&(h=h.substring(0,h.length-1)),f=Math.min(h,f))}if(void 0!==f&&0>=f)return!0;(d=d.parentElement)&&(e=G.getComputedStyle(d,
null))}return!1};var je=/:[0-9]+$/,ke=function(a,b,c){for(var d=a.split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if(decodeURIComponent(f[0]).replace(/\+/g," ")===b){var h=f.slice(1).join("=");return c?h:decodeURIComponent(h).replace(/\+/g," ")}}},ne=function(a,b,c,d,e){b&&(b=String(b).toLowerCase());if("protocol"===b||"port"===b)a.protocol=le(a.protocol)||le(G.location.protocol);"port"===b?a.port=String(Number(a.hostname?a.port:G.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===b&&
(a.hostname=(a.hostname||G.location.hostname).replace(je,"").toLowerCase());return me(a,b,c,d,e)},me=function(a,b,c,d,e){var f,h=le(a.protocol);b&&(b=String(b).toLowerCase());switch(b){case "url_no_fragment":f=qe(a);break;case "protocol":f=h;break;case "host":f=a.hostname.replace(je,"").toLowerCase();if(c){var k=/^www\d*\./.exec(f);k&&k[0]&&(f=f.substr(k[0].length))}break;case "port":f=String(Number(a.port)||("http"==h?80:"https"==h?443:""));break;case "path":a.pathname||a.hostname||ra("TAGGING",
1);f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var l=f.split("/");0<=Ba(d||[],l[l.length-1])&&(l[l.length-1]="");f=l.join("/");break;case "query":f=a.search.replace("?","");e&&(f=ke(f,e,void 0));break;case "extension":var n=a.pathname.split(".");f=1<n.length?n[n.length-1]:"";f=f.split("/")[0];break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},le=function(a){return a?a.replace(":","").toLowerCase():""},qe=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");
b=0>c?a.href:a.href.substr(0,c)}return b},re=function(a){var b=I.createElement("a");a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||ra("TAGGING",1),c="/"+c);var d=b.hostname.replace(je,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}},se=function(a){function b(n){var p=n.split("=")[0];return 0>d.indexOf(p)?n:p+"=0"}function c(n){return n.split("&").map(b).filter(function(p){return void 0!=p}).join("&")}var d="gclid dclid gbraid wbraid gclaw gcldc gclha gclgf gclgb _gl".split(" "),
e=re(a),f=a.split(/[?#]/)[0],h=e.search,k=e.hash;"?"===h[0]&&(h=h.substring(1));"#"===k[0]&&(k=k.substring(1));h=c(h);k=c(k);""!==h&&(h="?"+h);""!==k&&(k="#"+k);var l=""+f+h+k;"/"===l[l.length-1]&&(l=l.substring(0,l.length-1));return l};var te=new RegExp(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i),ue=new RegExp(/@(gmail|googlemail)\./i),ve=new RegExp(/support|noreply/i),we="SCRIPT STYLE IMG SVG PATH BR".split(" "),xe=["BR"];function ye(a){var b;if(a===I.body)b="body";else{var c;if(a.id)c="#"+a.id;else{var d;if(a.parentElement){var e;a:{var f=a.parentElement;if(f){for(var h=0;h<f.childElementCount;h++)if(f.children[h]===a){e=h+1;break a}e=-1}else e=1}d=ye(a.parentElement)+">:nth-child("+e+")"}else d="";c=d}b=c}return b}
function ze(a,b){if(1>=a.length)return a;var c=a.filter(b);return 0==c.length?a:c}function Ae(a){if(0==a.length)return null;var b;b=ze(a,function(c){return!ve.test(c.wb)});b=ze(b,function(c){return"INPUT"===c.element.tagName.toUpperCase()});b=ze(b,function(c){return!ae(c.element)});return b[0]}
var Be=function(){var a;var b=[],c=I.body;if(c){for(var d=c.querySelectorAll("*"),e=0;e<d.length&&1E4>e;e++){var f=d[e];if(!(0<=we.indexOf(f.tagName.toUpperCase()))){for(var h=!1,k=0;k<f.childElementCount&&1E4>k;k++)if(!(0<=xe.indexOf(f.children[k].tagName.toUpperCase()))){h=!0;break}h||b.push(f)}}a={elements:b,status:1E4<d.length?"2":"1"}}else a={elements:b,status:"4"};for(var l=a,n=l.elements,p=[],q=0;q<n.length;q++){var r=n[q],t=r.textContent;r.value&&(t=r.value);if(t){var u=t.match(te);if(u){var v=
u[0],x;if(G.location){var z=me(G.location,"host",!0);x=0<=v.toLowerCase().indexOf(z)}else x=!1;x||p.push({element:r,wb:v})}}}var w=Ae(p),y=[];if(w){var A=w.element,C={wb:w.wb,tagName:A.tagName,type:1};C.querySelector=ye(A);C.isVisible=!ae(A);y.push(C)}return{elements:y,status:10<p.length?"3":l.status}},Ce=function(a){return a.tagName+":"+a.isVisible+":"+a.wb.length+":"+ue.test(a.wb)};var Qe={},O=null,Re=Math.random();Qe.K="GTM-T6WCVTG";Qe.xc="5c1";Qe.ai="";Qe.Vf="ChEI8OL9hAYQprfqp+vKwJeCARIkAHdyifNUOhv802qp8aMgYozqsYodcHZgwfoxrPArJzgzR068GgL04g\x3d\x3d";var Se={__cl:!0,__ecl:!0,__ehl:!0,__evl:!0,__fal:!0,__fil:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0},Te={__paused:!0,__tg:!0},Ue;for(Ue in Se)Se.hasOwnProperty(Ue)&&(Te[Ue]=!0);var Ve="www.googletagmanager.com/gtm.js";
var We=Ve,Xe=Ma(""),Ye=null,Ze=null,$e="//www.googletagmanager.com/a?id="+Qe.K+"&cv=4",af={},bf={},cf=function(){var a=O.sequence||1;O.sequence=a+1;return a};Qe.Uf="";var df={},ef=new Ga,ff={},gf={},kf={name:"dataLayer",set:function(a,b){B(ab(a,b),ff);hf()},get:function(a){return jf(a,2)},reset:function(){ef=new Ga;ff={};hf()}},jf=function(a,b){return 2!=b?ef.get(a):lf(a)},lf=function(a){var b,c=a.split(".");b=b||[];for(var d=ff,e=0;e<c.length;e++){if(null===d)return!1;if(void 0===d)break;d=d[c[e]];if(-1!==Ba(b,d))return}return d},mf=function(a,b){gf.hasOwnProperty(a)||(ef.set(a,b),B(ab(a,b),ff),hf())},hf=function(a){Ia(gf,function(b,c){ef.set(b,c);B(ab(b,
void 0),ff);B(ab(b,c),ff);a&&delete gf[b]})},of=function(a,b,c){df[a]=df[a]||{};df[a][b]=nf(b,c)},nf=function(a,b){var c,d=1!==(void 0===b?2:b)?lf(a):ef.get(a);"array"===fb(d)||"object"===fb(d)?c=B(d):c=d;return c},pf=function(a,b){if(df[a])return df[a][b]},qf=function(a,b){df[a]&&delete df[a][b]};var tf={},uf=function(a,b){if(G._gtmexpgrp&&G._gtmexpgrp.hasOwnProperty(a))return G._gtmexpgrp[a];void 0===tf[a]&&(tf[a]=Math.floor(Math.random()*b));return tf[a]};var vf=function(a){var b=1,c,d,e;if(a)for(b=0,d=a.length-1;0<=d;d--)e=a.charCodeAt(d),b=(b<<6&268435455)+e+(e<<14),c=b&266338304,b=0!=c?b^c>>21:b;return b};function wf(a,b,c){for(var d=[],e=b.split(";"),f=0;f<e.length;f++){var h=e[f].split("="),k=h[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=h.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&c&&(l=decodeURIComponent(l));d.push(l)}}return d};function xf(a){return"null"!==a.origin};var Af=function(a,b,c,d){return yf(d)?wf(a,String(b||zf()),c):[]},Df=function(a,b,c,d,e){if(yf(e)){var f=Bf(a,d,e);if(1===f.length)return f[0].id;if(0!==f.length){f=Cf(f,function(h){return h.Fc},b);if(1===f.length)return f[0].id;f=Cf(f,function(h){return h.Sb},c);return f[0]?f[0].id:void 0}}};function Ef(a,b,c,d){var e=zf(),f=window;xf(f)&&(f.document.cookie=a);var h=zf();return e!=h||void 0!=c&&0<=Af(b,h,!1,d).indexOf(c)}
var If=function(a,b,c){function d(t,u,v){if(null==v)return delete h[u],t;h[u]=v;return t+"; "+u+"="+v}function e(t,u){if(null==u)return delete h[u],t;h[u]=!0;return t+"; "+u}if(!yf(c.Ha))return 2;var f;void 0==b?f=a+"=deleted; expires="+(new Date(0)).toUTCString():(c.encode&&(b=encodeURIComponent(b)),b=Ff(b),f=a+"="+b);var h={};f=d(f,"path",c.path);var k;c.expires instanceof Date?k=c.expires.toUTCString():null!=c.expires&&(k=""+c.expires);f=d(f,"expires",k);f=d(f,"max-age",c.mi);f=d(f,"samesite",
c.ni);c.oi&&(f=e(f,"secure"));var l=c.domain;if("auto"===l){for(var n=Gf(),p=0;p<n.length;++p){var q="none"!==n[p]?n[p]:void 0,r=d(f,"domain",q);r=e(r,c.flags);if(!Hf(q,c.path)&&Ef(r,a,b,c.Ha))return 0}return 1}l&&"none"!==l&&(f=d(f,"domain",l));f=e(f,c.flags);return Hf(l,c.path)?1:Ef(f,a,b,c.Ha)?0:1},Jf=function(a,b,c){null==c.path&&(c.path="/");c.domain||(c.domain="auto");return If(a,b,c)};
function Cf(a,b,c){for(var d=[],e=[],f,h=0;h<a.length;h++){var k=a[h],l=b(k);l===c?d.push(k):void 0===f||l<f?(e=[k],f=l):l===f&&e.push(k)}return 0<d.length?d:e}function Bf(a,b,c){for(var d=[],e=Af(a,void 0,void 0,c),f=0;f<e.length;f++){var h=e[f].split("."),k=h.shift();if(!b||-1!==b.indexOf(k)){var l=h.shift();l&&(l=l.split("-"),d.push({id:h.join("."),Fc:1*l[0]||1,Sb:1*l[1]||1}))}}return d}
var Ff=function(a){a&&1200<a.length&&(a=a.substring(0,1200));return a},Kf=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Rf=/(^|\.)doubleclick\.net$/i,Hf=function(a,b){return Rf.test(window.document.location.hostname)||"/"===b&&Kf.test(a)},zf=function(){return xf(window)?window.document.cookie:""},Gf=function(){var a=[],b=window.document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(var d=b.length-2;0<=d;d--)a.push(b.slice(d).join("."));
var e=window.document.location.hostname;Rf.test(e)||Kf.test(e)||a.push("none");return a},yf=function(a){if(!zd(Ec)||!a||!Kd())return!0;if(!Jd(a))return!1;var b=Hd(a);return null==b?!0:!!b};var Sf=function(a,b){a.addEventListener&&a.addEventListener.call(a,"message",b,!1)};var Tf=function(){return Vc("iPhone")&&!Vc("iPod")&&!Vc("iPad")};Vc("Opera");Vc("Trident")||Vc("MSIE");Vc("Edge");!Vc("Gecko")||-1!=Mc.toLowerCase().indexOf("webkit")&&!Vc("Edge")||Vc("Trident")||Vc("MSIE")||Vc("Edge");-1!=Mc.toLowerCase().indexOf("webkit")&&!Vc("Edge")&&Vc("Mobile");Vc("Macintosh");Vc("Windows");Vc("Linux")||Vc("CrOS");var Uf=oa.navigator||null;Uf&&(Uf.appVersion||"").indexOf("X11");Vc("Android");Tf();Vc("iPad");Vc("iPod");Tf()||Vc("iPad")||Vc("iPod");Mc.toLowerCase().indexOf("kaios");var Vf=function(){if(!G.crypto)return Math.random();try{var a=new Uint32Array(1);G.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}},Wf=function(a,b){for(var c=a,d=0;50>d;++d){var e;try{e=!(!c.frames||!c.frames[b])}catch(k){e=!1}if(e)return c;var f;a:{try{var h=c.parent;if(h&&h!=c){f=h;break a}}catch(k){}f=null}if(!(c=f))break}return null};var Xf=function(a,b){for(var c=""+(a?"":fd.userAgent)+((xf(G)?I.cookie:null)||"")+(I.referrer||""),d=c.length,e=G.history.length;0<e;)c+=e--^d++;return[Math.round(2147483647*(b?Vf():Math.random()))^vf(c)&2147483647,Math.round(Qa()/1E3)].join(".")},$f=function(a,b,c,d,e){var f=Yf(b);return Df(a,f,Zf(c),d,e)},ag=function(a,b,c,d){var e=""+Yf(c),f=Zf(d);1<f&&(e+="-"+f);return[b,e,a].join(".")},Yf=function(a){if(!a)return 1;a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length},Zf=function(a){if(!a||
"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1};function bg(a,b,c){var d,e=Number(null!=a.tb?a.tb:void 0);0!==e&&(d=new Date((b||Qa())+1E3*(e||7776E3)));return{path:a.path,domain:a.domain,flags:a.flags,encode:!!c,expires:d}};var cg=["1"],dg={},hg=function(a){var b=eg(a.prefix);if(!dg[b]&&!fg(b,a.path,a.domain)){var c=Xf();if(0===gg(b,c,a)){var d=hd("google_tag_data",{});d._gcl_au?ra("GTM",57):d._gcl_au=c}fg(b,a.path,a.domain)}};function gg(a,b,c){var d=ag(b,"1",c.domain,c.path),e=bg(c);e.Ha="ad_storage";return Jf(a,d,e)}function fg(a,b,c){var d=$f(a,b,c,cg,"ad_storage");d&&(dg[a]=d);return d}function eg(a){return(a||"_gcl")+"_au"};var ig=function(a){for(var b=[],c=I.cookie.split(";"),d=new RegExp("^\\s*"+(a||"_gac")+"_(UA-\\d+-\\d+)=\\s*(.+?)\\s*$"),e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push({Yd:f[1],value:f[2],timestamp:Number(f[2].split(".")[1])||0})}b.sort(function(h,k){return k.timestamp-h.timestamp});return b};
function jg(a,b){var c=ig(a),d={};if(!c||!c.length)return d;for(var e=0;e<c.length;e++){var f=c[e].value.split(".");if(!("1"!==f[0]||b&&3>f.length||!b&&3!==f.length)&&Number(f[1])){d[c[e].Yd]||(d[c[e].Yd]=[]);var h={version:f[0],timestamp:1E3*Number(f[1]),ma:f[2]};b&&3<f.length&&(h.labels=f.slice(3));d[c[e].Yd].push(h)}}return d};function kg(){for(var a=lg,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function mg(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}var lg,ng;
function og(a){function b(l){for(;d<a.length;){var n=a.charAt(d++),p=ng[n];if(null!=p)return p;if(!/^[\s\xa0]*$/.test(n))throw Error("Unknown base64 encoding at char: "+n);}return l}lg=lg||mg();ng=ng||kg();for(var c="",d=0;;){var e=b(-1),f=b(0),h=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|f>>4);64!=h&&(c+=String.fromCharCode(f<<4&240|h>>2),64!=k&&(c+=String.fromCharCode(h<<6&192|k)))}};var pg;var tg=function(){var a=qg,b=rg,c=sg(),d=function(h){a(h.target||h.srcElement||{})},e=function(h){b(h.target||h.srcElement||{})};if(!c.init){nd(I,"mousedown",d);nd(I,"keyup",d);nd(I,"submit",e);var f=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=function(){b(this);f.call(this)};c.init=!0}},ug=function(a,b,c,d,e){var f={callback:a,domains:b,fragment:2===c,placement:c,forms:d,sameHost:e};sg().decorators.push(f)},vg=function(a,b,c){for(var d=sg().decorators,e={},f=0;f<d.length;++f){var h=
d[f],k;if(k=!c||h.forms)a:{var l=h.domains,n=a,p=!!h.sameHost;if(l&&(p||n!==I.location.hostname))for(var q=0;q<l.length;q++)if(l[q]instanceof RegExp){if(l[q].test(n)){k=!0;break a}}else if(0<=n.indexOf(l[q])||p&&0<=l[q].indexOf(n)){k=!0;break a}k=!1}if(k){var r=h.placement;void 0==r&&(r=h.fragment?2:1);r===b&&Xa(e,h.callback())}}return e},sg=function(){var a=hd("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var wg=/(.*?)\*(.*?)\*(.*)/,xg=/^https?:\/\/([^\/]*?)\.?cdn\.ampproject\.org\/?(.*)/,yg=/^(?:www\.|m\.|amp\.)+/,zg=/([^?#]+)(\?[^#]*)?(#.*)?/;function Ag(a){return new RegExp("(.*?)(^|&)"+a+"=([^&]*)&?(.*)")}
var Cg=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];if(void 0!==d&&d===d&&null!==d&&"[object Object]"!==d.toString()){b.push(c);var e=b,f=e.push,h,k=String(d);lg=lg||mg();ng=ng||kg();for(var l=[],n=0;n<k.length;n+=3){var p=n+1<k.length,q=n+2<k.length,r=k.charCodeAt(n),t=p?k.charCodeAt(n+1):0,u=q?k.charCodeAt(n+2):0,v=r>>2,x=(r&3)<<4|t>>4,z=(t&15)<<2|u>>6,w=u&63;q||(w=64,p||(z=64));l.push(lg[v],lg[x],lg[z],lg[w])}h=l.join("");f.call(e,h)}}var y=b.join("*");return["1",Bg(y),
y].join("*")},Bg=function(a,b){var c=[window.navigator.userAgent,(new Date).getTimezoneOffset(),window.navigator.userLanguage||window.navigator.language,Math.floor((new Date).getTime()/60/1E3)-(void 0===b?0:b),a].join("*"),d;if(!(d=pg)){for(var e=Array(256),f=0;256>f;f++){for(var h=f,k=0;8>k;k++)h=h&1?h>>>1^3988292384:h>>>1;e[f]=h}d=e}pg=d;for(var l=4294967295,n=0;n<c.length;n++)l=l>>>8^pg[(l^c.charCodeAt(n))&255];return((l^-1)>>>0).toString(36)},Eg=function(){return function(a){var b=re(G.location.href),
c=b.search.replace("?",""),d=ke(c,"_gl",!0)||"";a.query=Dg(d)||{};var e=ne(b,"fragment").match(Ag("_gl"));a.fragment=Dg(e&&e[3]||"")||{}}},Fg=function(a){var b=Eg(),c=sg();c.data||(c.data={query:{},fragment:{}},b(c.data));var d={},e=c.data;e&&(Xa(d,e.query),a&&Xa(d,e.fragment));return d},Dg=function(a){var b;b=void 0===b?3:b;try{if(a){var c;a:{for(var d=a,e=0;3>e;++e){var f=wg.exec(d);if(f){c=f;break a}d=decodeURIComponent(d)}c=void 0}var h=c;if(h&&"1"===h[1]){var k=h[3],l;a:{for(var n=h[2],p=0;p<
b;++p)if(n===Bg(k,p)){l=!0;break a}l=!1}if(l){for(var q={},r=k?k.split("*"):[],t=0;t<r.length;t+=2)q[r[t]]=og(r[t+1]);return q}}}}catch(u){}};function Gg(a,b,c,d){function e(p){var q=p,r=Ag(a).exec(q),t=q;if(r){var u=r[2],v=r[4];t=r[1];v&&(t=t+u+v)}p=t;var x=p.charAt(p.length-1);p&&"&"!==x&&(p+="&");return p+n}d=void 0===d?!1:d;var f=zg.exec(c);if(!f)return"";var h=f[1],k=f[2]||"",l=f[3]||"",n=a+"="+b;d?l="#"+e(l.substring(1)):k="?"+e(k.substring(1));return""+h+k+l}
function Hg(a,b){var c="FORM"===(a.tagName||"").toUpperCase(),d=vg(b,1,c),e=vg(b,2,c),f=vg(b,3,c);if(Za(d)){var h=Cg(d);c?Ig("_gl",h,a):Jg("_gl",h,a,!1)}if(!c&&Za(e)){var k=Cg(e);Jg("_gl",k,a,!0)}for(var l in f)if(f.hasOwnProperty(l))a:{var n=l,p=f[l],q=a;if(q.tagName){if("a"===q.tagName.toLowerCase()){Jg(n,p,q,void 0);break a}if("form"===q.tagName.toLowerCase()){Ig(n,p,q);break a}}"string"==typeof q&&Gg(n,p,q,void 0)}}
function Jg(a,b,c,d){if(c.href){var e=Gg(a,b,c.href,void 0===d?!1:d);Lc.test(e)&&(c.href=e)}}
function Ig(a,b,c){if(c&&c.action){var d=(c.method||"").toLowerCase();if("get"===d){for(var e=c.childNodes||[],f=!1,h=0;h<e.length;h++){var k=e[h];if(k.name===a){k.setAttribute("value",b);f=!0;break}}if(!f){var l=I.createElement("input");l.setAttribute("type","hidden");l.setAttribute("name",a);l.setAttribute("value",b);c.appendChild(l)}}else if("post"===d){var n=Gg(a,b,c.action);Lc.test(n)&&(c.action=n)}}}
var qg=function(a){try{var b;a:{for(var c=a,d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var f=e.protocol;"http:"!==f&&"https:"!==f||Hg(e,e.hostname)}}catch(h){}},rg=function(a){try{if(a.action){var b=ne(re(a.action),"host");Hg(a,b)}}catch(c){}},Kg=function(a,b,c,d){tg();ug(a,b,"fragment"===c?2:1,!!d,!1)},Lg=function(a,b){tg();ug(a,[me(G.location,"host",!0)],b,!0,!0)},Mg=function(){var a=I.location.hostname,b=xg.exec(I.referrer);if(!b)return!1;
var c=b[2],d=b[1],e="";if(c){var f=c.split("/"),h=f[1];e="s"===h?decodeURIComponent(f[2]):decodeURIComponent(h)}else if(d){if(0===d.indexOf("xn--"))return!1;e=d.replace(/-/g,".").replace(/\.\./g,"-")}var k=a.replace(yg,""),l=e.replace(yg,""),n;if(!(n=k===l)){var p="."+l;n=k.substring(k.length-p.length,k.length)===p}return n},Ng=function(a,b){return!1===a?!1:a||b||Mg()};var Og={};var Pg=/^\w+$/,Qg=/^[\w-]+$/,Rg={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha",gp:"_gp",gb:"_gb"},Sg=function(){if(!zd(Ec)||!Kd())return!0;var a=Hd("ad_storage");return null==a?!0:!!a},Tg=function(a,b){Jd("ad_storage")?Sg()?a():Od(a,"ad_storage"):b?ra("TAGGING",3):Nd(function(){Tg(a,!0)},["ad_storage"])},Vg=function(a){return Ug(a).map(function(b){return b.ma})},Ug=function(a){var b=[];if(!xf(G)||!I.cookie)return b;var c=Af(a,I.cookie,void 0,"ad_storage");if(!c||0==c.length)return b;for(var d={},e=0;e<c.length;d=
{Yb:d.Yb},e++){var f=Wg(c[e]);if(null!=f){var h=f,k=h.version;d.Yb=h.ma;var l=h.timestamp,n=h.labels,p=Da(b,function(q){return function(r){return r.ma===q.Yb}}(d));p?(p.timestamp=Math.max(p.timestamp,l),p.labels=Xg(p.labels,n||[])):b.push({version:k,ma:d.Yb,timestamp:l,labels:n})}}b.sort(function(q,r){return r.timestamp-q.timestamp});return Yg(b)};function Xg(a,b){for(var c={},d=[],e=0;e<a.length;e++)c[a[e]]=!0,d.push(a[e]);for(var f=0;f<b.length;f++)c[b[f]]||d.push(b[f]);return d}
function Zg(a){return a&&"string"==typeof a&&a.match(Pg)?a:"_gcl"}
var ah=function(){var a=re(G.location.href),b=ne(a,"query",!1,void 0,"gclid"),c=ne(a,"query",!1,void 0,"gclsrc"),d=ne(a,"query",!1,void 0,"wbraid"),e=ne(a,"query",!1,void 0,"dclid");if(!b||!c||!d){var f=a.hash.replace("#","");b=b||ke(f,"gclid",void 0);c=c||ke(f,"gclsrc",void 0);d=d||ke(f,"wbraid",void 0)}return $g(b,c,e,d)},$g=function(a,b,c,d){var e={},f=function(h,k){e[k]||(e[k]=[]);e[k].push(h)};e.gclid=a;e.gclsrc=b;e.dclid=c;void 0!==d&&Qg.test(d)&&(e.gbraid=d,f(d,"gb"));if(void 0!==a&&a.match(Qg))switch(b){case void 0:f(a,
"aw");break;case "aw.ds":f(a,"aw");f(a,"dc");break;case "ds":f(a,"dc");break;case "3p.ds":f(a,"dc");break;case "gf":f(a,"gf");break;case "ha":f(a,"ha")}c&&f(c,"dc");return e},bh=function(a,b){switch(a){case void 0:case "aw":return"aw"===b;case "aw.ds":return"aw"===b||"dc"===b;case "ds":case "3p.ds":return"dc"===b;case "gf":return"gf"===b;case "ha":return"ha"===b}return!1},dh=function(a){var b=ah();Tg(function(){ch(b,a)})};
function ch(a,b,c,d){function e(p,q){var r=eh(p,f);r&&(Jf(r,q,h),k=!0)}b=b||{};d=d||[];var f=Zg(b.prefix);c=c||Qa();var h=bg(b,c,!0);h.Ha="ad_storage";var k=!1,l=Math.round(c/1E3),n=function(p){var q=["GCL",l,p];0<d.length&&q.push(d.join("."));return q.join(".")};a.aw&&e("aw",n(a.aw[0]));a.dc&&e("dc",n(a.dc[0]));a.gf&&e("gf",n(a.gf[0]));a.ha&&e("ha",n(a.ha[0]));a.gp&&e("gp",n(a.gp[0]));(void 0==Og.enable_gbraid_cookie_write?0:Og.enable_gbraid_cookie_write)&&!k&&a.gb&&e("gb",n(a.gb[0]))}
var gh=function(a,b){var c=Fg(!0);Tg(function(){for(var d=Zg(b.prefix),e=0;e<a.length;++e){var f=a[e];if(void 0!==Rg[f]){var h=eh(f,d),k=c[h];if(k){var l=Math.min(fh(k),Qa()),n;b:{var p=l;if(xf(G))for(var q=Af(h,I.cookie,void 0,"ad_storage"),r=0;r<q.length;++r)if(fh(q[r])>p){n=!0;break b}n=!1}if(!n){var t=bg(b,l,!0);t.Ha="ad_storage";Jf(h,k,t)}}}}ch($g(c.gclid,c.gclsrc),b)})},eh=function(a,b){var c=Rg[a];if(void 0!==c)return b+c},fh=function(a){return 0!==hh(a.split(".")).length?1E3*(Number(a.split(".")[1])||
0):0};function Wg(a){var b=hh(a.split("."));return 0===b.length?null:{version:b[0],ma:b[2],timestamp:1E3*(Number(b[1])||0),labels:b.slice(3)}}function hh(a){return 3>a.length||"GCL"!==a[0]&&"1"!==a[0]||!/^\d+$/.test(a[1])||!Qg.test(a[2])?[]:a}
var ih=function(a,b,c,d,e){if(wa(b)&&xf(G)){var f=Zg(e),h=function(){for(var k={},l=0;l<a.length;++l){var n=eh(a[l],f);if(n){var p=Af(n,I.cookie,void 0,"ad_storage");p.length&&(k[n]=p.sort()[p.length-1])}}return k};Tg(function(){Kg(h,b,c,d)})}},Yg=function(a){return a.filter(function(b){return Qg.test(b.ma)})},jh=function(a,b){if(xf(G)){for(var c=Zg(b.prefix),d={},e=0;e<a.length;e++)Rg[a[e]]&&(d[a[e]]=Rg[a[e]]);Tg(function(){Ia(d,function(f,h){var k=Af(c+h,I.cookie,void 0,"ad_storage");k.sort(function(t,
u){return fh(u)-fh(t)});if(k.length){var l=k[0],n=fh(l),p=0!==hh(l.split(".")).length?l.split(".").slice(3):[],q={},r;r=0!==hh(l.split(".")).length?l.split(".")[2]:void 0;q[f]=[r];ch(q,b,n,p)}})})}};function kh(a,b){for(var c=0;c<b.length;++c)if(a[b[c]])return!0;return!1}
var lh=function(a){function b(e,f,h){h&&(e[f]=h)}if(Kd()){var c=ah();if(kh(c,a)){var d={};b(d,"gclid",c.gclid);b(d,"dclid",c.dclid);b(d,"gclsrc",c.gclsrc);b(d,"wbraid",c.gbraid);Lg(function(){return d},3);Lg(function(){var e={};return e._up="1",e},1)}}};function mh(a,b){var c=Zg(b),d=eh(a,c);if(!d)return 0;for(var e=Ug(d),f=0,h=0;h<e.length;h++)f=Math.max(f,e[h].timestamp);return f}
function nh(a){var b=0,c;for(c in a)for(var d=a[c],e=0;e<d.length;e++)b=Math.max(b,Number(d[e].timestamp));return b};var oh=/^\d+\.fls\.doubleclick\.net$/;function ph(a,b){Jd(E.B)?N(E.B)?a():Od(a,E.B):b?Bc(42):Vd(function(){ph(a,!0)},[E.B])}function qh(a){var b=re(G.location.href),c=ne(b,"host",!1);if(c&&c.match(oh)){var d=ne(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function rh(a,b,c){if("aw"===a||"dc"===a||"gb"===a){var d=qh("gcl"+a);if(d)return d.split(".")}var e=Zg(b);if("_gcl"==e){c=void 0===c?!0:c;var f=!N(E.B)&&c,h;h=ah()[a]||[];if(0<h.length)return f?["0"]:h}var k=eh(a,e);return k?Vg(k):[]}function sh(a){var b=[];Ia(a,function(c,d){d=Yg(d);for(var e=[],f=0;f<d.length;f++)e.push(d[f].ma);e.length&&b.push(c+":"+e.join(","))});return b.join(";")}
var th=function(a){var b=qh("gac");return b?!N(E.B)&&a?"0":decodeURIComponent(b):sh(Sg()?jg():{})},uh=function(a){var b=qh("gacgb");return b?!N(E.B)&&a?"0":decodeURIComponent(b):sh(Sg()?jg("_gac_gb",!0):{})},vh=function(a,b,c){var d=ah(),e=[],f=d.gclid,h=d.dclid,k=d.gclsrc||"aw";!f||"aw.ds"!==k&&"aw"!==k&&"ds"!==k||c&&!bh(k,c)||e.push({ma:f,Dd:k});!h||c&&"dc"!==c||e.push({ma:h,Dd:"ds"});ph(function(){hg(b);var l=dg[eg(b.prefix)],n=!1;if(l&&0<e.length)for(var p=O.joined_auid=O.joined_auid||{},q=0;q<e.length;q++){var r=e[q],t=r.ma,u=r.Dd,v=(b.prefix||"_gcl")+"."+u+"."+t;if(!p[v]){var x="https://adservice.google.com/pagead/regclk";x="gb"===u?x+"?gbraid="+t+"&auid="+l:x+"?gclid="+t+"&auid="+l+"&gclsrc="+u;wd(x);n=p[v]=!0}}null==a&&(a=n);if(a&&
l){var z=eg(b.prefix),w=dg[z];w&&gg(z,w,b)}})},wh=function(a){var b;if(qh("gclaw")||qh("gac")||0<(ah().aw||[]).length)b=!1;else{var c;if(0<(ah().gb||[]).length)c=!0;else{var d=Math.max(mh("aw",a),nh(Sg()?jg():{}));c=Math.max(mh("gb",a),nh(Sg()?jg("_gac_gb",!0):{}))>d}b=c}return b};var xh=/[A-Z]+/,yh=/\s/,zh=function(a){if(m(a)&&(a=Oa(a),!yh.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(xh.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],F:d}}}}},Bh=function(a){for(var b={},c=0;c<a.length;++c){var d=zh(a[c]);d&&(b[d.id]=d)}Ah(b);var e=[];Ia(b,function(f,h){e.push(h)});return e};
function Ah(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];"AW"===d.prefix&&d.F[1]&&b.push(d.containerId)}for(var e=0;e<b.length;++e)delete a[b[e]]};var Ch=function(){var a=!1;return a};var Eh=function(a,b,c,d){return(2===Dh()||d||"http:"!=G.location.protocol?a:b)+c},Dh=function(){var a=kd(),b;if(1===a)a:{var c=We;c=c.toLowerCase();for(var d="https://"+c,e="http://"+c,f=1,h=I.getElementsByTagName("script"),k=0;k<h.length&&100>k;k++){var l=h[k].src;if(l){l=l.toLowerCase();if(0===l.indexOf(e)){b=3;break a}1===f&&0===l.indexOf(d)&&(f=2)}}b=f}else b=a;return b};
var Sh=function(a){if(N(E.B))return a;a=a.replace(/&url=([^&#]+)/,function(b,c){var d=se(decodeURIComponent(c));return"&url="+encodeURIComponent(d)});a=a.replace(/&ref=([^&#]+)/,function(b,c){var d=se(decodeURIComponent(c));return"&ref="+encodeURIComponent(d)});return a},Th=function(){var a;if(!(a=Xe)){var b;if(!0===G._gtmdgs)b=!0;else{var c=fd&&fd.userAgent||"";b=0>c.indexOf("Safari")||/Chrome|Coast|Opera|Edg|Silk|Android/.test(c)||
11>((/Version\/([\d]+)/.exec(c)||[])[1]||"")?!1:!0}a=!b}if(a)return-1;var d=La("1");return uf(1,100)<d?uf(2,2):-1},Uh=function(a){var b;if(!a||!a.length)return;for(var c=[],d=0;d<a.length;++d){var e=a[d];e&&e.estimated_delivery_date?c.push(""+e.estimated_delivery_date):c.push("")}b=c.join(",");return b};var Vh=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Wh={cl:["ecl"],customPixels:["nonGooglePixels"],ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Xh={cl:["ecl"],customPixels:["customScripts","html"],
ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Yh="google customPixels customScripts html nonGooglePixels nonGoogleScripts nonGoogleIframes".split(" ");
var Zh=function(){var a=!1;return a},ai=function(a){var b=jf("gtm.allowlist")||jf("gtm.whitelist");b&&Bc(9);Zh()&&(b="google gtagfl lcl zone oid op".split(" "));var c=b&&$a(Na(b),Wh),d=jf("gtm.blocklist")||
jf("gtm.blacklist");d||(d=jf("tagTypeBlacklist"))&&Bc(3);d?Bc(8):d=[];$h()&&(d=Na(d),d.push("nonGooglePixels","nonGoogleScripts","sandboxedScripts"));0<=Ba(Na(d),"google")&&Bc(2);var e=d&&$a(Na(d),Xh),f={};return function(h){var k=h&&h[kb.Ta];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==f[k])return f[k];var l=bf[k]||[],n=a(k,l);if(b){var p;if(p=
n)a:{if(0>Ba(c,k))if(l&&0<l.length)for(var q=0;q<l.length;q++){if(0>Ba(c,l[q])){Bc(11);p=!1;break a}}else{p=!1;break a}p=!0}n=p}var r=!1;if(d){var t=0<=Ba(e,k);if(t)r=t;else{var u=Ha(e,l||[]);u&&Bc(10);r=u}}var v=!n||r;v||!(0<=Ba(l,"sandboxedScripts"))||c&&-1!==Ba(c,"sandboxedScripts")||(v=Ha(e,Yh));return f[k]=v}},$h=function(){return Vh.test(G.location&&G.location.hostname)};var bi={active:!0,isAllowed:function(){return!0}},ci=function(a){var b=O.zones;return b?b.checkState(Qe.K,a):bi},di=function(a){var b=O.zones;!b&&a&&(b=O.zones=a());return b};var ei=function(){},fi=function(){};var gi=!1,hi=0,ii=[];function ji(a){if(!gi){var b=I.createEventObject,c="complete"==I.readyState,d="interactive"==I.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){gi=!0;for(var e=0;e<ii.length;e++)J(ii[e])}ii.push=function(){for(var f=0;f<arguments.length;f++)J(arguments[f]);return 0}}}function ki(){if(!gi&&140>hi){hi++;try{I.documentElement.doScroll("left"),ji()}catch(a){G.setTimeout(ki,50)}}}var li=function(a){gi?a():ii.push(a)};var ri=function(a,b){this.m=!1;this.H=[];this.X={tags:[]};this.da=!1;this.o=this.C=0;qi(this,a,b)},si=function(a,b,c,d){if(Te.hasOwnProperty(b)||"__zone"===b)return-1;var e={};ib(d)&&(e=B(d,e));e.id=c;e.status="timeout";return a.X.tags.push(e)-1},ti=function(a,b,c,d){var e=a.X.tags[b];e&&(e.status=c,e.executionTime=d)},ui=function(a){if(!a.m){for(var b=a.H,c=0;c<b.length;c++)b[c]();a.m=!0;a.H.length=0}},qi=function(a,b,c){ua(b)&&vi(a,b);c&&G.setTimeout(function(){return ui(a)},Number(c))},vi=function(a,
b){var c=Va(function(){return J(function(){b(Qe.K,a.X)})});a.m?c():a.H.push(c)},wi=function(a){a.C++;return Va(function(){a.o++;a.da&&a.o>=a.C&&ui(a)})};var xi=function(){function a(d){return!va(d)||0>d?0:d}if(!O._li&&G.performance&&G.performance.timing){var b=G.performance.timing.navigationStart,c=va(kf.get("gtm.start"))?kf.get("gtm.start"):0;O._li={cst:a(c-b),cbt:a(Ze-b)}}};var Bi={},Ci=function(){return G.GoogleAnalyticsObject&&G[G.GoogleAnalyticsObject]},Di=!1;
var Ii=function(a){},Hi=function(){return G.GoogleAnalyticsObject||"ga"},Ji=function(a,b){return function(){var c=Ci(),d=c&&c.getByName&&c.getByName(a);if(d){var e=d.get("sendHitTask");d.set("sendHitTask",function(f){var h=f.get("hitPayload"),k=f.get("hitCallback"),l=0>h.indexOf("&tid="+b);l&&(f.set("hitPayload",h.replace(/&tid=UA-[0-9]+-[0-9]+/,"&tid="+
b),!0),f.set("hitCallback",void 0,!0));e(f);l&&(f.set("hitPayload",h,!0),f.set("hitCallback",k,!0),f.set("_x_19",void 0,!0),e(f))})}}};
var Oi=function(){return"&tc="+Qb.filter(function(a){return a}).length},Ri=function(){2022<=Pi().length&&Qi()},Ti=function(){Si||(Si=G.setTimeout(Qi,500))},Qi=function(){Si&&(G.clearTimeout(Si),Si=void 0);void 0===Ui||Vi[Ui]&&!Wi&&!Xi||(Yi[Ui]||Zi.vh()||0>=$i--?(Bc(1),Yi[Ui]=!0):(Zi.Nh(),md(Pi()),Vi[Ui]=!0,aj=bj=cj=Xi=Wi=""))},Pi=function(){var a=Ui;if(void 0===a)return"";var b=sa("GTM"),c=sa("TAGGING");return[dj,Vi[a]?"":"&es=1",ej[a],b?"&u="+b:"",c?"&ut="+c:"",Oi(),Wi,Xi,cj?cj:"",bj,aj,"&z=0"].join("")},
gj=function(){dj=fj()},fj=function(){return[$e,"&v=3&t=t","&pid="+Ea(),"&rv="+Qe.xc].join("")},hj="0.005000">Math.random(),dj=fj(),Vi={},Wi="",Xi="",aj="",bj="",cj="",Ui=void 0,ej={},Yi={},Si=void 0,Zi=function(a,b){var c=0,d=0;return{vh:function(){if(c<a)return!1;Qa()-d>=b&&(c=0);return c>=a},Nh:function(){Qa()-d>=b&&(c=0);c++;d=Qa()}}}(2,1E3),$i=1E3,ij=function(a,b,c){if(hj&&!Yi[a]&&b){a!==Ui&&(Qi(),Ui=a);var d,e=String(b[kb.Ta]||"").replace(/_/g,"");0===e.indexOf("cvt")&&(e="cvt");
d=e;var f=c+d;Wi=Wi?Wi+"."+f:"&tr="+f;var h=b["function"];if(!h)throw Error("Error: No function name given for function call.");var k=(Sb[h]?"1":"2")+d;aj=aj?aj+"."+k:"&ti="+k;Ti();Ri()}},jj=function(a,b,c){if(hj&&!Yi[a]){a!==Ui&&(Qi(),Ui=a);var d=c+b;Xi=Xi?Xi+"."+d:"&epr="+d;Ti();Ri()}},kj=function(a,b,c){};
function lj(a,b,c,d){var e=Qb[a],f=mj(a,b,c,d);if(!f)return null;var h=Xb(e[kb.df],c,[]);if(h&&h.length){var k=h[0];f=lj(k.index,{onSuccess:f,onFailure:1===k.vf?b.terminate:f,terminate:b.terminate},c,d)}return f}
function mj(a,b,c,d){function e(){if(f[kb.Ig])k();else{var x=Yb(f,c,[]);var y=si(c.Ua,String(f[kb.Ta]),Number(f[kb.ef]),x[kb.Jg]),A=!1;x.vtp_gtmOnSuccess=function(){if(!A){A=!0;var D=Qa()-F;ij(c.id,Qb[a],"5");ti(c.Ua,y,"success",
D);h()}};x.vtp_gtmOnFailure=function(){if(!A){A=!0;var D=Qa()-F;ij(c.id,Qb[a],"6");ti(c.Ua,y,"failure",D);k()}};x.vtp_gtmTagId=f.tag_id;x.vtp_gtmEventId=c.id;ij(c.id,f,"1");var C=function(){var D=Qa()-F;ij(c.id,f,"7");ti(c.Ua,y,"exception",D);A||(A=!0,k())};var F=Qa();try{Wb(x,c)}catch(D){C(D)}}}var f=Qb[a],h=b.onSuccess,k=b.onFailure,l=b.terminate;if(c.Jd(f))return null;var n=Xb(f[kb.ff],c,[]);if(n&&n.length){var p=n[0],q=lj(p.index,{onSuccess:h,onFailure:k,terminate:l},c,d);if(!q)return null;h=q;k=2===p.vf?l:q}if(f[kb.Xe]||f[kb.Lg]){var r=f[kb.Xe]?Rb:
c.Uh,t=h,u=k;if(!r[a]){e=Va(e);var v=nj(a,r,e);h=v.onSuccess;k=v.onFailure}return function(){r[a](t,u)}}return e}function nj(a,b,c){var d=[],e=[];b[a]=oj(d,e,c);return{onSuccess:function(){b[a]=pj;for(var f=0;f<d.length;f++)d[f]()},onFailure:function(){b[a]=qj;for(var f=0;f<e.length;f++)e[f]()}}}function oj(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function pj(a){a()}function qj(a,b){b()};var tj=function(a,b){for(var c=[],d=0;d<Qb.length;d++)if(a[d]){var e=Qb[d];var f=wi(b.Ua);try{var h=lj(d,{onSuccess:f,onFailure:f,terminate:f},b,d);if(h){var k=c,l=k.push,n=d,p=e["function"];if(!p)throw"Error: No function name given for function call.";var q=Sb[p];l.call(k,{Mf:n,Ef:q?q.priorityOverride||0:0,jh:h})}else rj(d,b),f()}catch(u){f()}}var r=b.Ua;r.da=!0;r.o>=r.C&&ui(r);c.sort(sj);for(var t=0;t<c.length;t++)c[t].jh();
return 0<c.length};function sj(a,b){var c,d=b.Ef,e=a.Ef;c=d>e?1:d<e?-1:0;var f;if(0!==c)f=c;else{var h=a.Mf,k=b.Mf;f=h>k?1:h<k?-1:0}return f}function rj(a,b){if(!hj)return;var c=function(d){var e=b.Jd(Qb[d])?"3":"4",f=Xb(Qb[d][kb.df],b,[]);f&&f.length&&c(f[0].index);ij(b.id,Qb[d],e);var h=Xb(Qb[d][kb.ff],b,[]);h&&h.length&&c(h[0].index)};c(a);}
var uj=!1,Aj=function(a){var b=a["gtm.uniqueEventId"],c=a.event;if("gtm.js"===c){if(uj)return!1;uj=!0}var d=ci(b),e=!1;if(!d.active){if("gtm.js"!==c)return!1;e=!0;d=ci(Number.MAX_SAFE_INTEGER)}hj&&!Yi[b]&&Ui!==b&&(Qi(),Ui=b,aj=Wi="",ej[b]="&e="+(0===c.indexOf("gtm.")?encodeURIComponent(c):"*")+"&eid="+b,Ti());var f=a.eventCallback,h=a.eventTimeout,k={id:b,name:c,Jd:ai(d.isAllowed),Uh:[],Af:function(){Bc(6)},nf:vj(b),Ua:new ri(f,
h)};xj(b,k.Ua);var l=bc(k);e&&(l=yj(l));var n=tj(l,k);"gtm.js"!==c&&"gtm.sync"!==c||Ii(Qe.K);switch(c){case "gtm.init":n&&Bc(20)}return zj(l,n)};function vj(a){return function(b){hj&&(jb(b)||kj(a,"input",b))}}
function xj(a,b){of(a,"event",1);of(a,"ecommerce",1);of(a,"gtm");of(a,"eventModel");}function wj(){var a={};a.event=nf("event",1);a.ecommerce=nf("ecommerce",1);a.gtm=nf("gtm");a.eventModel=nf("eventModel");return a}function yj(a){for(var b=[],c=0;c<a.length;c++)a[c]&&Se[String(Qb[c][kb.Ta])]&&(b[c]=!0);return b}
function zj(a,b){if(!b)return b;for(var c=0;c<a.length;c++)if(a[c]&&Qb[c]&&!Te[String(Qb[c][kb.Ta])])return!0;return!1}function Bj(a,b){if(a){var c=""+a;0!==c.indexOf("http://")&&0!==c.indexOf("https://")&&(c="https://"+c);"/"===c[c.length-1]&&(c=c.substring(0,c.length-1));return re(""+c+b).href}}function Cj(a,b){return Dj()?Bj(a,b):void 0}function Dj(){var a=!1;return a};var Ej=function(){this.eventModel={};this.targetConfig={};this.containerConfig={};this.remoteConfig={};this.globalConfig={};this.onSuccess=function(){};this.onFailure=function(){};this.setContainerTypeLoaded=function(){};this.getContainerTypeLoaded=function(){};this.eventId=void 0;this.isGtmEvent=!1},Fj=function(a){var b=new Ej;b.eventModel=a;return b},Gj=function(a,b){a.targetConfig=b;return a},Hj=function(a,b){a.containerConfig=b;return a},Ij=function(a,b){a.remoteConfig=b;return a},Jj=function(a,
b){a.globalConfig=b;return a},Kj=function(a,b){a.onSuccess=b;return a},Lj=function(a,b){a.setContainerTypeLoaded=b;return a},Mj=function(a,b){a.getContainerTypeLoaded=b;return a},Nj=function(a,b){a.onFailure=b;return a};
Ej.prototype.getWithConfig=function(a){if(void 0!==this.eventModel[a])return this.eventModel[a];if(void 0!==this.targetConfig[a])return this.targetConfig[a];if(void 0!==this.containerConfig[a])return this.containerConfig[a];if(void 0!==this.remoteConfig[a])return this.remoteConfig[a];if(void 0!==this.globalConfig[a])return this.globalConfig[a]};
var Oj=function(a){function b(e){Ia(e,function(f){c[f]=null})}var c={};b(a.eventModel);b(a.targetConfig);b(a.containerConfig);b(a.globalConfig);var d=[];Ia(c,function(e){d.push(e)});return d};var Pj;if(3===Qe.xc.length)Pj="g";else{var Qj="G";Pj=Qj}
var Rj={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GF:"f",HA:"h",GTM:Pj,OPT:"o"},Sj=function(a){var b=Qe.K.split("-"),c=b[0].toUpperCase(),d=Rj[c]||"i",e=a&&"GTM"===c?b[1]:"OPT"===c?b[1]:"",f;if(3===Qe.xc.length){var h="w";f="2"+h}else f="";return f+d+Qe.xc+e};var Tj=function(){};var Uj=function(a){void 0!==a.addtlConsent&&"string"!==typeof a.addtlConsent&&(a.addtlConsent=void 0);void 0!==a.gdprApplies&&"boolean"!==typeof a.gdprApplies&&(a.gdprApplies=void 0);return void 0!==a.tcString&&"string"!==typeof a.tcString||void 0!==a.listenerId&&"number"!==typeof a.listenerId?2:a.cmpStatus&&"error"!==a.cmpStatus?0:3},Vj=function(a,b){this.o=a;this.m=null;this.H={};this.da=0;this.X=void 0===b?500:b;this.C=null};na(Vj,Tj);
var Xj=function(a){return"function"===typeof a.o.__tcfapi||null!=Wj(a)};
Vj.prototype.addEventListener=function(a){var b={},c=Gc(function(){return a(b)}),d=0;-1!==this.X&&(d=setTimeout(function(){b.tcString="tcunavailable";b.internalErrorState=1;c()},this.X));var e=function(f,h){clearTimeout(d);f?(b=f,b.internalErrorState=Uj(b),h&&0===b.internalErrorState||(b.tcString="tcunavailable",h||(b.internalErrorState=3))):(b.tcString="tcunavailable",b.internalErrorState=3);a(b)};try{Yj(this,"addEventListener",e)}catch(f){b.tcString="tcunavailable",b.internalErrorState=3,d&&(clearTimeout(d),
d=0),c()}};Vj.prototype.removeEventListener=function(a){a&&a.listenerId&&Yj(this,"removeEventListener",null,a.listenerId)};
var ak=function(a,b,c){var d;d=void 0===d?"755":d;var e;a:{if(a.publisher&&a.publisher.restrictions){var f=a.publisher.restrictions[b];if(void 0!==f){e=f[void 0===d?"755":d];break a}}e=void 0}var h=e;if(0===h)return!1;var k=c;2===c?(k=0,2===h&&(k=1)):3===c&&(k=1,1===h&&(k=0));var l;if(0===k)if(a.purpose&&a.vendor){var n=Zj(a.vendor.consents,void 0===d?"755":d);l=n&&"1"===b&&a.purposeOneTreatment&&("DE"===a.publisherCC||zd(Dc)&&"CH"===a.publisherCC)?!0:n&&Zj(a.purpose.consents,b)}else l=!0;else l=
1===k?a.purpose&&a.vendor?Zj(a.purpose.legitimateInterests,b)&&Zj(a.vendor.legitimateInterests,void 0===d?"755":d):!0:!0;return l},Zj=function(a,b){return!(!a||!a[b])},Yj=function(a,b,c,d){c||(c=function(){});if("function"===typeof a.o.__tcfapi){var e=a.o.__tcfapi;e(b,2,c,d)}else if(Wj(a)){bk(a);var f=++a.da;a.H[f]=c;if(a.m){var h={};a.m.postMessage((h.__tcfapiCall={command:b,version:2,callId:f,parameter:d},h),"*")}}else c({},!1)},Wj=function(a){if(a.m)return a.m;a.m=Wf(a.o,"__tcfapiLocator");return a.m},
bk=function(a){a.C||(a.C=function(b){try{var c;c=("string"===typeof b.data?JSON.parse(b.data):b.data).__tcfapiReturn;a.H[c.callId](c.returnValue,c.success)}catch(d){}},Sf(a.o,a.C))};var ck=!0;ck=!1;var dk={1:0,3:0,4:0,7:3,9:3,10:3};function ek(a,b){if(""===a)return b;var c=Number(a);return isNaN(c)?b:c}var fk=ek("",550),gk=ek("",500);function hk(){var a=O.tcf||{};return O.tcf=a}
var ik=function(a,b){this.C=a;this.m=b;this.o=Qa();},jk=function(a){},kk=function(a){},qk=function(){var a=hk(),b=new Vj(G,ck?3E3:-1),c=new ik(b,a);if((lk()?!0===G.gtag_enable_tcf_support:!1!==G.gtag_enable_tcf_support)&&!a.active&&("function"===typeof G.__tcfapi||Xj(b))){a.active=!0;a.Tb={};mk();var d=null;ck?d=G.setTimeout(function(){nk(a);ok(a);d=null},gk):a.tcString="tcunavailable";try{b.addEventListener(function(e){d&&(clearTimeout(d),d=null);if(0!==e.internalErrorState)nk(a),ok(a),jk(c);
else{var f;a.gdprApplies=e.gdprApplies;if(!1===e.gdprApplies)f=pk(),b.removeEventListener(e);else if("tcloaded"===e.eventStatus||"useractioncomplete"===e.eventStatus||"cmpuishown"===e.eventStatus){var h={},k;for(k in dk)if(dk.hasOwnProperty(k))if("1"===k){var l,n=e,p=!0;p=void 0===p?!1:p;var q;var r=n;!1===r.gdprApplies?q=!0:(void 0===r.internalErrorState&&(r.internalErrorState=Uj(r)),q="error"===r.cmpStatus||0!==r.internalErrorState||"loaded"===r.cmpStatus&&("tcloaded"===r.eventStatus||"useractioncomplete"===
r.eventStatus)?!0:!1);l=q?!1===n.gdprApplies||"tcunavailable"===n.tcString||void 0===n.gdprApplies&&!p||"string"!==typeof n.tcString||!n.tcString.length?!0:ak(n,"1",0):!1;h["1"]=l}else h[k]=ak(e,k,dk[k]);f=h}f&&(a.tcString=e.tcString||"tcempty",a.Tb=f,ok(a),jk(c))}}),kk(c)}catch(e){d&&(clearTimeout(d),d=null),nk(a),ok(a)}}};function nk(a){a.type="e";a.tcString="tcunavailable";ck&&(a.Tb=pk())}function mk(){var a={},b=(a.ad_storage="denied",a.wait_for_update=fk,a);Rd(b)}
var lk=function(){var a=!1;a=!0;return a};function pk(){var a={},b;for(b in dk)dk.hasOwnProperty(b)&&(a[b]=!0);return a}function ok(a){var b={},c=(b.ad_storage=a.Tb["1"]?"granted":"denied",b);rk();Sd(c,0)}
var sk=function(){var a=hk();if(a.active&&void 0!==a.loadTime)return Number(a.loadTime)},rk=function(){var a=hk();return a.active?a.tcString||"":""},tk=function(){var a=hk();return a.active&&void 0!==a.gdprApplies?a.gdprApplies?"1":"0":""},uk=function(a){if(!dk.hasOwnProperty(String(a)))return!0;var b=hk();return b.active&&b.Tb?!!b.Tb[String(a)]:!0};var vk=!1;function wk(a){var b=String(G.location).split(/[?#]/)[0],c=Qe.Vf||G._CONSENT_MODE_SALT;return a?c?String(vf(b+a+c)):"0":""}
function xk(a){function b(u){var v;O.reported_gclid||(O.reported_gclid={});v=O.reported_gclid;var x;x=vk&&h&&(!Kd()||N(E.B))?l+"."+(f.prefix||"_gcl")+(u?"gcu":"gcs"):l+(u?"gcu":"gcs");if(!v[x]){v[x]=!0;var z=[],w={},y=function(P,R){R&&(z.push(P+"="+encodeURIComponent(R)),w[P]=!0)},A="https://www.google.com";if(Kd()){var C=N(E.B);y("gcs",Td());u&&y("gcu","1");Ld()&&y("gcd","G1"+Pd(Id));O.dedupe_gclid||
(O.dedupe_gclid=""+Xf());y("rnd",O.dedupe_gclid);if((!l||n&&"aw.ds"!==n)&&N(E.B)){var F=Vg("_gcl_aw");y("gclaw",F.join("."))}y("url",String(G.location).split(/[?#]/)[0]);y("dclid",yk(d,p));var D=!1;D=!0;C||!d&&!D||(A="https://pagead2.googlesyndication.com")}
y("gdpr_consent",rk()),y("gdpr",tk());"1"===Fg(!1)._up&&y("gtm_up","1");y("gclid",yk(d,l));y("gclsrc",n);if(!(w.gclid||w.dclid||w.gclaw)&&(y("gbraid",yk(d,q)),!w.gbraid&&Kd()&&N(E.B))){var H=Vg("_gcl_gb");y("gclgb",H.join("."))}y("gtm",Sj(!e));vk&&h&&N(E.B)&&(hg(f||{}),y("auid",dg[eg(f.prefix)]||""));
a.rf&&y("did",a.rf);var M=A+"/pagead/landing?"+z.join("&");wd(M)}}var c=!!a.yd,d=!!a.wa,e=a.T,f=void 0===a.Dc?{}:a.Dc,h=void 0===a.Jc?!0:a.Jc,k=ah(),l=k.gclid||"",n=k.gclsrc,p=k.dclid||"",q=k.gbraid||"",r=!c&&((!l||n&&"aw.ds"!==n?!1:!0)||q),t=Kd();if(r||t)t?Vd(function(){b();N(E.B)||Ud(function(u){return b(!0,u.pf)},E.B)},[E.B]):b()}function yk(a,b){var c=a&&!N(E.B);return b&&c?"0":b}var kl=function(){var a=!0;uk(7)&&uk(9)&&uk(10)||(a=!1);var b=!0;b=!1;b&&!jl()&&(a=!1);return a},jl=function(){var a=!0;uk(3)&&uk(4)||(a=!1);return a};var Il=!1;function Jl(){var a=O;return a.gcq=a.gcq||new Kl}
var Ll=function(a,b,c){Jl().register(a,b,c)},Ml=function(a,b,c,d){Jl().push("event",[b,a],c,d)},Nl=function(a,b){Jl().push("config",[a],b)},Ol=function(a,b,c,d){Jl().push("get",[a,b],c,d)},Pl={},Ql=function(){this.status=1;this.containerConfig={};this.targetConfig={};this.remoteConfig={};this.o=null;this.m=!1},Rl=function(a,b,c,d,e){this.type=a;this.C=b;this.T=c||"";this.m=d;this.o=e},Kl=function(){this.H={};this.o={};this.m=[];this.C={AW:!1,UA:!1};this.enableDeferrableCommandAfterConfig=Il},Sl=function(a,
b){var c=zh(b);return a.H[c.containerId]=a.H[c.containerId]||new Ql},Tl=function(a,b,c){if(b){var d=zh(b);if(d&&1===Sl(a,b).status){Sl(a,b).status=2;var e={};hj&&(e.timeoutId=G.setTimeout(function(){Bc(38);Ti()},3E3));a.push("require",[e],d.containerId);Pl[d.containerId]=Qa();if(Ch()){}else{var h="/gtag/js?id="+encodeURIComponent(d.containerId)+"&l=dataLayer&cx=c",k=("http:"!=G.location.protocol?"https:":"http:")+("//www.googletagmanager.com"+h),l=Cj(c,h)||k;jd(l)}}}},Ul=function(a,b,c,d){if(d.T){var e=Sl(a,d.T),f=e.o;if(f){var h=B(c),k=B(e.targetConfig[d.T]),l=B(e.containerConfig),n=B(e.remoteConfig),p=B(a.o),q=jf("gtm.uniqueEventId"),r=zh(d.T).prefix,t=Mj(Lj(Nj(Kj(Jj(Ij(Hj(Gj(Fj(h),k),l),n),p),function(){
jj(q,r,"2");}),function(){jj(q,r,"3");}),function(u,v){a.C[u]=v}),function(u){return a.C[u]});try{jj(q,r,"1");f(d.T,b,d.C,t)}catch(u){jj(q,r,"4");}}}};g=Kl.prototype;
g.register=function(a,b,c){var d=Sl(this,a);if(3!==d.status){d.o=b;d.status=3;if(c){B(d.remoteConfig,c);d.remoteConfig=c}var e=zh(a),f=Pl[e.containerId];if(void 0!==f){var h=O[e.containerId].bootstrap,k=e.prefix.toUpperCase();O[e.containerId]._spx&&(k=k.toLowerCase());var l=jf("gtm.uniqueEventId"),n=k,p=Qa()-h;if(hj&&!Yi[l]){l!==Ui&&(Qi(),Ui=l);var q=n+"."+Math.floor(h-f)+
"."+Math.floor(p);bj=bj?bj+","+q:"&cl="+q}delete Pl[e.containerId]}this.flush()}};g.push=function(a,b,c,d){var e=Math.floor(Qa()/1E3);Tl(this,c,b[0][E.Ba]||this.o[E.Ba]);Il&&c&&Sl(this,c).m&&(d=!1);this.m.push(new Rl(a,e,c,b,d));d||this.flush()};g.insert=function(a,b,c){var d=Math.floor(Qa()/1E3);0<this.m.length?this.m.splice(1,0,new Rl(a,d,c,b,!1)):this.m.push(new Rl(a,d,c,b,!1))};
g.flush=function(a){for(var b=this,c=[],d=!1,e={};this.m.length;){var f=this.m[0];if(f.o)Il?!f.T||Sl(this,f.T).m?(f.o=!1,this.m.push(f)):c.push(f):(f.o=!1,this.m.push(f));else switch(f.type){case "require":if(3!==Sl(this,f.T).status&&!a){Il&&this.m.push.apply(this.m,c);return}hj&&G.clearTimeout(f.m[0].timeoutId);break;case "set":Ia(f.m[0],function(r,t){B(ab(r,t),b.o)});break;case "config":e.xa={};Ia(f.m[0],function(r){return function(t,u){B(ab(t,u),r.xa)}}(e));var h=!!e.xa[E.qc];delete e.xa[E.qc];
var k=Sl(this,f.T),l=zh(f.T),n=l.containerId===l.id;h||(n?k.containerConfig={}:k.targetConfig[f.T]={});k.m&&h||Ul(this,E.fa,e.xa,f);k.m=!0;delete e.xa[E.Hb];n?B(e.xa,k.containerConfig):B(e.xa,k.targetConfig[f.T]);Il&&(d=!0);break;case "event":e.Xb={};Ia(f.m[0],function(r){return function(t,u){B(ab(t,u),r.Xb)}}(e));Ul(this,f.m[1],e.Xb,f);break;case "get":var p={},q=(p[E.Ka]=f.m[0],p[E.Ja]=f.m[1],p);Ul(this,E.za,q,f)}this.m.shift();e={xa:e.xa,Xb:e.Xb}}Il&&(this.m.push.apply(this.m,c),d&&this.flush())};
g.getRemoteConfig=function(a){return Sl(this,a).remoteConfig};var Vl=function(a,b,c){var d={event:b,"gtm.element":a,"gtm.elementClasses":xd(a,"className"),"gtm.elementId":a["for"]||sd(a,"id")||"","gtm.elementTarget":a.formTarget||xd(a,"target")||""};c&&(d["gtm.triggers"]=c.join(","));d["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||xd(a,"href")||a.src||a.code||a.codebase||"";return d},Wl=function(a){O.hasOwnProperty("autoEventsSettings")||(O.autoEventsSettings={});var b=O.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});
return b[a]},Xl=function(a,b,c){Wl(a)[b]=c},Yl=function(a,b,c,d){var e=Wl(a),f=Ua(e,b,d);e[b]=c(f)},Zl=function(a,b,c){var d=Wl(a);return Ua(d,b,c)};var $l=!!G.MutationObserver,am=void 0,bm=function(a){if(!am){var b=function(){var c=I.body;if(c)if($l)(new MutationObserver(function(){for(var e=0;e<am.length;e++)J(am[e])})).observe(c,{childList:!0,subtree:!0});else{var d=!1;nd(c,"DOMNodeInserted",function(){d||(d=!0,J(function(){d=!1;for(var e=0;e<am.length;e++)J(am[e])}))})}};am=[];I.body?b():J(b)}am.push(a)};var dm=!1,em=[];function fm(){if(!dm){dm=!0;for(var a=0;a<em.length;a++)J(em[a])}}var gm=function(a){dm?J(a):em.push(a)};Object.freeze({dl:1,id:1});var hm="HA GF G UA AW DC".split(" "),im=!1,jm={},km=!1;function lm(a,b){var c={event:a};b&&(c.eventModel=B(b),b[E.$c]&&(c.eventCallback=b[E.$c]),b[E.ic]&&(c.eventTimeout=b[E.ic]));return c}function mm(a){a.hasOwnProperty("gtm.uniqueEventId")||Object.defineProperty(a,"gtm.uniqueEventId",{value:cf()});return a["gtm.uniqueEventId"]}
function nm(){return im}
var qm={config:function(a){var b,c;void 0===c&&(c=cf());return b},consent:function(a){function b(){nm()&&B(a[2],{subcommand:a[1]})}if(3===a.length){Bc(39);var c=cf(),d=a[1];"default"===d?(b(),Rd(a[2])):"update"===d&&(b(),Sd(a[2],c))}},event:function(a){var b=a[1];if(!(2>a.length)&&m(b)){var c;if(2<a.length){if(!ib(a[2])&&
void 0!=a[2]||3<a.length)return;c=a[2]}var d=lm(b,c),e=void 0;void 0===e&&cf();return d}},get:function(a){},js:function(a){if(2==a.length&&a[1].getTime){km=!0;nm();var b={event:"gtm.js","gtm.start":a[1].getTime()};return b}},policy:function(){},set:function(a){var b;2==a.length&&ib(a[1])?b=B(a[1]):3==a.length&&
m(a[1])&&(b={},ib(a[2])||wa(a[2])?b[a[1]]=B(a[2]):b[a[1]]=a[2]);if(b){b._clear=!0;return b}}},rm={policy:!0};var sm=function(a,b){var c=a.hide;if(c&&void 0!==c[b]&&c.end){c[b]=!1;var d=!0,e;for(e in c)if(c.hasOwnProperty(e)&&!0===c[e]){d=!1;break}d&&(c.end(),c.end=null)}},um=function(a){var b=tm(),c=b&&b.hide;c&&c.end&&(c[a]=!0)};var Nm=function(a){if(Mm(a))return a;this.m=a};Nm.prototype.ph=function(){return this.m};var Mm=function(a){return!a||"object"!==fb(a)||ib(a)?!1:"getUntrustedUpdateValue"in a};Nm.prototype.getUntrustedUpdateValue=Nm.prototype.ph;var Om=[],Pm=!1,Qm=!1,Rm=!1,Sm=function(a){return G["dataLayer"].push(a)},Tm=function(a){var b=O["dataLayer"],c=b?b.subscribers:1,d=0,e=a;return function(){++d===c&&(e(),e=null)}};
function Um(a){var b=a._clear;Ia(a,function(d,e){"_clear"!==d&&(b&&mf(d,void 0),mf(d,e))});Ye||(Ye=a["gtm.start"]);var c=a["gtm.uniqueEventId"];if(!a.event)return!1;c||(c=cf(),a["gtm.uniqueEventId"]=c,mf("gtm.uniqueEventId",c));return Aj(a)}function Vm(){var a=Om[0];if(null==a||"object"!==typeof a)return!1;if(a.event)return!0;if(Ka(a)){var b=a[0];if("config"===b||"event"===b||"js"===b)return!0}return!1}
function Wm(){for(var a=!1;!Rm&&0<Om.length;){var b=!1;if(b&&!Qm&&Vm()){var c={};Om.unshift((c.event=
"gtm.init",c));Qm=!0}var d=!1;if(d&&!Pm&&Vm()){var e={};Om.unshift((e.event="gtm.init_consent",e));Pm=!0}Rm=!0;delete ff.eventModel;hf();var f=Om.shift();if(null!=f){var h=Mm(f);
if(h){var k=f;f=Mm(k)?k.getUntrustedUpdateValue():void 0;for(var l=["gtm.allowlist","gtm.blocklist","gtm.whitelist","gtm.blacklist","tagTypeBlacklist"],n=0;n<l.length;n++){var p=l[n],q=jf(p,1);if(wa(q)||ib(q))q=B(q);gf[p]=q}}try{if(ua(f))try{f.call(kf)}catch(y){}else if(wa(f)){var r=f;if(m(r[0])){var t=r[0].split("."),u=t.pop(),v=r.slice(1),x=jf(t.join("."),2);if(void 0!==x&&null!==x)try{x[u].apply(x,v)}catch(y){}}}else{if(Ka(f)){a:{var z=f;if(z.length&&m(z[0])){var w=qm[z[0]];if(w&&(!h||!rm[z[0]])){f=
w(z);break a}}f=void 0}if(!f){Rm=!1;continue}}a=Um(f)||a}}finally{h&&hf(!0)}}Rm=!1}return!a}function Xm(){var a=Wm();try{sm(G["dataLayer"],Qe.K)}catch(b){}return a}
var Zm=function(){var a=hd("dataLayer",[]),b=hd("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};li(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});gm(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});b.subscribers=(b.subscribers||0)+1;var c=a.push;a.push=function(){var e;if(0<O.SANDBOXED_JS_SEMAPHORE){e=[];for(var f=0;f<arguments.length;f++)e[f]=new Nm(arguments[f])}else e=[].slice.call(arguments,0);var h=c.apply(a,e);Om.push.apply(Om,e);if(300<
this.length)for(Bc(4);300<this.length;)this.shift();var k="boolean"!==typeof h||h;return Wm()&&k};var d=a.slice(0);Om.push.apply(Om,d);Ym()&&J(Xm)},Ym=function(){var a=!0;return a};var $m={};$m.sc=new String("undefined");
var an=function(a){this.m=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===$m.sc?b:a[d]);return c.join("")}};an.prototype.toString=function(){return this.m("undefined")};an.prototype.valueOf=an.prototype.toString;$m.Og=an;$m.ud={};$m.bh=function(a){return new an(a)};var bn={};$m.Oh=function(a,b){var c=cf();bn[c]=[a,b];return c};$m.qf=function(a){var b=a?0:1;return function(c){var d=bn[c];if(d&&"function"===typeof d[b])d[b]();bn[c]=void 0}};$m.uh=function(a){for(var b=!1,c=!1,d=2;d<a.length;d++)b=
b||8===a[d],c=c||16===a[d];return b&&c};$m.Ih=function(a){if(a===$m.sc)return a;var b=cf();$m.ud[b]=a;return'google_tag_manager["'+Qe.K+'"].macro('+b+")"};$m.Eh=function(a,b,c){a instanceof $m.Og&&(a=a.m($m.Oh(b,c)),b=ta);return{qh:a,onSuccess:b}};var cn=["input","select","textarea"],dn=["button","hidden","image","reset","submit"],en=function(a){var b=a.tagName.toLowerCase();return!Da(cn,function(c){return c===b})||"input"===b&&Da(dn,function(c){return c===a.type.toLowerCase()})?!1:!0},fn=function(a){return a.form?a.form.tagName?a.form:I.getElementById(a.form):vd(a,["form"],100)},gn=function(a,b,c){if(!a.elements)return 0;for(var d=b.getAttribute(c),e=0,f=1;e<a.elements.length;e++){var h=a.elements[e];if(en(h)){if(h.getAttribute(c)===d)return f;
f++}}return 0};var sn=G.clearTimeout,tn=G.setTimeout,V=function(a,b,c){if(Ch()){b&&J(b)}else return jd(a,b,c)},un=function(){return new Date},vn=function(){return G.location.href},wn=function(a){return ne(re(a),"fragment")},xn=function(a){return qe(re(a))},yn=function(a,b){return jf(a,b||2)},zn=function(a,b,c){var d;b?(a.eventCallback=b,c&&(a.eventTimeout=c),d=Sm(a)):d=Sm(a);return d},An=function(a,b){G[a]=b},X=function(a,b,c){b&&
(void 0===G[a]||c&&!G[a])&&(G[a]=b);return G[a]},Bn=function(a,b,c){return Af(a,b,void 0===c?!0:!!c)},Cn=function(a,b,c){return 0===Jf(a,b,c)},Dn=function(a,b){if(Ch()){b&&J(b)}else ld(a,b)},En=function(a){return!!Zl(a,"init",!1)},Fn=function(a){Xl(a,"init",!0)},Gn=function(a){var b=We+"?id="+encodeURIComponent(a)+"&l=dataLayer";V(Eh("https://","http://",b))},Hn=function(a,b,c){hj&&(jb(a)||kj(c,b,a))};var In=$m.Eh;function fo(a,b){a=String(a);b=String(b);var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var go=new Ga;function ho(a,b,c){var d=c?"i":void 0;try{var e=String(b)+d,f=go.get(e);f||(f=new RegExp(b,d),go.set(e,f));return f.test(a)}catch(h){return!1}}
function io(a,b){function c(h){var k=re(h),l=ne(k,"protocol"),n=ne(k,"host",!0),p=ne(k,"port"),q=ne(k,"path").toLowerCase().replace(/\/$/,"");if(void 0===l||"http"==l&&"80"==p||"https"==l&&"443"==p)l="web",p="default";return[l,n,p,q]}for(var d=c(String(a)),e=c(String(b)),f=0;f<d.length;f++)if(d[f]!==e[f])return!1;return!0}
function jo(a){return ko(a)?1:0}
function ko(a){var b=a.arg0,c=a.arg1;if(a.any_of&&wa(c)){for(var d=0;d<c.length;d++){var e=B(a,{});B({arg1:c[d],any_of:void 0},e);if(jo(e))return!0}return!1}switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_css":var f;a:{if(b){var h=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var k=0;k<h.length;k++)if(b[h[k]]){f=b[h[k]](c);break a}}catch(n){}}f=!1}return f;case "_ew":return fo(b,c);case "_eq":return String(b)==
String(c);case "_ge":return Number(b)>=Number(c);case "_gt":return Number(b)>Number(c);case "_lc":var l;l=String(b).split(",");return 0<=Ba(l,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":return ho(b,c,a.ignore_case);case "_sw":return 0==String(b).indexOf(String(c));case "_um":return io(b,c)}return!1};var lo=encodeURI,Y=encodeURIComponent,mo=md;var no=function(a,b){if(!a)return!1;var c=ne(re(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var oo=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};function Wp(){return G.gaGlobal=G.gaGlobal||{}}var Xp=function(){var a=Wp();a.hid=a.hid||Ea();return a.hid},Yp=function(a,b){var c=Wp();if(void 0==c.vid||b&&!c.from_cookie)c.vid=a,c.from_cookie=b};var uq=function(){if(ua(G.__uspapi)){var a="";try{G.__uspapi("getUSPData",1,function(b,c){if(c&&b){var d=b.uspString;d&&/^[\da-zA-Z-]{1,20}$/.test(d)&&(a=d)}})}catch(b){}return a}};var Oq=window,Pq=document,Qq=function(a){var b=Oq._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===Oq["ga-disable-"+a])return!0;try{var c=Oq.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(f){}for(var d=wf("AMP_TOKEN",String(Pq.cookie),!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return Pq.getElementById("__gaOptOutExtension")?!0:!1};var Rq={};function Uq(a){delete a.eventModel[E.Hb];Wq(a.eventModel)}var Wq=function(a){Ia(a,function(c){"_"===c.charAt(0)&&delete a[c]});var b=a[E.Ca]||{};Ia(b,function(c){"_"===c.charAt(0)&&delete b[c]})};var Zq=function(a,b,c){Ml(b,c,a)},$q=function(a,b,c){Ml(b,c,a,!0)},gr=function(a,b){};
function ar(a,b){}var Z={g:{}};
Z.g.gaawc=["google"],function(){function a(b,c,d){for(var e=0;e<c.length;e++)b.hasOwnProperty(c[e])&&(b[c[e]]=d(b[c[e]]))}(function(b){Z.__gaawc=b;Z.__gaawc.h="gaawc";Z.__gaawc.i=!0;Z.__gaawc.priorityOverride=10})(function(b){var c=String(b.vtp_measurementId),d=oo(b.vtp_fieldsToSet,"name","value")||{};if(d.hasOwnProperty(E.Ca)||b.vtp_userProperties){var e=d[E.Ca]||{};B(oo(b.vtp_userProperties,"name","value"),e);d[E.Ca]=e}b.vtp_enableSendToServerContainer&&b.vtp_transportUrl&&(d[E.Ba]=b.vtp_transportUrl,
d[E.Cb]=!0);a(d,E.Pe,function(f){return Ma(f)});a(d,E.Re,function(f){return Number(f)});d.send_page_view=b.vtp_sendPageView;Nl(d,c);J(b.vtp_gtmOnSuccess)})}();


Z.g.e=["google"],function(){(function(a){Z.__e=a;Z.__e.h="e";Z.__e.i=!0;Z.__e.priorityOverride=0})(function(a){var b=String(pf(a.vtp_gtmEventId,"event"));return b})}();

Z.g.v=["google"],function(){(function(a){Z.__v=a;Z.__v.h="v";Z.__v.i=!0;Z.__v.priorityOverride=0})(function(a){var b=a.vtp_name;if(!b||!b.replace)return!1;var c=yn(b.replace(/\\\./g,"."),a.vtp_dataLayerVersion||1),d=void 0!==c?c:a.vtp_defaultValue;Hn(d,"v",a.vtp_gtmEventId);return d})}();









Z.g.gas=["google"],function(){(function(a){Z.__gas=a;Z.__gas.h="gas";Z.__gas.i=!0;Z.__gas.priorityOverride=0})(function(a){var b=B(a),c=b;c[kb.Ta]=null;c[kb.Fg]=null;var d=b=c;d.vtp_fieldsToSet=d.vtp_fieldsToSet||[];var e=d.vtp_cookieDomain;void 0!==e&&(d.vtp_fieldsToSet.push({fieldName:"cookieDomain",value:e}),delete d.vtp_cookieDomain);return b})}();






Z.g.dbg=["google"],function(){(function(a){Z.__dbg=a;Z.__dbg.h="dbg";Z.__dbg.i=!0;Z.__dbg.priorityOverride=0})(function(){return!1})}();






var hr={};hr.macro=function(a){if($m.ud.hasOwnProperty(a))return $m.ud[a]},hr.onHtmlSuccess=$m.qf(!0),hr.onHtmlFailure=$m.qf(!1);hr.dataLayer=kf;hr.callback=function(a){af.hasOwnProperty(a)&&ua(af[a])&&af[a]();delete af[a]};hr.bootstrap=0;hr._spx=!1;function ir(){O[Qe.K]=hr;Xa(bf,Z.g);Ub=Ub||$m;Vb=cc}
function jr(){yd.o().o();O=G.google_tag_manager=G.google_tag_manager||{};qk();Og.enable_gbraid_cookie_write=!0;if(O[Qe.K]){var a=O.zones;a&&a.unregisterChild(Qe.K);}else{for(var b=data.resource||{},c=b.macros||[],d=0;d<c.length;d++)Nb.push(c[d]);for(var e=b.tags||[],f=0;f<e.length;f++)Qb.push(e[f]);for(var h=b.predicates||[],k=0;k<h.length;k++)Pb.push(h[k]);for(var l=b.rules||[],n=0;n<l.length;n++){for(var p=l[n],q={},r=0;r<p.length;r++)q[p[r][0]]=Array.prototype.slice.call(p[r],1);Ob.push(q)}Sb=Z;Tb=jo;ir();Zm();gi=!1;hi=0;if("interactive"==I.readyState&&!I.createEventObject||"complete"==I.readyState)ji();
else{nd(I,"DOMContentLoaded",ji);nd(I,"readystatechange",ji);if(I.createEventObject&&I.documentElement.doScroll){var t=!0;try{t=!G.frameElement}catch(z){}t&&ki()}nd(G,"load",ji)}dm=!1;"complete"===I.readyState?fm():nd(G,"load",fm);a:{if(!hj)break a;G.setInterval(gj,
864E5);}Ze=(new Date).getTime();}}
(function(a){if(!G["__TAGGY_INSTALLED"]){var b=!1;if(I.referrer){var c=re(I.referrer);b="cct.google"===me(c,"host")}if(!b){var d=Af("googTaggyReferrer");b=d.length&&d[0].length}b&&(G["__TAGGY_INSTALLED"]=!0,jd("https://cct.google/taggy/agent.js"))}var f=function(){var n=G["google.tagmanager.debugui2.queue"];n||(n=[],G["google.tagmanager.debugui2.queue"]=n,jd("https://www.googletagmanager.com/debug/bootstrap"));var p={messageType:"CONTAINER_STARTING",data:{scriptSource:gd,containerProduct:"GTM",debug:!1}};p.data.resume=function(){a()};Qe.Uf&&(p.data.initialPublish=!0);n.push(p)},h="x"===ne(G.location,"query",!1,void 0,"gtm_debug");if(!h&&I.referrer){var k=re(I.referrer);h="tagassistant.google.com"===me(k,"host")}if(!h){var l=Af("__TAG_ASSISTANT");h=l.length&&l[0].length}G.__TAG_ASSISTANT_API&&(h=!0);h&&gd?f():a()})(jr);

})()
