var desc = []   // unicode v11

desc[2304]="= vaidika adhomukha candrabindu"
desc[2305]="= anunasika¶→ (combining candrabindu - 0310)"
desc[2306]="= bindu"
desc[2308]="• used for short e in Awadhi¶• also used in Devanagari transliterations of some South Indian and Kashmiri languages by a publisher in Lucknow"
desc[2318]="• Kashmiri, Bihari languages¶• also used for transcribing Dravidian short e"
desc[2322]="• Kashmiri, Bihari languages¶• also used for transcribing Dravidian short o"
desc[2345]="• for transcribing Dravidian alveolar n¶≡ 0928 093C"
desc[2353]="• for transcribing Dravidian alveolar r¶• half form is represented as 'Eyelash RA'¶≡ 0930 093C"
desc[2356]="• for transcribing Dravidian l¶≡ 0933 093C"
desc[2364]="• for extending the alphabet to new letters"
desc[2367]="• stands to the left of the consonant"
desc[2373]="= candra"
desc[2374]="• Kashmiri, Bihari languages¶• also used for transcribing Dravidian short e"
desc[2378]="• Kashmiri, Bihari languages¶• also used for transcribing Dravidian short o"
desc[2381]="= halant (the preferred Hindi name)¶• suppresses inherent vowel"
desc[2382]="• character has historic use only¶• combines with E to form AI, with AA to form O, and with O to form AU"
desc[2383]="• Kashmiri, Bihari languages"
desc[2384]="→ (om symbol - 1F549)"
desc[2385]="= Vedic tone svarita¶• mostly used for svarita, with rare use for udatta¶• used also in Vedic texts written in other scripts¶→ (vedic tone double svarita - 1CDA)"
desc[2386]="= Vedic tone anudatta¶• used also in Vedic texts written in other scripts¶→ (vedic tone kathaka anudatta - 1CDC)"
desc[2387]="→ (combining grave accent - 0300)"
desc[2388]="→ (combining acute accent - 0301)"
desc[2389]="• used in transliteration of Avestan"
desc[2392]="≡ 0915 093C"
desc[2393]="≡ 0916 093C"
desc[2394]="≡ 0917 093C"
desc[2395]="≡ 091C 093C"
desc[2396]="≡ 0921 093C"
desc[2397]="≡ 0922 093C"
desc[2398]="≡ 092B 093C"
desc[2399]="≡ 092F 093C"
desc[2404]="= purna viram¶• phrase separator"
desc[2405]="= deergh viram"
desc[2406]="• also used to represent an anusvara following digits indicating secondary svara-s in Samavedic texts"
desc[2416]="• intended for Devanagari-specific abbreviations"
desc[2425]="• used in transliteration of Avestan¶→ (gujarati letter zha - 0AF9)"
desc[2426]="• used for an affricated glide JJYA"
desc[2429]="• used for writing Limbu in Devanagari¶• a glyph variant has the connecting top bar"

desc[43232]="= vaidika saamasvara anka shuunya"
desc[43233]="= vaidika saamasvara anka eka udaatta"
desc[43234]="= vaidika saamasvara anka dvi svarita"
desc[43235]="= vaidika saamasvara anka tri anudaatta"
desc[43236]="= vaidika saamasvara anka chatur"
desc[43237]="= vaidika saamasvara anka pancha"
desc[43238]="= vaidika saamasvara anka shatt"
desc[43239]="= vaidika saamasvara anka sapta"
desc[43240]="= vaidika saamasvara anka ashta"
desc[43241]="= vaidika saamasvara anka nava"
desc[43242]="= vaidika saamasvara abhinihita"
desc[43243]="= vaidika saamasvara u"
desc[43244]="= vaidika saamasvara ka"
desc[43245]="= vaidika saamasvara namana"
desc[43246]="= vaidika saamasvara prannatam"
desc[43247]="= vaidika saamasvara ra"
desc[43248]="= vaidika saamasvara vinata"
desc[43249]="= vaidika saamasvara diirghiibhaava"
desc[43250]="= vaidika candrabindu¶→ (devanagari sign candrabindu - 0901)"
desc[43251]="= vaidika anusvaara candrabindu tiryak"
desc[43252]="= vaidika anusvaara dvi candrabindu tiryak"
desc[43253]="= vaidika anusvaara candrabindu sa-dvi"
desc[43254]="= vaidika anusvaara candrabindu sa-tri"
desc[43255]="= vaidika anusvaara candrabindu sa-avagraha"
desc[43256]="= vaidika pushpikaa¶• used as a placeholder or 'filler'¶• often flanked by double dandas"
desc[43257]="• used to indicate that a gap in a manuscript or text is not a lacuna"
desc[43258]="= vaidika trutikaa¶• zero-advance character centered on the point between two orthographic syllables¶• used for insertion of characters¶→ (caret - 2038)"
desc[43259]="= shirorekhaa¶• used to indicate uncertain manuscript readings¶→ (sharada headstroke - 111DC)"
desc[43260]="= siddhirastu¶• used at the beginning of texts as an invocation¶→ (kannada sign siddham - 0C84)¶→ (tibetan mark initial yig mgo mdun ma - 0F04)¶→ (mongolian birga - 1800)¶→ (sharada sign siddham - 111DB)"

