// if there is a * after a transcription it has been autogenerated and needs checking

autoExpandExamples.hi = `
अंडा|egg|ən.ɖɑː
इन्सान|mankind|ɪnsaːn
ईंट|brick|iːnʈ
उड़ना|to fly|ʊɽ.nɑː
ऊपर|above|uːpar
एक|one|eːk
एकोऽयम्|this one
ओस|dew|oːs
कह|say!|kəɦ
कहना|to say|kɛɦɛnaː
क़लम|pen|qələm
कुत्ता|dog|kʊt̪.t̪ɑː
कोड|code|koːd
ख़ारीदारी|shopping
ख़ून|blood|xuːn
खाना|to eat|kʰɑː.nɑː
गर्दन|neck|ɡəɾ.d̪ən
गाढ़ा|thick|ɡɑː.ɽʱɑː
घास|grass|ɡʱaːs
चार|four|t͡ʃɑːɾ
छः|six
छोटा|small|t͡ʃʰoː.ʈɑː
जानवर|animal|d͡ʒɑːn.ʋəɾ
झील|lake|d͡ʒʱiːl
टांग|knee|ʈɑːŋɡ
टांग|leg|ʈɑːŋɡ
टोपी|hat|ʈoːpiː
ठंडा|cold|ʈʰən.ɖɑː
तीन|three|t̪iːn
त्वचा|skin|t̪ʋə.t͡ʃɑː
थूकना|to spit|t̪ʰuːk.nɑː
दाँत|tooth|d̪ɑ̃ːt̪
दिन|day|dɪn
दुःख|grief
दो|two|d̪oː
धूल|dust|d̪ʱuːl
नई|new
नज़दीक|near|nəzdiːk
नया|new|nə.jɑː
नाक|nose|nɑːk
पंजाब|Punjab|pañjāb
पकवान|food dish|pəkwaːn
पानी|water|pɑː.niː
फल|fruit|pʰəl
फूल|flower|pʰuːl
बइठऽ|sit
बड़ा|big|bə.ɽɑː
बहुत|many|bəˈhʊt̪
बारिश|rain|bɑː.ɾɪʃ
बेटा|son|beʈɑː
भारी|heavy|bʱɑː.ɾiː
मछली|fish|mət͡ʃʰ.liː
माता-पिता|parents
मुँह|mouth
रुपया|rupee
लाभ-हानि|profit-loss
लाल|red|lɑːl
वस्तु|item|ʋəstu
व्रत|fast|ʋrʌt
व्रत|vow|vrət
शक्ति|energy|ʃəkti
सदाऽऽत्मा|always
सफ़ेद|white|sə.feːd̪
सुस्त|lazy|sʊst
सूरज|sun|suː.ɾəd͡ʒ
हड्डी|bone|ɦəɖ.ɖiː
हवा|wind|ɦə.ʋɑː
हिंदी|Hindi|hindiː
हैं|are|ɦɛ̃

`

