var desc = []   // unicode v11

desc[6030]="• as this character belongs to the first register, its correct transliteration is nna, not nno"
desc[6045]="• used only for Pali/Sanskrit transliteration"
desc[6046]="• used only for Pali/Sanskrit transliteration¶• as this character belongs to the first register, its correct transliteration is ssa, not sso"
desc[6050]="• glottal stop"
desc[6051]="• use of this character is strongly discouraged; 17A2 should be used instead"
desc[6052]="• use of this character is strongly discouraged; the sequence 17A2 17B6 should be used instead"
desc[6056]="• obsolete ligature for the sequence 17A7 1780¶• use of the sequence is now preferred"
desc[6066]="• this is a variant for 17B1, used in only two words¶• 17B1 is the normal variant of this vowel"
desc[6086]="= srak am¶= anusvara¶• final nasalization¶• this character is usually regarded as a vowel sign am, along with om and aam¶→ (thai character nikhahit - 0E4D)¶→ (myanmar sign anusvara - 1036)"
desc[6087]="= srak ah¶= visarga¶→ (myanmar sign visarga - 1038)"
desc[6088]="• inserts a short inherent vowel with abrupt glottal stop¶• the preferred transliteration is yukaleakpintu"
desc[6089]="• changes the second register to the first¶• the preferred transliteration is muusekatoan"
desc[6090]="• changes the first register to the second¶• the preferred transliteration is treisap"
desc[6091]="• shortens the vowel sound in the previous orthographic syllable¶• the preferred transliteration is bantak"
desc[6092]="• a diacritic historically corresponding to the repha form of ra in Devanagari"
desc[6093]="• indicates that the base character is not pronounced¶→ (thai character thanthakhat - 0E4C)"
desc[6094]="• sign used with some exclamations"
desc[6095]="• denotes stressed intonation in some single-consonant words"
desc[6096]="• denotes deviation from the general rules of pronunciation, mostly used in loan words from Pali/Sanskrit, French, and so on"
desc[6097]="• mostly obsolete, a 'killer'¶• indicates that the base character is the final consonant of a word without its inherent vowel sound"
desc[6098]="• functions to indicate that the following Khmer letter is to be rendered subscripted¶• shape shown is arbitrary and is not visibly rendered"
desc[6099]="• originally intended as part of lunar date symbols¶• use of this character is discouraged in favor of the complete set of lunar date symbols¶→ (khmer symbol pathamasat - 19E0)"
desc[6100]="• functions as a full stop, period¶→ (thai character paiyannoi - 0E2F)¶→ (myanmar sign little section - 104A)"
desc[6101]="• indicates the end of a section or a text¶→ (thai character angkhankhu - 0E5A)¶→ (myanmar sign section - 104B)"
desc[6102]="• functions as colon¶• the preferred transliteration is camnoc pii kuuh¶→ (division sign - 00F7)¶→ (tibetan mark gter tsheg - 0F14)"
desc[6103]="• repetition sign¶→ (thai character maiyamok - 0E46)"
desc[6104]="• et cetera¶• use of this character is discouraged; other abbreviations for et cetera also exist¶• preferred spelling: 17D4 179B 17D4"
desc[6105]="• indicates the beginning of a book or a treatise¶• the preferred transliteration is phnek moan¶→ (thai character fongman - 0E4F)"
desc[6106]="• indicates the end of a book or treatise¶• this forms a pair with 17D9¶• the preferred transliteration is koomoot¶→ (thai character khomut - 0E5B)"
desc[6108]="• rare, shows an omitted Sanskrit vowel, like an apostrophe¶• the preferred transliteration is avakraha sannya¶→ (devanagari sign avagraha - 093D)"
desc[6109]="• mostly obsolete¶• indicates that the base character is the final consonant of a word with its inherent vowel sound¶→ (khmer sign viriam - 17D1)"


desc[6624]="• represents the first Ashadha (eighth month of the lunar calendar)"
desc[6640]="• represents the second Ashadha in the lunar calendar during the Adhikameas leap year"
