// if there is a * after a transcription it has been autogenerated and needs checking

var examples = `
កន្ត្រៃ|scissors|kɑːntraj
ច្រៀង|singing|criəŋ
ប្រយ័ត្ន|to be careful|prɑjat
ដំ|to pound|ɗɑm
ដម|nectar|ɗɑːm
ពាំ|to carry in the beak|poə̆m
ពាម|mouth of a river|piəm
ឪពុក|father|ʔəwpuk
ឲ្យ|to give|jʔaoj
ឮ|to hear|lɨː
ពេទ្យ|medical|peit
រដ្ឋ|state|rɔat
កម្មករ|worker|kɑmmɔkɑː
កញ្ជ្រេង|fox|kɑɲcreːŋ
អង្គ្លេស|English|ʔɑŋkleːh
សងស្ក្រិត|Sanskrit|sɑŋskret
សាស្ត្រាចារ្យ|teacher|sɑstraːcaː
បរិបូណ៌|abundant|ɓɑriɓou
សប្ដាហ៍|week|sɑpɗaː
រេហ៍ពល|army|rɔpuə̆l
អាត្មន៑|soul|ʔaːtman
ក៏|also, therefore|kɑː
ដ៏|which, very|ɗɑː
ណែ៎|Hey!|nɛː
នុ៎ះន៎|Over there!|nuhnɔː
បញ្ឆោត|to trick|ɓɑɲcʰaot
កញ្ញា|young lady|kɑɲɲaa
ប្រាជ្ញា|intelligence|praːcɲaa
ខ្លាំង ៗ|very strong|klaŋklaŋ
បន្តិចម្ដង ៗ|little by little|ɓɑntecmɗɑːŋ ɓɑntecmɗɑːŋ
ជាតិ|national|ciəteʔ*
វិទ្យាល័យ|highschool|ʋiʔtjiəlɨj*
កម្ម|mission|kɑːm*
អន្តរជាតិ|international|ʔɑːntɑːciəteʔ*
ជាតិសាសន៍|race|ciəteʔsaːsɑː*
កម្មផល|karma|kɑːmmɔːpʰɑːl*
សកលវិទ្យាល័យ|university|sɑːkɑːlɔːʋiʔtjiəlɨj*

ក|neck|kɑː
គ|mute|kɔː
ខត់|to polish|kʰɑt
ឃត់|to prevent|kʰuə̆t
ង៉ាវ|noise-maker|ŋaːw
ងាវ|kind of clam|ŋiəw
ចា|to inscribe|caː
ជា|be|ciə
ឆោង|interval|cʰaoŋ
ញ៉ាំ|to eat|ɲam
ញាំ|meat salad|ɲoə̆m
ដុន|elephant command|ɗon
ឌុន|alike|ɗun
តា|old man|taː
ទា|duck|tiə
ថូ|waste|tʰou
ឋាន|place, site|tʰaːn
ធូរ|relaxed|tʰuː
ឍាល|large drum|tʰiəl
ណាយ|bored|naːj
ហ្នឹង|that's right|nəŋ
នាយ|chief|niəj
ប៊ុត|a personal name|ɓut
ប្រុត|son|bot
ព៉ី|flute|pəj
ពី|from|piː
ផាយ|run at full speed|pʰaːj
ភាយ|to circulate|pʰiəj
ម៉ែ|mother|mae
មែ|polite response particle|mɛː
ហ្មត់|fine, powdered|mɑt
យ៉ាង|kind; variety|jaːŋ
យាង|go (royalty)|jiəŋ
រ៉ូង|rattling noise|rouŋ
រូង|hole|ruːŋ
ឡេង|personal name|leiŋ
ហ្លួង|king|luəŋ
លាង|to play|leeŋ
វ៉ៃ|to hit|ʋaj
វៃ|quick, clever|ʋɨj
ហ្វូង|flock, crowd|ʋouŋ
សី|wicker ball|səj
ស៊ី|to eat|siː
ហាង|shop, store|haːŋ
ហ៊ាន|to dare|hiən
អី/what||ʔəj
អ៊ី|interjection|ʔiː
ហ្វឹក|to practice|fək
ហ្វ៊ីស៉ិក|physics|fiːsik
រៀប|to arrange|riəp
ភាព|aspect|pʰiəp
លោភ|greed|loːp
កាត់|to cut|kat
បាទ|male polite response|ɓaːt
ប្រាកដ|exact|praːkɑːt
បាឋ|to tell, recite (clergy)|ɓaːt
ឥដ្ឋ|brick|ʔət
គ្រុឌ|garuda|krut
ប្រមាថ|to scorn, despise|prɑmaːt
អាវុធ|weapon|ʔaːʋut
អាសាឍ|June-July|ʔaːsaːt
តូច|small|touc
រាជ|reign|riəc
ជីក|to dig|ciːk
រោគ|rook, disease|roːk
មុខ|face|muk
មេឃ|sky|meːk
កាក|refuse, residue|kaːʔ
នាគ|dragon|niəʔ
ពិសាខ|April-May|pisaːʔ
មាឃ|January|miəʔ
តាម|to follow|taːm
ដុំ|piece|ɗom
ចំ|exact|cɑm
ចាំ|remember|cam
មាន|to have|miən
បូរាណ|ancient|ɓouraːn
ទាញ|to pull|tiəɲ
ដឹង|to know|ɗəŋ
រីញ|dried up|riːɲ
អាវ|shirt|ʔaːw
ហៅ|to call|haw
បាយ|cooked rice, food|ɓaːj
ព្រៃ|forest|prɨj
កាល|time|kaːl
ចាស់|old|cah
ទះ|to slap|teə̆h
កត់|jot down|kɑt
ទប់|to stop up|tup
យល់|to understand|juə̆l
ស័ក|era|saʔ
ល័ខ|gum lac|leə̆k
ទ័ព|army|toə̆p
សម័យ|era|sɑmaj
ជ័យ|victory|cɨj
ជ័រ|resin|cɔə
តា|grandfather|taː
ជា|to be|ciə
ទាក់|to trap|teə̆ʔ
គាត់|he, she, they|koə̆t
មតិ|opinion|matteʔ
កិរិយា|conduct|kerijaː
លទ្ធិ|precept|lattʰiʔ
និទាន|story|nitiən
ចិត្ត|heart, mind|cət
ជិត|near|cɨt
ចេតិយ|stupa|caetdəj
ឥន្ត្រិយ|power|ʔəntriː
តិះដៀល|to ridicule|tehɗiəl
ជិះ|to ride|cih
បី|three|ɓəj
ពីរ|two|piː
ដឹក|transport|ɗək
ទឹក|water|tɨk
ឆ្កឹះ|to pry out|ckəh
ដឺ|fallow|ɗəɨ
គឺ|as follows|kɨː
វត្តុ|artifact|ʋoə̆ttoʔ
កុមារ|child|komaː
វិទ្យុ|radio|ʋitjuʔ
គុលិកា|pill|kulikaː
កុន|film|kon
គុណ|merit|kun
ចុះ|to descend|coh
ពុះ|boiled|puh
កូរ|to stir|kou
គូ|pair|kuː
ត្រូវ|correct|trəw
នូវ|consisting of|nɨw
កួរ|pod, ear|kuə
បើ|if|ɓaə
ឈើ|wood|cʰəː
តឿ|dwarfed|tɨə
ជឿ|to believe|cɨə
តៀប|bowl|tiəp
ទៀប|nearly|tiəp
កេរ្តិ៍|heritage|kei
គេ|he, she, they|keː
ម៉េច|how, why|məc
ពេញ|full|pɨɲ
សេះ|horse|seh
នេះ|this, here|nih
កែ|to repair|kae
គែ|craw (of bird)|kɛː
កែះ|kind of goat|keh
ប្រៃ|salty|praj
កោរ|to shave|kao
គោ|cow|koː
កោះ|island|kɑh
គោះ|to strike|kuə̆h
តៅ|bushel|taw
ទៅ|to go|tɨw
ដុំ|piece, morsel|ɗom
ទុំ|ripe|tum
ទំ|to perch|tum
ចាំ|to remember|cam
ជាំ|bruised|coə̆m
តាំង|to establish|taŋ
ទាំង|all of|teə̆ŋ
តះ|to wiggle|tɑh
ទះ|to slap|teə̆h
ឬស្សី|bamboo|rɨːhsəj
ឬ|or|rɨː
រំឭក|to commemorate|rumlɨk
ឮ|to hear|lɨː
ឩដ្ឋ|camel|ʔout
ឩន|deficient (lit.)|ʔuːn
គួរ|proper|kuə
ឯ|at, as, for|ʔae
ឧបាសក|layman|ʔaoɓaːsɑʔ
ឱប|to embrace|ʔaop
ឲ្យ|to give|jʔaoj
ឥន្ទុ|the moon|ʔɨntuʔ
ឥត|not|ʔət
ឪពុក|father|ʔəwpuk
ឥឡូវ|now|ʔəjləw
ឦសាន|northeast|ʔəjsaːn
ឧកញ៉ា|official of ministerial rank|ʔokɲaː
ឧបម៉ា|example|uppəmaː
ឰរាវ័ណ|Erawan|ʔajrəʋoə̆n
ឳទក|water-plant|ʔawtuə̆k
លប|fish trap|lɔːp
លប់|bird trap|lup
ចប់|to finish|cɑp
ចប|hoe|cɑːp
ចាប់|to catch|cap
ចាប|sparrow|caːp
លក់|to sell|luə̆ʔ
លក|to channel|lɔːk
ពាក់|to wear|peə̆ʔ
ពាក្យ|word|piəʔ
មាន់|to wear|moə̆n
ចិត្ដ|heart|cet
ចុះ|so?|coh
ចង្កើះ|chopsticks|cɑŋkəh

`

