// if there is a * after a transcription it has been autogenerated and needs checking

autoExpandExamples.km = `
ក|neck|kɑː
កញ្ជ្រេង|fox|kɑɲcreːŋ
កញ្ញា|young lady|kɑɲɲaa
កត់|jot down|kɑt
កន្ត្រៃ|scissors|kɑːntraj
កម្ម|mission|kɑːm*
កម្មករ|worker|kɑmmɔkɑː
កម្មផល|karma|kɑːmmɔːpʰɑːl*
កា|to address (a letter)|kaa
កាក|refuse, residue|kaːʔ
កាត់|to cut|kat
ការ|to work|kaa
កាល|time|kaːl
កាហ្វេ|coffee|kaːfei
កិរិយា|conduct|kerijaː
កឹះ|to scratch|kəh
កុន|film|kon
កុមារ|child|komaː
កូរ|to stir|kou
កួរ|pod, ear|kuə
កេរ្តិ៍|heritage|kei
កែ|to repair|kae
កែះ|wild goat|keh
កោរ|to shave|kao
កោះ|island|kɑh
កំពុង|present tense marker|kɑmpuŋ
ក៏|also, therefore|kɑː
ក្រុមហ៊ុន|company|kromhun
ខត់|to polish|kʰɑt
ខាង|direction|kʰaːŋ
ខ្មែរ|Cambodian|kmae
ខ្លាឃ្មុំ|bear|kʰlaːkʰmum
ខ្លាំង ៗ|very strong|klaŋklaŋ
ខ្លះ|some|klɑh
គ|mute|kɔː
គ|that is|kɨː
គាត់|he, she, they|koə̆t
គាត់មានផ្ទះថ្មី ៗ|he has a brand new house|kaːtʰ miən pʰteə̯h tʰməitʰməi
គឺ|as follows|kɨː
គុណ|merit|kun
គុលិកា|pill|kulikaː
គូ|pair|kuː
គួរ|proper|kuə
គេ|he, she, they|keː
គេ|they|kei
គែ|craw (of bird)|kɛː
គោ|cow|koː
គោះ|to strike|kuə̆h
គ្រុឌ|garuda|krut
ឃត់|to prevent|kʰuə̆t
ឃ្លាន|hungry|kliən
ងងឹត|dark|ŋoŋət
ងាវ|kind of clam|ŋiəw
ង៉ាវ|noise-maker|ŋaːw
ចង់|to want|cɑŋ
ចង្កើះ|chopsticks|cɑŋkəh
ចប|hoe|cɑːp
ចប់|to finish|cɑp
ចា|to inscribe|caː
ចាប|sparrow|caːp
ចាប់|to catch|cap
ចាស់|old|cah
ចាំ|to remember|cam
ចិត្ត|heart, mind|cət
ចុះ|so?|coh
ចុះ|to descend|coh
ចេតិយ|stupa|caetdəj
ចំ|exact|cɑm
ច្រៀង|singing|criəŋ
ឆោង|interval|cʰaoŋ
ឆ្កឹះ|to pry out|ckəh
ជា|is|ciə
ជា|to be|ciə
ជាតិ|national|ciəteʔ*
ជាតិសាសន៍|race|ciəteʔsaːsɑː*
ជាំ|bruised|coə̆m
ជិត|near|cɨt
ជិះ|to ride|cih
ជីក|to dig|ciːk
ជឿ|to believe|cɨə
ជ័យ|victory|cɨj
ជ័រ|resin|cɔə
ឈប់|to stop|cʰup
ឈឺ|sick|cʰɨː
ឈើ|wood|cʰəː
ឈ្មោះ|name|cʰmuə
ញាំ|meat salad|ɲoə̆m
ញី|female|ɲiː
ញ៉ាំ|to eat|ɲam
ដម|nectar|ɗɑːm
ដាំ|to plant|ɗam
ដឹក|transport|ɗək
ដឹង|to know|ɗəŋ
ដឺ|fallow|ɗəɨ
ដុន|elephant command|ɗon
ដុល្លារ|dollar|ɗɑllaː
ដុំ|piece, morsel|ɗom
ដំ|to pound|ɗɑm
ដ៏|which, very|ɗɑː
ឋាន|place, site|tʰaːn
ឌុន|alike|ɗun
ឍាល|large drum|tʰiəl
ណា|which, where|naː
ណាយ|bored|naːj
ណាស់|very|nah
ណែ៎|Hey !|nɛː
តង្វាយ|gift|ɗɔŋʋaaj
តា|grandfather|taː
តា|old man|taː
តាម|to follow|taːm
តាំង|to establish|taŋ
តិះដៀល|to ridicule|tehɗiəl
តូច|small|touc
តឿ|dwarfed|tɨə
តៀប|bowl|tiəp
តៅ|bushel|taw
តះ|to wiggle|tɑh
ត្រី|fish|trəj
ត្រូវ|correct|trəw
ថា|saying, as follows|tʰaː
ថា|that|tʰaː
ថូ|waste|tʰou
ទប់|to stop up|tup
ទម្ងន់|weight|tɔmŋɔn
ទា|duck|tiə
ទាក់|to trap|teə̆ʔ
ទាញ|to pull|tiəɲ
ទាំង|all of|teə̆ŋ
ទាំង|including, both|teə̯ŋ
ទឹក|water|tɨk
ទុគ៌ត|destitute|tuːrəkuə̆t
ទុំ|ripe|tum
ទៀប|nearly|tiəp
ទៅ|to go|tɨw
ទំ|to perch|tum
ទះ|to slap|teə̆h
ទ័ព|army|toə̆p
ធុរៈ|preoccupation|tʰureə̆ʔ
ធូរ|relaxed|tʰuː
ធំ|big|tʰɑm
នាគ|dragon|niəʔ
នាយ|chief|niəj
នាំ|to lead|noə̯m
និទាន|story|nitiən
នឹង|future tense marker|nəŋ
នុ៎ះន៎|Over there !|nuhnɔː
នូវ|consisting of|nɨw
នេះ|this, here|nih
នោះ|that|nuh
នៅណោះ|over there|nəɨnɔh
បច្ច័យ|money|paccaj
បញ្ឆោត|to trick|ɓɑɲcʰaot
បណ្តុះ|to grow|ɓɑnɗoh
បន្តិចម្ដង ៗ|little by little|ɓɑntecmɗɑːŋ ɓɑntecmɗɑːŋ
បន្តុះ|to criticize|ɓɑntoh
បន្ទប់|room|ɓɑntuɓ
បរិបូណ៌|abundant|ɓɑriɓou
បាឋ|to tell, recite (clergy)|ɓaːt
បាទ|male polite response|ɓaːt
បាន|to have|ɓaːn
បាយ|cooked rice, food|ɓaːj
បី|three|ɓəj
បូរាណ|ancient|ɓouraːn
បើ|if|ɓaə
ប៉ា|father|paː
ប៉ាន|to cover|paːn
ប៉ះ|to touch|pah
ប៊ុត|a personal name|ɓut
ប្រមាថ|to scorn, despise|prɑmaːt
ប្រយ័ត្ន|to be careful|prɑjat
ប្រាកដ|exact|praːkɑːt
ប្រាជ្ញា|intelligence|praːcɲaa
ប្រុត|son|bot
ប្រៃ|salty|praj
ផាយ|run at full speed|pʰaːj
ផ្សារ|market|psaː
ពណ៌|colour|pɔə
ពាក់|to wear|peə̆ʔ
ពាក្យ|word|piəʔ
ពាម|mouth of a river|piəm
ពាំ|to carry in the beak|poə̆m
ពិសាខ|April-May|pisaːʔ
ពី|from|piː
ពីរ|two|piː
ពុះ|boiled|puh
ពុះ|to boil|puh
ពេញ|full|pɨɲ
ពេទ្យ|medical|peit
ព៉ី|flute|pəj
ព្រៃ|forest|prɨj
ភាព|aspect|pʰiəp
ភាយ|to circulate|pʰiəj
ភាសា|language|pʰiəsaː
ភំ|big|tʰom
មតិ|opinion|matteʔ
មាឃ|January|miəʔ
មាន|to have|miən
មាន|word|miən
មាន់|to wear|moə̆n
មុខ|ahead, front|muk
មុខ|face|muk
មេឃ|sky|meːk
មែ|polite response particle|mɛː
ម៉ត់ចត់|careful|mɑtcɑt
ម៉ឺន|10,000|məɨn
ម៉េច|how, why|məc
ម៉ែ|mother|mae
ម្ហូបបារាំង|French food|mhouɓɓaːraŋ
យល់|to understand|juə̆l
យាង|go (royalty)|jiəŋ
យ៉ាង|kind; variety|jaːŋ
រដ្ឋ|state|rɔat
រាជ|reign|riəc
រីញ|dried up|riːŋ
រូង|hole|ruːŋ
រូប|picture|ruːɓ
រៀប|to arrange|riəp
រេហ៍ពល|army|rɔpuə̆l
រោគ|rook, disease|roːk
រំភើប|excited|rumɓəːpʰ
រំឭក|to commemorate|rumlɨk
រ៉ាប់|to guarrantee|rap
រ៉ូង|rattling noise|rouŋ
លក|to channel|lɔːk
លក់|to sell|luə̆ʔ
លទ្ធិ|precept|lattʰiʔ
លប|fish trap|lɔːp
លប់|bird trap|lup
លាង|to play|leeŋ
លុយ|money|luj
លើក|to lift|ləːk
លោភ|greed|loːp
ល័ខ|gum lac|leə̆k
វត្តុ|artifact|ʋoə̆ttoʔ
វិញ|instead, again|ʋiɲ
វិទ្យាល័យ|highschool|ʋiʔtjiəlɨj*
វិទ្យុ|radio|ʋitjuʔ
វៃ|quick, clever|ʋɨj
វ៉ៃ|to hit|ʋaj
វ័ង|palace|ʋeə̯ŋ
សកលវិទ្យាល័យ|university|sɑːkɑːlɔːʋiʔtjiəlɨj*
សងស្ក្រិត|Sanskrit|sɑŋskret
សប្ដាហ៍|week|sɑpɗaː
សម័យ|era|sɑmaj
សាសន៍|race, ethnicity|saːh
សាស្ត្រាចារ្យ|teacher|sɑstraːcaː
សី|wicker ball|səj
សូមទោស|I beg your pardon|soum toːs
សេះ|horse|seh
សំយោគសញ្ញា|name of a diacritic|sɑnjoːksaɲɲaː
សំស្ក្រិត|Sanskrit|sɑŋskret
ស៊ី|to eat|siː
ស័ក|era|saʔ
ស័កិ្ត|rank|sak
ស្រៈ|vowel|sraʔ
ហាង|shop, store|haːŋ
ហាន|shop|haːn
ហៅ|to call|haw
ហ៊ាន|to dare|hiən
ហ្នឹង|that's right|nəŋ
ហ្មត់|fine, powdered|mɑt
ហ្លួង|king|luəŋ
ហ្វឹក|to practice|fək
ហ្វូង|crowd|ʋouŋ
ហ្វូង|flock, crowd|ʋouŋ
ហ្វ៊ីស៉ិក|physics|fiːsik
ឡេង|personal name|leiŋ
អង្គ្លេស|English|ʔɑŋkleːh
អន្តរជាតិ|international|ʔɑːntɑːciəteʔ*
អាត្មន៑|soul|ʔaːtman
អាវ|shirt|ʔaːw
អាវុធ|weapon|ʔaːʋut
អាសាឍ|June-July|ʔaːsaːt
អី/what||ʔəj
អី|what|ʔī
អូ|exclamation|ʔou
អ៊ី|interjection|ʔiː
អ៊ូ|dry dock|ʔuː
ឥដ្ឋ|brick|ʔət
ឥត|not|ʔət
ឥន្ត្រិយ|power|ʔəntriː
ឥន្ទុ|the moon|ʔɨntuʔ
ឥឡូវ|now|ʔəjləw
ឦសាន|northeast|ʔəjsaːn
ឧកញ៉ា|official of ministerial rank|ʔokɲaː
ឧបម៉ា|example|uppəmaː
ឧបាសក|layman|ʔaoɓaːsɑʔ
ឩដ្ឋ|camel|ʔout
ឩន|deficient (lit.)|ʔuːn
ឪពុក|father|ʔəwpuk
ឬ|or|rɨː
ឬស្សី|bamboo|rɨːhsəj
ឮ|to hear|lɨː
ឯ|at, as, for|ʔae
ឰរាវ័ណ|Erawan|ʔajrəʋoə̆n
ឱប|to embrace|ʔaop
ឲ្យ|to give|ʔaoj
ឳទក|water-plant|ʔawtuə̆k
៣០០០ ៛|3000 riel|ɓej poan riəl

`

