// if there is a * after a transcription it has been autogenerated and needs checking

var examples = `


ကဏ္ဍ|section|kàɴda̰
ကား|car|ká
ကောက်ညှင်း|sticky rice|kaʊʔɲ̥ɪ́ɴ
ကျပ်|to be tight|tɕaʔ
ကျား|tiger|tɕá
ကျောင်း|school|tɕáʊɴ
ကျွန်မတို့|(female) we|tɕəma̰do̰
ကျွန်ုပ်|first person singular|tɕʊ̀ɴnoʊʔ
ကြက်|chicken|tɕɛʔ
ကြက်သွန်ဖြူ|garlic|tɕɛʔθʊ̀ɴbjù
ကြား|between|dʑá
ကြိုက်|like|tɕaɪʔ
ကြောင်|cat|dʑàʊɴ
ခက်|difficult|kʰɛʔ
ခေါက်ဆွဲ|noodles|kʰaʊʔ sʰwɛ́
ခေါင်း|head|kʰáʊɴ
ခဲတံ|pencil|kʰɛ́dàɴ
ခ္လိုဝ်း|wash
ချယ်|cook|tɕʰɛ̀ʔ
ချားနား|different|tɕʰáná
ဂဏန်း|crab|ga̰náɴ
ဂဠုန်|Garuda|gəlòʊɴ
ဂျပန်|Japan|dʑəpàɴ
ငှက်|bird|ŋ̥ɛʔ
စက္ကူ|paper|sɛʔkù
စကြဝဠာ|universe|seja̰wə̰là
စာအုပ်|book|sàʔoʊʔ
စေတီ|table|zèdì
စောင့်တယ်|to wait|sa̰ʊɴdɛ̀
စျေး|market|zé
ဆရာ|teacher|sʰəjà
ဆိုင်|store|sʰàɪɴ
ဆိုး|bad|sʰó
ဆေး|medecine|sʰé
ဆေးရုံ|hospital|sʰéjòʊɴ
ဇွန်း|spoon|zʊ́ɴ
ညာ|right|ɲà
ညှပ်|cut|ɲ̥aʔ
တကယ်ပါ|certainly, really|da̰gɛ̀bà
တက္ကသိုလ်|university|təʔkəθò
တချို့|some|tətɕʰo̰
တစ်ဆယ်|ten
တစ်သိန်း|hundred thousand|təθéɪɴ
တီဗွီ|T.V.|tìbwì
တံခါး|door|dəgá
တံဂါ|fisherman|təɴgà
ထမင်းဆိုင်|restaurant|tʰa̰mɪ́ɴzàɪɴ
ထားဝယ်|Tavoy/Dawei|dáwɛ̀
ထိုင်းနိုင်ဂံ|Thailand|tʰáɪɴnàɪɴgàɴ
ထီး|umbrella|tʰí
ထောပတ်သီး|banana|tʰɔ́baʔdʰí
ဒေါ်လေး|aunt|dɔlè [dɔ̀lé?]
ဓာတ်|electric|daʔ
နာရီ|hour|nàjì
နို့နဲ့|with milk|no̰nɛ̰
နောက်လ|next month|naʊʔla̰
နွား|cow|nwá
နှစ်|year|n̥ɪʔ
နှာ|nose|n̥à
ပဉ္စမ|fifth|pɪ̀ɴza̰ma̰
ပန်း|flower|páɴ
ပန်းသီး|apple|páɴðí
ပသျှူး|Malay|pa̰ʃú
ပိန္နဲသီး|jackfruit|pèɪɴnɛ́ dʰí
ပိုက်ဆံ|money|paɪʔsʰàɴ
ပုဂံ|Pagan/Bagan|bəgàɴ
ပေါင်|thigh|pàʊɴ
ပေါ့တယ်|bland, tasteless|pɔ̰dɛ̀
ပေါ့တယ်|to be light|pɔ̰dɛ̀
ပျော့တယ်|to be soft|pjɔ̰dɛ̀
ပျော်|happy|pjɔ̀
ပျော်တယ်|to be happy|pjɔ̀dɛ̀
ပြည်|country|pjɛ
ပြတင်းပေါက်|window|bədɪ́ɴbaʊʔ
ပြီခဲ့တဲ့လ|last month|pìgɛ̰dɛ̰la̰
ပြီးခဲ့တဲ့|last|pígɛ̰dɛ̰
ပြီးခဲ့တဲ့လ|last month|pjígɛ̰dɛ̰la̰
ပြောင်းဖူး|corn|pjáʊɴbú
ဖိနပ်|shoe|pʰənaʔ
ဗိုက်ဆာတယ်|to be hungry|baɪʔsʰàdɛ̀
ဗိုလ်|lieutenant|bò
ဗုဒ္ဓ|Buddha|boʊʔda̰
ဗုဒ္ဓဟူးနေ့|Wednesday|boʊʔdəhúnḛ
ဘက်|side|bɛʔ
ဘတ်(စ်)|bus|bas
ဘယ်|which|bɛ̀
ဘုရား|pagoda|pʰəjá
ဘဲ|duck|bɛ́
မတ်|March|maʔ
မန္တလေး|Mandalay|màɴda̰lé
မာ|hard|mà
မိနစ်|minute|mḭnɪʔ
မီ|before|mì
မီး|fire|mí
မုန့်ဆိုင်|bakery|mo̰ʊɴzàɪɴ
မုန်လာဥနီ|carrots|mòʊɴlàʔṵnì
မေ့|forget|mḛ
မြေပုံ|map|mjèbòʊɴ
မြွေ|snake|mwè
မှာ|at|m̥à
မှာ|in, at|m̥à
ယောက်ျား|man, husband|jaʊʔtɕá
ရင်|if|jɪ̀ɴ
ရစ်|pheasant|jɪʔ
ရန်ကုန်|Rangoon|jàɴgòʊɴ
ရေ|water|jè
ရေဒီယို|radio|rèdìjò
ရွှေပဲသီး|snow peas|ʃwebɛ̀
ရှိတယ်|to have|ʃḭdɛ̀
ရှေ့|front|ʃḛ
လ|month|la̰
လက်ဖက်|tea|lɛʔpʰɛʔ
လမ်း|road|láɴ
လမ်းလျှောက်တယ်|to walk|láɴʃaʊʔtɛ̀
လားရှိုး|Lashio|láʃó
လိုက်|follow|laɪʔ
လူမျိုး|nationality|lùmjó
လေယာဉ်|airplane|lèjaɴ
လျှာ|tongue|ʃà
လှ|pretty|l̥a̰
ဝင်|enter|wɪ̀ɴ
ဝန်ကြီး|minister|wʊ̀ɴtɕí
ဝှက်|hide|w̥ɛʔ
သတင်းစာ|farmer|θa̰dɪ́ɴzà
သဒ္ဒါ|grammar|θəda
သန်းခေါင်|midnight|dəgàʊɴ
သိပ်|very|θeɪʔ
သိမ်း|save|θéɪɴ
သိုး|three|θóʊɴ
သုံး|three|tʰóʊɴ
သုံး|use|θóʊɴ
သွား|to go|θwà
သဿ|Pali corn, crop|θa̰θθa̰
ဟင်းနုနွယ်|amaranth|hɪ́ɴnṵnwɛ̀
ဟုတ်ကဲ့|yes|hoʊʔkɛ̰
အက္ခရာ|character, script|ʔɛʔkʰəjà
အကျဉ်းထောင်|prison|ʔa̰dʑɪ́ɴdàʊɴ
အင်္ဂလန်|England|ʔɪ̀ɴgə̰làɴ
အညို|brown|ʔəɲò
အတန်း|class|ʔa̰táɴ
အန္တရာယ်|danger|ʔàɴdəje
အပ်ချုပ်သမား|tailor|ʔaʔtɕʰoʊʔθəmá
အဖြူ|white|ʔə̰pʰjù
အဘိဓာန်|dictionary|ʔa̰bḭdaɴ
အမည်း|black|ʔa̰mɛ́
အရိပ်|shadow|ʔa̰jeɪʔ
အားကစား|sport,athletics|ʔágəzá
အိတ်|bag|ʔeɪʔ
အိန္ဒိယ|India|ʔèɪɴdḭja̰
အိမ်|house, home|ʔèɪɴ
အုန်းသီး|coconut|ʔóʊɴdʰí
အောက်တိုဘာ|October|ʔaʊʔtòbà
အဲဒါ|that|ʔɛ́dà
ဤ|this|ʔì
ဥ|egg|ʔṵ
ဥစ္စာ|property|ʔoʊʔsà
ဦး|uncle, Mr.|ʔù
ဦးလေး|uncle|úlé
ဧက|acre|ʔèka̰
ဧရာဝတီ|Irawaddy river|ʔèjàwa̰dì
ဩဂုတ်|August|ʔɔ́goʊʔ
ဩဇာသီး|custard apple|ʔɔ́zàðí

`

