// if there is a * after a transcription it has been autogenerated and needs checking

autoExpandExamples.bo = `
ཁ་ཁེབ་|cover|kʰa-kʰep
ཁ་ཎ་ཌ་|Canada|(kha-ṇa-ḍa)
གྱུརད་|became|kjùr
ཏཱ་བླ་མ་|grand lama|(tā-bla-ma)
ད་ལྟ་|now|dan-ta
དཀར་པོ་|white|karpo
དག་|I|dàg
དགའ་|virtue|gà
དགེ་འདུན་|buddhist community|(dge-'dun)
དབང་ཆ་|power|wang-ʧa
བདུན་|seven|dỳn
བསད་|killed|sɛ́
བསྒྲུབས་|established|ɖɹúb
མཐུན་|agreement
མཚམས་|boundary
མི་|person|(mi)
མེའུ་|dwarf|(me'u)
མོ་ཊ་|car|mo-ta
འཁོར་ལོ་|wheel|kor-lo
འགྲེམས་སྟོན་|exhibition|ɖɹem-ton
རེ་བ་|hope|re-wa
རྡེའུ་|pebble|(rde'u)
རྡོ་|stone|(rdo)
ཤྲཱི་|wealth|(shrī)
སྐར་ཆ་|second|karcʰe (skar-cha)
སྤྱིར་|general|ʧí

`

