langTag = 'und'
window.version = 'v29'
window.scriptName = ''
window.ghDirectory = 'punctuation'
window.blockDirectory = 'punctuation'
window.languageList = ['und'] // lang tags for each orthography handled
window.detailsfileList = ['und'] // first part of xx-details for each orthography
window.scriptISO = 'latn'
window.webfonts = ["Noto Sans WF"]
window.defaultSize = '24px'
hideBlockName = ""
