window.version = 'v29'
window.scriptName = 'Gujarati'
window.ghDirectory = 'gujarati'
window.blockDirectory = 'gujarati'
window.languageList = ['gu'] // lang tags for each orthography handled
window.detailsfileList = ['gu'] // first part of xx-details for each orthography
window.scriptISO = 'gujr'
window.webfonts = ["Noto Serif Gujarati WF", "Noto Sans Gujarati WF"]
window.defaultSize = '24px'
window.hideBlockName = "GUJARATI"
