langTag = 'tyj'
window.version = 'v29'
window.scriptName = 'Tai Yo'
window.ghDirectory = 'tayo'
window.blockDirectory = 'tayo'
window.languageList = ['tyj'] // lang tags for each orthography handled
window.detailsfileList = ['tyj'] // first part of xx-details for each orthography
window.scriptISO = 'tayo'
window.webfonts = ["Noto Serif Tai Yo WF"]
window.defaultSize = '24px'
hideBlockName = "TAI YO"
