(function(g){var window=this;'use strict';var pKa=function(a,b){return g.Mb(a,b)},qKa=function(a){if(a instanceof g.cj)return a;
if("function"==typeof a.wh)return a.wh(!1);if(g.Ma(a)){var b=0,c=new g.cj;c.next=function(){for(;;){if(b>=a.length)throw g.Nn;if(b in a)return a[b++];b++}};
return c}throw Error("Not implemented");},rKa=function(a,b,c){if(g.Ma(a))try{g.zb(a,b,c)}catch(d){if(d!==g.Nn)throw d;
}else{a=qKa(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(d){if(d!==g.Nn)throw d;}}},O4=function(a,b,c){a.l.set(b,c)},P4=function(a){O4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Sa()).toString(36));
return a},Q4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.fn(a.l,b,c)},sKa=function(a,b){var c=[];
rKa(b,function(d){try{var e=g.co.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.bo(e)&&c.push(d)},a);
return c},tKa=function(a,b){b=sKa(a,b);
g.zb(b,function(c){g.co.prototype.remove.call(this,c)},a)},uKa=function(a){if(a.V){if(a.V.locationOverrideToken)return{locationOverrideToken:a.V.locationOverrideToken};
if(null!=a.V.latitudeE7&&null!=a.V.longitudeE7)return{latitudeE7:a.V.latitudeE7,longitudeE7:a.V.longitudeE7}}return null},vKa=function(a,b){g.fb(a,b)||a.push(b)},R4=function(a){var b=0,c;
for(c in a)b++;return b},wKa=function(a,b){b=b instanceof g.Cc?b:g.Jc(b,/^data:image\//i.test(b));
a.src=g.Dc(b)},xKa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},yKa=function(a){if(a.Gg&&"function"==typeof a.Gg)return a.Gg();
if("string"===typeof a)return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ib(a)},zKa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||"string"===typeof a)g.zb(a,b,void 0);else{if(a.Gh&&"function"==typeof a.Gh)var c=a.Gh();else if(a.Gg&&"function"==typeof a.Gg)c=void 0;else if(g.Ma(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Kb(a);d=yKa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},AKa=function(a,b,c,d){var e=new g.Um(null,void 0);
a&&g.Vm(e,a);b&&g.Wm(e,b);c&&g.Xm(e,c);d&&(e.J=d);return e},S4=function(){},T4=function(a,b){g.Xq[a]=!0;
var c=g.Vq();c&&c.publish.apply(c,arguments);g.Xq[a]=!1},U4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Rm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",BKa(this,a.capabilities||""),CKa(this,a.experiments||""))},BKa=function(a,b){a.capabilities.clear();
g.Ke(b.split(","),g.Qa(pKa,DKa)).forEach(function(c){a.capabilities.add(c)})},CKa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},V4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},W4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},EKa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},FKa=function(a){return new V4(a)},GKa=function(a){return Array.isArray(a)?g.Pc(a,FKa):[]},X4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},Y4=function(a){return Array.isArray(a)?"["+g.Pc(a,X4).join(",")+"]":"null"},Z4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},HKa=function(a){return g.Pc(a,function(b){return{key:b.id,
name:b.name}})},$4=function(a,b){return g.bb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},a5=function(a,b){return g.bb(a,function(c){return W4(c,b)})},IKa=function(){var a=(0,g.qv)();
a&&tKa(a,a.i.wh(!0))},b5=function(){var a=g.uv("yt-remote-connected-devices")||[];
g.wb(a);return a},JKa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Pc(a,function(d,e){return 0==e?d:d.substring(c.length)})},KKa=function(a){g.tv("yt-remote-connected-devices",a,86400)},d5=function(){if(c5)return c5;
var a=g.uv("yt-remote-device-id");a||(a=Z4(),g.tv("yt-remote-device-id",a,31536E3));for(var b=b5(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return c5=d},e5=function(){var a=b5(),b=d5();
g.fb(a,b);g.xv()&&g.yb(a,b);a=JKa(a);if(g.gb(a))try{g.Mo("remote_sid")}catch(c){}else try{g.Ko("remote_sid",a.join(","),-1)}catch(c){}},LKa=function(){return g.uv("yt-remote-session-browser-channel")},MKa=function(){return g.uv("yt-remote-local-screens")||[]},NKa=function(){g.tv("yt-remote-lounge-token-expiration",!0,86400)},OKa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Pc(MKa(),function(d){return d.loungeToken}),c=g.Pc(a,function(d){return d.loungeToken});
g.mh(c,function(d){return!g.fb(b,d)})&&NKa();
g.tv("yt-remote-local-screens",a,31536E3)},PKa=function(a,b){g.tv("yt-remote-session-browser-channel",a);
g.tv("yt-remote-session-screen-id",b);a=b5();b=d5();g.fb(a,b)||a.push(b);KKa(a);e5()},f5=function(a){a||(g.wv("yt-remote-session-screen-id"),g.wv("yt-remote-session-video-id"));
e5();a=b5();g.kb(a,d5());KKa(a)},QKa=function(){if(!g5){var a=g.vo();
a&&(g5=new g.Xn(a))}},RKa=function(){QKa();
return g5?!!g5.get("yt-remote-use-staging-server"):!1},h5=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},SKa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},TKa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},i5=function(a){a.length?UKa(a.shift(),function(){i5(a)}):j5()},VKa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},UKa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.kg(d,g.ng(a));(document.head||document.documentElement).appendChild(d)},WKa=function(){var a=h5(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},j5=function(){var a=TKa();
a&&a(!1,"No cast extension found")},k5=function(){if(XKa){var a=2,b=TKa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;UKa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",j5,c)}},YKa=function(){k5();
var a=WKa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");i5(a)},$Ka=function(){k5();
var a=WKa();a.push.apply(a,g.na(ZKa.map(VKa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");i5(a)},l5=function(a,b,c){g.F.call(this);
this.G=null!=c?(0,g.C)(a,c):a;this.Kf=b;this.C=(0,g.C)(this.UL,this);this.i=!1;this.l=0;this.u=this.yb=null;this.B=[]},m5=function(a,b,c){g.F.call(this);
this.B=null!=c?a.bind(c):a;this.Kf=b;this.u=null;this.i=!1;this.l=0;this.yb=null},n5=function(a){a.yb=g.Pm(function(){a.yb=null;
a.i&&!a.l&&(a.i=!1,n5(a))},a.Kf);
var b=a.u;a.u=null;a.B.apply(null,b)},o5=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return xKa(a)},p5=function(){},q5=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},s5=function(a){r5.dispatchEvent(new aLa(r5,a))},aLa=function(a,b){g.Kl.call(this,"statevent",a);
this.stat=b},t5=function(){},bLa=function(){},dLa=function(a){return(a=cLa(a))?new ActiveXObject(a):new XMLHttpRequest},cLa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},u5=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.i0(this);this.u=new g.Om;this.u.setInterval(250)},fLa=function(a,b,c){a.Sq=1;
a.Gl=P4(b.clone());a.Uo=c;a.G=!0;eLa(a,null)},v5=function(a,b,c,d,e){a.Sq=1;
a.Gl=P4(b.clone());a.Uo=null;a.G=c;e&&(a.WI=!1);eLa(a,d)},eLa=function(a,b){a.Jq=Date.now();
w5(a);a.Km=a.Gl.clone();Q4(a.Km,"t",a.J);a.vu=0;a.Le=a.i.Jz(a.i.Tt()?b:null);0<a.Iy&&(a.bx=new m5((0,g.C)(a.RJ,a,a.Le),a.Iy));a.B.Oa(a.Le,"readystatechange",a.kS);b=a.fn?g.Tb(a.fn):{};a.Uo?(a.Ox="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Le.send(a.Km,a.Ox,a.Uo,b)):(a.Ox="GET",a.WI&&!g.Ae&&(b.Connection="close"),a.Le.send(a.Km,a.Ox,null,b));a.i.Ii(1)},iLa=function(a,b,c){for(var d=!0;!a.Kn&&a.vu<c.length;){var e=gLa(a,c);
if(e==x5){4==b&&(a.Bl=4,s5(15),d=!1);break}else if(e==hLa){a.Bl=4;s5(16);d=!1;break}else y5(a,e)}4==b&&0==c.length&&(a.Bl=1,s5(17),d=!1);a.Ui=a.Ui&&d;d||(z5(a),A5(a))},gLa=function(a,b){var c=a.vu,d=b.indexOf("\n",c);
if(-1==d)return x5;c=Number(b.substring(c,d));if(isNaN(c))return hLa;d+=1;if(d+c>b.length)return x5;b=b.substr(d,c);a.vu=d+c;return b},kLa=function(a,b){a.Jq=Date.now();
w5(a);var c=b?window.location.hostname:"";a.Km=a.Gl.clone();O4(a.Km,"DOMAIN",c);O4(a.Km,"t",a.J);try{a.Yi=new ActiveXObject("htmlfile")}catch(m){z5(a);a.Bl=7;s5(22);A5(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in B5)f=B5[f];else if(f in jLa)f=B5[f]=jLa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
B5[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.gd(g.ec("b/12014412"),d+"</body></html>");a.Yi.open();a.Yi.write(g.cd(c));a.Yi.close();a.Yi.parentWindow.m=(0,g.C)(a.IR,a);a.Yi.parentWindow.d=(0,g.C)(a.kI,a,!0);a.Yi.parentWindow.rpcClose=(0,g.C)(a.kI,a,!1);c=a.Yi.createElement("DIV");a.Yi.parentWindow.document.body.appendChild(c);d=g.Ic(a.Km.toString());d=g.rd(g.Dc(d));d=g.gd(g.ec("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,d);a.i.Ii(1)},w5=function(a){a.TC=Date.now()+
a.C;
lLa(a,a.C)},lLa=function(a,b){if(null!=a.Xq)throw Error("WatchDog timer not null");
a.Xq=q5((0,g.C)(a.QR,a),b)},C5=function(a){a.Xq&&(g.A.clearTimeout(a.Xq),a.Xq=null)},A5=function(a){a.i.QD()||a.Kn||a.i.Ju(a)},z5=function(a){C5(a);
g.Ii(a.bx);a.bx=null;a.u.stop();g.bFa(a.B);if(a.Le){var b=a.Le;a.Le=null;b.abort();b.dispose()}a.Yi&&(a.Yi=null)},y5=function(a,b){try{a.i.dI(a,b),a.i.Ii(4)}catch(c){}},nLa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;mLa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){nLa(a,b,c,d,f)},f)})}},mLa=function(a,b,c){var d=new Image;
d.onload=function(){try{D5(d),c(!0)}catch(e){}};
d.onerror=function(){try{D5(d),c(!1)}catch(e){}};
d.onabort=function(){try{D5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{D5(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
wKa(d,a)},D5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},E5=function(a){g.dm.call(this);
this.headers=new g.Rm;this.ra=a||null;this.B=!1;this.ma=this.i=null;this.Fa=this.V="";this.G=0;this.u="";this.C=this.ya=this.L=this.xa=!1;this.J=0;this.X=null;this.La="";this.Y=this.Da=!1},oLa=function(a){return g.ye&&g.be(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},pLa=function(a){return"content-type"==a.toLowerCase()},rLa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.G=5;qLa(a);F5(a)},qLa=function(a){a.xa||(a.xa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},tLa=function(a){if(a.B&&"undefined"!=typeof g.m0)if(a.ma[1]&&4==G5(a)&&2==a.getStatus())H5(a,"Local request error detected and ignored");
else if(a.L&&4==G5(a))g.Pm(a.aI,0,a);else if(a.dispatchEvent("readystatechange"),a.ue()){H5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Ad(1,String(a.V));if(!f&&g.A.self&&g.A.self.location){var h=g.A.self.location.protocol;f=h.substr(0,h.length-1)}e=!sLa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.G=6;try{var l=2<G5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";qLa(a)}}finally{F5(a)}}},F5=function(a,b){if(a.i){uLa(a);
var c=a.i,d=a.ma[0]?g.Ia:null;a.i=null;a.ma=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},uLa=function(a){a.i&&a.Y&&(a.i.ontimeout=null);
a.X&&(g.A.clearTimeout(a.X),a.X=null)},G5=function(a){return a.i?a.i.readyState:0},I5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},H5=function(a,b){return b+" ["+a.Fa+" "+a.V+" "+a.getStatus()+"]"},vLa=function(a){this.i=a;
this.l=new p5},wLa=function(a){var b=J5(a.i,a.Or,"/mail/images/cleardot.gif");
P4(b);nLa(b.toString(),5E3,(0,g.C)(a.PM,a),3,2E3);a.Ii(1)},L5=function(a){var b=a.i.L;
if(null!=b)s5(5),b?(s5(11),K5(a.i,a,!1)):(s5(12),K5(a.i,a,!0));else if(a.Pg=new u5(a,void 0,void 0,void 0),a.Pg.fn=a.Jy,b=a.i,b=J5(b,b.Tt()?a.Dr:null,a.Ky),s5(5),!g.ye||g.ce(10))Q4(b,"TYPE","xmlhttp"),v5(a.Pg,b,!1,a.Dr,!1);else{Q4(b,"TYPE","html");var c=a.Pg;a=!!a.Dr;c.Sq=3;c.Gl=P4(b.clone());kLa(c,a)}},M5=function(a,b,c){this.eb=1;
this.i=[];this.u=[];this.B=new p5;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},xLa=function(a,b){this.i=a;
this.map=b;this.context=null},yLa=function(a,b,c,d){g.Kl.call(this,"timingevent",a);
this.size=b;this.Nt=d},zLa=function(a){g.Kl.call(this,"serverreachability",a)},CLa=function(a){ALa(a);
if(3==a.eb){var b=a.jt++,c=a.xv.clone();O4(c,"SID",a.l);O4(c,"RID",b);O4(c,"TYPE","terminate");N5(a,c);b=new u5(a,a.l,b,void 0);b.Sq=2;b.Gl=P4(c.clone());wKa(new Image,b.Gl.toString());b.Jq=Date.now();w5(b)}BLa(a)},DLa=function(a){a.oN(1,0);
a.xv=J5(a,null,a.Ly);O5(a)},ALa=function(a){a.Ll&&(a.Ll.abort(),a.Ll=null);
a.Zd&&(a.Zd.cancel(),a.Zd=null);a.Ck&&(g.A.clearTimeout(a.Ck),a.Ck=null);P5(a);a.Eg&&(a.Eg.cancel(),a.Eg=null);a.Tl&&(g.A.clearTimeout(a.Tl),a.Tl=null)},ELa=function(a,b){if(0==a.eb)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new xLa(a.OO++,b));2!=a.eb&&3!=a.eb||O5(a)},FLa=function(a){var b=0;
a.Zd&&b++;a.Eg&&b++;return b},O5=function(a){a.Eg||a.Tl||(a.Tl=q5((0,g.C)(a.iI,a),0),a.eq=0)},HLa=function(a,b){if(1==a.eb){if(!b){a.jt=Math.floor(1E5*Math.random());
b=a.jt++;var c=new u5(a,"",b,void 0);c.fn=a.sj;var d=Q5(a),e=a.xv.clone();O4(e,"RID",b);O4(e,"CVER","1");N5(a,e);fLa(c,e,d);a.Eg=c;a.eb=2}}else 3==a.eb&&(b?GLa(a,b):0==a.i.length||a.Eg||GLa(a))},GLa=function(a,b){if(b)if(6<a.Ln){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.jt-1;b=Q5(a)}else c=b.L,b=b.Uo;else c=a.jt++,b=Q5(a);var d=a.xv.clone();O4(d,"SID",a.l);O4(d,"RID",c);O4(d,"AID",a.xq);N5(a,d);c=new u5(a,a.l,c,a.eq+1);c.fn=a.sj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Eg=c;fLa(c,d,b)},N5=function(a,b){a.Df&&(a=a.Df.PF())&&g.Bb(a,function(c,d){O4(b,d,c)})},Q5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Ln&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={xp:e.xp},f++){e.xp=a.i[f].i;var h=a.i[f].map;e.xp=6>=a.Ln?f:e.xp-d;try{g.Bb(h,function(l){return function(m,n){c.push("req"+l.xp+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.xp+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},ILa=function(a){a.Zd||a.Ck||(a.G=1,a.Ck=q5((0,g.C)(a.hI,a),0),a.Rp=0)},R5=function(a){if(a.Zd||a.Ck||3<=a.Rp)return!1;
a.G++;a.Ck=q5((0,g.C)(a.hI,a),JLa(a,a.Rp));a.Rp++;return!0},K5=function(a,b,c){a.Mx=c;
a.tj=b.qk;a.C||DLa(a)},P5=function(a){null!=a.Sn&&(g.A.clearTimeout(a.Sn),a.Sn=null)},JLa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},S5=function(a,b){if(2==b||9==b){var c=null;
a.Df&&(c=null);var d=(0,g.C)(a.PS,a);c||(c=new g.Um("//www.google.com/images/cleardot.gif"),P4(c));mLa(c.toString(),1E4,d)}else s5(2);KLa(a,b)},KLa=function(a,b){a.eb=0;
a.Df&&a.Df.gF(b);BLa(a);ALa(a)},BLa=function(a){a.eb=0;
a.tj=-1;if(a.Df)if(0==a.u.length&&0==a.i.length)a.Df.vz();else{g.ob(a.u);var b=g.ob(a.i);a.u.length=0;a.i.length=0;a.Df.vz(b)}},J5=function(a,b,c){var d=g.bn(c);
if(""!=d.i)b&&g.Wm(d,b+"."+d.i),g.Xm(d,d.u);else{var e=window.location;d=AKa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.hs&&g.Bb(a.hs,function(f,h){O4(d,h,f)});
O4(d,"VER",a.Ln);N5(a,d);return d},LLa=function(){},MLa=function(){this.i=[];
this.l=[]},NLa=function(a,b){this.action=a;
this.params=b||{}},T5=function(a,b){g.F.call(this);
this.i=new g.J(this.AR,0,this);g.G(this,this.i);this.Kf=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.C)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.C)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},U5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ma=a;this.G=b;this.u=new g.Wn;this.l=new T5(this.vS,this);this.i=null;this.X=!1;this.C=null;this.V="";this.L=this.B=0;this.J=[];this.ra=c;this.Y=d;this.xa=e},OLa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Mx,sessionId:a.i.l,arrayId:a.i.xq}},PLa=function(a,b){a.L=b||0;
a.l.stop();V5(a);a.i&&(3==a.i.getState()&&HLa(a.i),CLa(a.i));a.L=0},W5=function(a){return!!a.i&&3==a.i.getState()},V5=function(a){if(a.i){var b=a.Y(),c=a.i.sj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.sj=c}},X5=function(a){this.port=this.domain="";
this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.Ad(4,a))||"";b&&(this.port=":"+b);this.domain=g.Bd(a)||"";a=g.Vc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ac(a,"10.0")&&(this.l=!1))},Y5=function(a,b){var c=a.i;
a.l&&(c="https://"+a.domain+a.port+a.i);return g.Od(c+b,{})},Z5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.B,d,!0),onError:g.Qa(a.u,e),onTimeout:g.Qa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Bp(b,a)},TLa=function(){var a=QLa;
RLa();$5.push(a);SLa()},a6=function(a,b){RLa();
var c=ULa(a,String(b));g.gb($5)?VLa(c):(SLa(),g.zb($5,function(d){d(c)}))},RLa=function(){$5||($5=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",$5,void 0))},VLa=function(a){var b=(b6+1)%50;
b6=b;c6[b]=a;d6||(d6=49==b)},SLa=function(){var a=$5;
if(c6[0]){var b=d6?b6:-1;do{b=(b+1)%50;var c=c6[b];g.zb(a,function(d){d(c)})}while(b!=b6);
c6=Array(50);b6=-1;d6=!1}},ULa=function(a,b){var c=(Date.now()-WLa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},e6=function(a){g.P.call(this);
this.G=a;this.screens=[]},XLa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},YLa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ke(a.screens,function(f){return!!$4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=XLa(a,b[d])||c;return c},ZLa=function(a,b){var c=a.screens.length;
a.screens=g.Ke(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},f6=function(a,b,c,d,e){g.P.call(this);
this.u=a;this.J=b;this.B=c;this.G=d;this.C=e;this.l=0;this.i=null;this.yb=NaN},h6=function(a){e6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;g6(this);this.info("Initializing with "+Y4(this.screens))},$La=function(a){if(a.screens.length){var b=g.Pc(a.screens,function(d){return d.id}),c=Y5(a.l,"/pairing/get_lounge_token_batch");
Z5(a.l,c,{screen_ids:b.join(",")},(0,g.C)(a.LN,a),(0,g.C)(a.KN,a))}},g6=function(a){if(g.Vo("deprecate_pair_servlet_enabled"))return YLa(a,[]);
var b=GKa(MKa());b=g.Ke(b,function(c){return!c.uuid});
return YLa(a,b)},i6=function(a,b){OKa(g.Pc(a.screens,EKa));
b&&NKa()},k6=function(a,b){g.P.call(this);
this.G=b;b=(b=g.uv("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.G(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.fb(b,h)}this.i=c;this.C=a;this.u=this.B=NaN;this.l=null;j6("Initialized with "+g.Fj(this.i))},l6=function(a,b,c){var d=Y5(a.C,"/pairing/get_screen_availability");
Z5(a.C,d,{lounge_token:b.token},(0,g.C)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.C)(function(){c(!1)},a))},m6=function(a,b){a:if(R4(b)!=R4(a.i))var c=!1;
else{c=g.Kb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(j6("Updated online screens: "+g.Fj(a.i)),a.i=b,a.W("screenChange"));aMa(a)},n6=function(a){isNaN(a.u)||g.wp(a.u);
a.u=g.up((0,g.C)(a.TB,a),0<a.B&&a.B<g.Sa()?2E4:1E4)},j6=function(a){a6("OnlineScreenService",a)},bMa=function(a){var b={};
g.zb(a.G(),function(c){c.token?b[c.token]=c.id:this.Md("Requesting availability of screen w/o lounge token.")});
return b},aMa=function(a){a=g.Kb(g.Cb(a.i,function(b){return b}));
g.wb(a);a.length?g.tv("yt-remote-online-screen-ids",a.join(","),60):g.wv("yt-remote-online-screen-ids")},o6=function(a,b){b=void 0===b?!1:b;
e6.call(this,"ScreenService");this.B=a;this.J=b;this.i=this.l=null;this.u=[];this.C={};cMa(this)},eMa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.dh(),l=c?a5(h,c):null;c&&(a.J||l)||(l=a5(h,b));if(l){l.uuid=b;var m=p6(a,l);l6(a.i,m,function(n){e(n?m:null)})}else c?dMa(a,c,(0,g.C)(function(n){var p=p6(this,new V4({name:d,
screenId:c,loungeToken:n,dialId:b||""}));l6(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},fMa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},gMa=function(a,b,c){l6(a.i,b,c)},dMa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Bp(Y5(a.B,"/pairing/get_lounge_token_batch"),e)},hMa=function(a){a.screens=a.l.dh();
for(var b=g.Vb(a.C),c=0,d=a.screens.length;c<d;++c){var e=a.screens[c];e.uuid=b[e.id]||""}a.info("Updated manual screens: "+Y4(a.screens))},cMa=function(a){q6(a);
a.l=new h6(a.B);a.l.subscribe("screenChange",(0,g.C)(a.RN,a));hMa(a);a.J||(a.u=GKa(g.uv("yt-remote-automatic-screen-cache")||[]));q6(a);a.info("Initializing automatic screens: "+Y4(a.u));a.i=new k6(a.B,(0,g.C)(a.dh,a,!0));a.i.subscribe("screenChange",(0,g.C)(function(){this.W("onlineScreenChange")},a))},p6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=a5(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),a.J||iMa(a));q6(a);a.C[b.uuid]=b.id;g.tv("yt-remote-device-id-map",a.C,31536E3);return b},iMa=function(a){a=g.Ke(a.u,function(b){return"shortLived"!=b.idType});
g.tv("yt-remote-automatic-screen-cache",g.Pc(a,EKa))},q6=function(a){a.C=g.uv("yt-remote-device-id-map")||{}},r6=function(a,b,c){g.P.call(this);
this.xa=c;this.u=a;this.i=b;this.B=null},s6=function(a,b){a.B=b;
a.W("sessionScreen",a.B)},jMa=function(a,b){a.B&&(a.B.token=b,p6(a.u,a.B));
a.W("sessionScreen",a.B)},t6=function(a,b){a6(a.xa,b)},u6=function(a,b,c){r6.call(this,a,b,"CastSession");
var d=this;this.ya=c;this.l=null;this.Y=(0,g.C)(this.ZL,this);this.ra=(0,g.C)(this.UR,this);this.X=g.up(function(){kMa(d,null)},12E4);
this.J=this.C=this.G=this.L=0;this.ma=!1;this.V="unknown"},v6=function(a,b){g.wp(a.J);
a.J=0;0==b?lMa(a):a.J=g.up(function(){lMa(a)},b)},lMa=function(a){mMa(a,"getLoungeToken");
g.wp(a.C);a.C=g.up(function(){nMa(a,null)},3E4)},mMa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Fj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.C)(function(){t6(this,"Failed to send message: "+b+".")},a)):t6(a,"Sending yt message without session: "+g.Fj(c))},w6=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.eG(b,function(c){s6(a,c)},function(){return a.jg()},5)):a.jg(Error("Waiting for session status timed out."))},pMa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new V4(b);oMa(a,d,function(e){e?(a.ma=!0,p6(a.u,d),s6(a,d),a.V="unknown",v6(a,c)):(g.$o(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.jg())},5)},kMa=function(a,b){g.wp(a.X);
a.X=0;b?a.ya.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?pMa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.$o(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),w6(a,b.screenId))):(g.$o(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),
w6(a,b.screenId)):w6(a,b.screenId):a.jg(Error("Waiting for session status timed out."))},nMa=function(a,b){g.wp(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.V=c,v6(a,3E4)):(jMa(a,b.loungeToken),a.ma=!1,a.V="unknown",v6(a,b.loungeTokenRefreshIntervalMs))},oMa=function(a,b,c,d){g.wp(a.G);
a.G=0;gMa(a.u,b,function(e){e||0>d?c(e):a.G=g.up(function(){oMa(a,b,c,d-1)},300)})},qMa=function(a){g.wp(a.L);
a.L=0;g.wp(a.G);a.G=0;g.wp(a.X);a.X=0;g.wp(a.C);a.C=0;g.wp(a.J);a.J=0},x6=function(a,b,c,d){r6.call(this,a,b,"DialSession");
this.Da=d;this.l=this.L=null;this.ra="";this.Fa=c;this.Ea=null;this.X=g.Ia;this.V=NaN;this.ya=(0,g.C)(this.aM,this);this.C=g.Ia;this.J=this.G=0;this.Y=!1;this.ma="unknown"},y6=function(a){var b;
return!!(a.Da.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},rMa=function(a){a.C=a.u.SD(a.ra,a.i.label,a.i.friendlyName,y6(a),function(b,c){a.C=g.Ia;
a.Y=!0;s6(a,b);"shortLived"==b.idType&&0<c&&z6(a,c)},function(b){a.C=g.Ia;
a.jg(b)})},sMa=function(a){var b={};
b.pairingCode=a.ra;b.theme=a.Fa;RKa()&&(b.env_useStageMdx=1);return g.Md(b)},A6=function(a){return new Promise(function(b){a.ra=Z4();
if(a.Ea){var c=new chrome.cast.DialLaunchResponse(!0,sMa(a));b(c);rMa(a)}else a.X=function(){g.wp(a.V);a.X=function(){};
a.V=NaN;var d=new chrome.cast.DialLaunchResponse(!0,sMa(a));b(d);rMa(a)},a.V=g.up(function(){a.X()},100)})},uMa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new V4(b);return(new Promise(function(e){tMa(a,d,function(f){f?(a.Y=!0,p6(a.u,d),s6(a,d),z6(a,c)):g.$o(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):A6(a)})},vMa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){eMa(a.u,c,b,d,function(f){f&&f.token&&s6(a,f);e(f)},function(f){t6(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):A6(a)})},tMa=function(a,b,c,d){g.wp(a.G);
a.G=0;gMa(a.u,b,function(e){e||0>d?c(e):a.G=g.up(function(){tMa(a,b,c,d-1)},300)})},z6=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
y6(a)&&(g.wp(a.J),a.J=0,0==b?wMa(a):a.J=g.up(function(){wMa(a)},b))},wMa=function(a){y6(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ma=c,z6(a,3E4)):(a.Y=!1,a.ma="unknown",jMa(a,b.loungeToken),z6(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ma="noLoungeTokenResponse";z6(a,3E4)})},xMa=function(a){g.wp(a.G);
a.G=0;g.wp(a.J);a.J=0;a.C();a.C=function(){};
g.wp(a.V)},B6=function(a,b){r6.call(this,a,b,"ManualSession");
this.l=g.up((0,g.C)(this.yq,this,null),150)},C6=function(a,b){g.P.call(this);
this.B=b;this.l=a;this.L=b.appId||"233637DE";this.C=b.theme||"cl";this.V=b.disableCastApi||!1;this.i=null;this.J=!1;this.u=[];this.G=(0,g.C)(this.QQ,this)},yMa=function(a,b){return b?g.bb(a.u,function(c){return W4(b,c.label)},a):null},D6=function(a){a6("Controller",a)},QLa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},E6=function(a){return a.J||!!a.u.length||!!a.i},F6=function(a,b,c){b!=a.i&&(g.Ii(a.i),(a.i=b)?(c?a.W("yt-remote-cast2-receiver-resumed",
b.i):a.W("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.C)(a.gI,a,b)),b.getScreen()?a.W("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.yq(null)):a.W("yt-remote-cast2-session-change",null))},zMa=function(a){var b=a.l.RD(),c=a.i&&a.i.i;
a=g.Pc(b,function(d){c&&W4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=yMa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},EMa=function(a,b,c,d){d.disableCastApi?G6("Cannot initialize because disabled by Mdx config."):AMa()?BMa(b,d)&&(H6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?CMa(a,c):(window.__onGCastApiAvailable=function(e,f){e?CMa(a,c):(I6("Failed to load cast API: "+f),J6(!1),H6(!1),g.wv("yt-remote-cast-available"),g.wv("yt-remote-cast-receiver"),
DMa(),c(!1))},d.loadCastApiSetupScript?g.yv("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=h5()&&YKa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?j5():89<=h5()?$Ka():(k5(),i5(ZKa.map(VKa))))):G6("Cannot initialize because not running Chrome")},DMa=function(){G6("dispose");
var a=K6();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);FMa(!1);g.$q(L6);L6.length=0},M6=function(){return!!g.uv("yt-remote-cast-installed")},GMa=function(){var a=g.uv("yt-remote-cast-receiver");
return a?a.friendlyName:null},HMa=function(){G6("clearCurrentReceiver");
g.wv("yt-remote-cast-receiver")},IMa=function(){return M6()?K6()?K6().getCastSession():(I6("getCastSelector: Cast is not initialized."),null):(I6("getCastSelector: Cast API is not installed!"),null)},O6=function(){M6()?K6()?N6()?(G6("Requesting cast selector."),K6().requestSession()):(G6("Wait for cast API to be ready to request the session."),L6.push(g.Zq("yt-remote-cast2-api-ready",O6))):I6("requestCastSelector: Cast is not initialized."):I6("requestCastSelector: Cast API is not installed!")},P6=
function(a,b){N6()?K6().setConnectedScreenStatus(a,b):I6("setConnectedScreenStatus called before ready.")},AMa=function(){var a=0<=g.Vc.search(/ (CrMo|Chrome|CriOS)\//);
return g.uB||a},JMa=function(a,b){K6().init(a,b)},BMa=function(a,b){var c=!1;
K6()||(a=new C6(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.tv("yt-remote-cast-available",d);T4("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){G6("onReceiverSelected: "+d.friendlyName);
g.tv("yt-remote-cast-receiver",d);T4("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){G6("onReceiverResumed: "+d.friendlyName);
g.tv("yt-remote-cast-receiver",d);T4("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){G6("onSessionChange: "+X4(d));
d||g.wv("yt-remote-cast-receiver");T4("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
G6("cloudview.createSingleton_: "+c);return c},K6=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},CMa=function(a,b){J6(!0);
H6(!1);JMa(a,function(c){c?(FMa(!0),g.ar("yt-remote-cast2-api-ready")):(I6("Failed to initialize cast API."),J6(!1),g.wv("yt-remote-cast-available"),g.wv("yt-remote-cast-receiver"),DMa());b(c)})},G6=function(a){a6("cloudview",a)},I6=function(a){a6("cloudview",a)},J6=function(a){G6("setCastInstalled_ "+a);
g.tv("yt-remote-cast-installed",a)},N6=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},FMa=function(a){G6("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},H6=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},Q6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.G=this.J=0;this.trackData=null;this.hasNext=this.Hj=!1;this.L=this.C=this.i=this.B=0;this.u=NaN;this.l=!1;this.reset(a)},R6=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Hj=!1;a.hasNext=!1;a.J=0;a.G=g.Sa();a.B=0;a.i=0;a.C=0;a.L=0;a.u=NaN;a.l=!1},S6=function(a){return a.qc()?(g.Sa()-a.G)/1E3:0},T6=function(a,b){a.J=b;
a.G=g.Sa()},U6=function(a){switch(a.playerState){case 1:case 1081:return(g.Sa()-a.G)/1E3+a.J;
case -1E3:return 0}return a.J},V6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&R6(a)},W6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Ub(a.trackData);b.hasPrevious=a.Hj;b.hasNext=a.hasNext;b.playerTime=a.J;b.playerTimeAt=a.G;b.seekableStart=a.B;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.L;b.liveIngestionTime=a.u;return b},Y6=function(a,b){g.P.call(this);
this.eb=0;this.u=a;this.C=[];this.B=new MLa;this.l=this.i=null;this.L=(0,g.C)(this.vP,this);this.G=(0,g.C)(this.ot,this);this.J=(0,g.C)(this.uP,this);this.V=(0,g.C)(this.CP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.fC,this),KMa(this))):c=3;0!=c&&(b?this.fC(c):g.up((0,g.C)(function(){this.fC(c)},this),0));
(a=IMa())&&X6(this,a);this.subscribe("yt-remote-cast2-session-change",this.V)},Z6=function(a){return new Q6(a.u.getPlayerContextData())},KMa=function(a){g.zb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Qa(this.NQ,b),this))},a)},LMa=function(a){g.zb(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},$6=function(a){return 1==a.getState()},a7=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},c7=function(a,b,c){var d=Z6(a);
T6(d,c);-1E3!=d.playerState&&(d.playerState=b);b7(a,d)},d7=function(a,b,c){a.u.sendMessage(b,c)},b7=function(a,b){LMa(a);
a.u.setPlayerContextData(W6(b));KMa(a)},X6=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.G),a.ot(null));
a.l=b;a.l&&(a6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.G),a.l.media.length&&a.ot(a.l.media[0]))},MMa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=Z6(a);b.contentId!=d.videoId&&a6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;T6(d,a.i.getEstimatedTime());b7(a,d)}else a6("CP","No cast media video. Ignoring state update.")},e7=function(a,b,c){return(0,g.C)(function(d){this.Md("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Md("Retrying "+b+" using MDx browser channel."),d7(this,b,c))},a)},f7=function(a,b,c){g.P.call(this);
this.C=NaN;this.ma=!1;this.L=this.J=this.X=this.Y=NaN;this.V=[];this.B=this.G=this.u=this.dc=this.i=null;this.xa=a;this.V.push(g.$p(window,"beforeunload",(0,g.C)(this.HN,this)));this.l=[];this.dc=new Q6;this.ya=b.id;this.ra=b.idType;this.i=NMa(this,c);this.i.subscribe("handlerOpened",this.zP,this);this.i.subscribe("handlerClosed",this.wP,this);this.i.subscribe("handlerError",this.xP,this);this.i.subscribe("handlerMessage",this.yP,this);this.i.ox(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.dc.videoId;g.xv()&&g.tv("yt-remote-session-video-id",d)},this)},g7=function(a){a6("conn",a)},NMa=function(a,b){return new U5(Y5(a.xa,"/bc"),b,!1,function(){return a.WD()},"shortLived"==a.ra)},h7=function(a,b){a.W("proxyStateChange",b)},OMa=function(a){a.C=g.up((0,g.C)(function(){g7("Connecting timeout");
this.Zp(1)},a),2E4)},i7=function(a){g.wp(a.C);
a.C=NaN},j7=function(a){g.wp(a.Y);
a.Y=NaN},PMa=function(a){k7(a);
a.X=g.up((0,g.C)(function(){l7(this,"getNowPlaying")},a),2E4)},k7=function(a){g.wp(a.X);
a.X=NaN},RMa=function(a,b){b&&(i7(a),j7(a));
var c=W5(a.i)&&isNaN(a.C);b==c?b&&(h7(a,1),l7(a,"getSubtitlesTrack")):b?(a.dG()&&a.dc.reset(),h7(a,1),l7(a,"getNowPlaying"),QMa(a)):a.Zp(1)},SMa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.dc.videoId&&(g.Pb(b.params)?a.dc.trackData=null:a.dc.trackData=b.params,a.W("remotePlayerChange"))},TMa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.dc.listId=b.params.listId||a.dc.listId;V6(a.dc,c,d);a.W("remoteQueueChange")},VMa=function(a,b){b.params=b.params||{};
TMa(a,b);UMa(a,b);a.W("autoplayDismissed")},UMa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
T6(a.dc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.dc.playerState&&(c=-1E3);a.dc.playerState=c;c=Number(b.params.loadedTime);a.dc.L=isNaN(c)?0:c;c=Number(b.params.duration);a.dc.C=isNaN(c)?0:c;c=a.dc;var d=Number(b.params.liveIngestionTime);c.u=d;c.l=isNaN(d)?!1:!0;c=a.dc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.dc.playerState?PMa(a):k7(a);a.W("remotePlayerChange")},WMa=function(a,b){if(-1E3!=a.dc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.dc.playerState=c;b=parseInt(b.params.currentTime,10);T6(a.dc,isNaN(b)?0:b);a.W("remotePlayerChange")}},XMa=function(a,b){var c="true"==b.params.muted;
a.dc.volume=parseInt(b.params.volume,10);a.dc.muted=c;a.W("remotePlayerChange")},YMa=function(a,b){a.G=b.params.videoId;
a.W("nowAutoplaying",parseInt(b.params.timeout,10))},ZMa=function(a,b){var c="true"==b.params.hasNext;
a.dc.Hj="true"==b.params.hasPrevious;a.dc.hasNext=c;a.W("previousNextChange")},QMa=function(a){g.wp(a.L);
a.L=g.up((0,g.C)(a.Zp,a,1),864E5)},l7=function(a,b,c){c?g7("Sending: action="+b+", params="+g.Fj(c)):g7("Sending: action="+b);
a.i.sendMessage(b,c)},m7=function(a){e6.call(this,"ScreenServiceProxy");
this.Jf=a;this.i=[];this.i.push(this.Jf.$_s("screenChange",(0,g.C)(this.eM,this)));this.i.push(this.Jf.$_s("onlineScreenChange",(0,g.C)(this.uQ,this)))},cNa=function(a,b){QKa();
if(!g5||!g5.get("yt-remote-disable-remote-module-for-dev")){b=g.N("MDX_CONFIG")||b;IKa();e5();n7||(n7=new X5(b?b.loungeApiHost:void 0),RKa()&&(n7.i="/api/loungedev"));o7||(o7=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",o7,void 0));$Ma();var c=p7();if(!c){var d=new o6(n7,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=p7();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});EMa(a,d,function(f){f?q7()&&P6(q7(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){T4("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),r7("Initializing: "+g.Fj(b)),s7.push(g.Zq("yt-remote-cast2-availability-change",function(){T4("yt-remote-receiver-availability-change")})),s7.push(g.Zq("yt-remote-cast2-receiver-selected",
function(){t7(null);
T4("yt-remote-auto-connect","cast-selector-receiver")})),s7.push(g.Zq("yt-remote-cast2-receiver-resumed",function(){T4("yt-remote-receiver-resumed","cast-selector-receiver")})),s7.push(g.Zq("yt-remote-cast2-session-change",aNa)),s7.push(g.Zq("yt-remote-connection-change",function(f){f?P6(q7(),"YouTube TV"):u7()||(P6(null,null),HMa())})),a=v7(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.Vo("desktop_enable_autoplay")&&e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=
b.theme)&&(a.theme=b),r7(" -- with channel params: "+g.Fj(a)),a?(g.tv("yt-remote-session-app",a.app),g.tv("yt-remote-session-name",a.name)):(g.wv("yt-remote-session-app"),g.wv("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),q7()||bNa())}},dNa=function(){var a=p7().Jf.$_gos();
var b=w7();b&&x7()&&($4(a,b)||a.push(b));return HKa(a)},y7=function(){var a=eNa();
!a&&M6()&&GMa()&&(a={key:"cast-selector-receiver",name:GMa()});return a},eNa=function(){var a=dNa(),b=w7();
b||(b=u7());return g.bb(a,function(c){return b&&W4(b,c.key)?!0:!1})},w7=function(){var a=q7();
if(!a)return null;var b=p7().dh();return a5(b,a)},aNa=function(a){r7("remote.onCastSessionChange_: "+X4(a));
if(a){var b=w7();if(b&&b.id==a.id){if(P6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))z7&&(z7.token=a),(b=x7())&&b.ox(a)}else b&&A7(),B7(a,1)}else x7()&&A7()},A7=function(){N6()?K6().stopSession():I6("stopSession called before API ready.");
var a=x7();a&&(a.disconnect(1),C7(null))},D7=function(){var a=x7();
return!!a&&3!=a.getProxyState()},r7=function(a){a6("remote",a)},p7=function(){if(!E7){var a=g.Ha("yt.mdx.remote.screenService_");
E7=a?new m7(a):null}return E7},q7=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},fNa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},gNa=function(){return g.Ha("yt.mdx.remote.connectData_")},t7=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},x7=function(){return g.Ha("yt.mdx.remote.connection_")},C7=function(a){var b=x7();
t7(null);a||fNa("");g.Ga("yt.mdx.remote.connection_",a,void 0);o7&&(g.zb(o7,function(c){c(a)}),o7.length=0);
b&&!a?T4("yt-remote-connection-change",!1):!b&&a&&T4("yt-remote-connection-change",!0)},u7=function(){var a=g.xv();
if(!a)return null;var b=p7();if(!b)return null;b=b.dh();return a5(b,a)},B7=function(a,b){q7();
w7()&&w7();F7?z7=a:(fNa(a.id),a=new f7(n7,a,v7()),a.connect(b,gNa()),a.subscribe("beforeDisconnect",function(c){T4("yt-remote-before-disconnect",c)}),a.subscribe("beforeDispose",function(){x7()&&(x7(),C7(null))}),a.subscribe("browserChannelAuthError",function(){var c=w7();
c&&"shortLived"==c.idType&&(N6()?K6().handleBrowserChannelAuthError():I6("refreshLoungeToken called before API ready."))}),C7(a))},bNa=function(){var a=u7();
a?(r7("Resume connection to: "+X4(a)),B7(a,0)):(f5(),HMa(),r7("Skipping connecting because no session screen found."))},$Ma=function(){var a=v7();
if(g.Pb(a)){a=d5();var b=g.uv("yt-remote-session-name")||"",c=g.uv("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},v7=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},G7=function(a,b,c){g.F.call(this);
var d=this;this.l=a;this.I=b;this.Ob=c;this.events=new g.bM(this);this.X=this.events.N(this.I,"onVolumeChange",function(e){hNa(d,e)});
this.C=!1;this.suggestion=null;this.G=new g.mJ(64);this.i=new g.J(this.eJ,500,this);this.u=new g.J(this.fJ,1E3,this);this.L=new l5(this.iT,0,this);this.B={};this.V=new g.J(this.KJ,1E3,this);this.J=new m5(this.seekTo,1E3,this);this.Y=g.Ia;g.G(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.fQ);this.events.N(b,"captionschanged",this.sP);this.events.N(b,"captionssettingschanged",this.lJ);this.events.N(b,"videoplayerreset",this.Uw);this.events.N(b,"mdxautoplaycancel",function(){d.Ob.zF()});
a=this.Ob;a.Ha();a.subscribe("proxyStateChange",this.cI,this);a.subscribe("remotePlayerChange",this.xt,this);a.subscribe("remoteQueueChange",this.Uw,this);a.subscribe("previousNextChange",this.ZH,this);a.subscribe("nowAutoplaying",this.TH,this);a.subscribe("autoplayDismissed",this.tH,this);g.G(this,this.i);g.G(this,this.u);g.G(this,this.L);g.G(this,this.V);g.G(this,this.J);this.lJ();this.Uw();this.xt()},hNa=function(a,b){if(H7(a)){a.Ob.unsubscribe("remotePlayerChange",a.xt,a);
var c=Math.round(b.volume);b=!!b.muted;var d=Z6(a.Ob);if(c!==d.volume||b!==d.muted)a.Ob.setVolume(c,b),a.V.start();a.Ob.subscribe("remotePlayerChange",a.xt,a)}},iNa=function(a){a.Tb(0);
a.i.stop();a.Lb(new g.mJ(64))},I7=function(a,b){if(H7(a)&&!a.C){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.Xb(c,b));a.Ob.VD(a.I.getVideoData(1).videoId,c);a.B=Z6(a.Ob).trackData}},J7=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Ob.playVideo(c.videoId,b,d,e,c.playerParams,c.Ea,uKa(c));a.Lb(new g.mJ(1))},jNa=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{tG:1});
c&&c.length?(a.I.setOption("captions","track",b),a.C=!1):(a.I.loadModule("captions"),a.C=!0)}else a.I.setOption("captions","track",{})},H7=function(a){return Z6(a.Ob).videoId===a.I.getVideoData(1).videoId},K7=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",oa:"Connecting to your TV on web using a code will be going away soon"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",Ca:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],oa:"Learn more"},{D:"button",Ca:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],oa:"OK"}]}]}]});this.i=new g.SK(this,250);this.learnMoreButton=
this.Ba("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Ba("ytp-mdx-manual-pairing-popup-ok");g.G(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},L7=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",oa:"You're signed out"},{D:"div",K:"ytp-mdx-popup-description",oa:"Videos that you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",Ca:["ytp-button","ytp-mdx-privacy-popup-cancel"],oa:"Cancel"},{D:"button",Ca:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],oa:"Confirm"}]}]}]});this.i=new g.SK(this,250);this.cancelButton=this.Ba("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Ba("ytp-mdx-privacy-popup-confirm");g.G(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},M7=function(a){g.V.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.Sma()]},{D:"div",K:"ytp-remote-display-status-text",oa:"{{statustext}}"}]}]});this.api=a;this.i=new g.SK(this,250);g.G(this,this.i);this.N(a,"presentingplayerstatechange",this.l);kNa(this,a.rb())},kNa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.QH("Error on $RECEIVER_NAME",c):b.qc()||g.U(b,4)?g.QH("Playing on $RECEIVER_NAME",c):g.QH("Connected to $RECEIVER_NAME",c);a.Qa("statustext",b);a.i.show()}else a.i.hide()},N7=function(a,b){g.cP.call(this,"Play on",0,a,b);
this.I=a;this.Hm={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},O7=function(a){g.mM.call(this,a);
this.Fi={key:Z4(),name:"This computer"};this.yh=null;this.subscriptions=[];this.GB=this.Ob=null;this.Hm=[this.Fi];this.Nl=this.Fi;this.fd=new g.mJ(64);this.PG=0;this.Ve=-1;this.Bq=null;this.Ct=this.ww=!1;this.dl=this.Iq=null;if(!g.KD(this.player.T())&&!g.LD(this.player.T())){a=this.player;var b=g.QL(a);b&&(b=b.fm())&&(b=new N7(a,b),g.G(this,b));b=new M7(a);g.G(this,b);g.$L(a,b.element,4);this.Iq=new L7;g.G(this,this.Iq);g.$L(a,this.Iq.element,4);g.R(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.R(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.Bq=new K7,g.G(this,this.Bq),g.$L(a,this.Bq.element,4));this.Ct=!!u7();this.ww=!!g.uv("yt-remote-manual-pairing-warning-shown")}},P7=function(a){a.dl&&(a.player.removeEventListener("presentingplayerstatechange",a.dl),a.dl=null)},lNa=function(a,b,c){a.fd=c;
a.player.W("presentingplayerstatechange",new g.CH(c,b))},mNa=function(a,b,c){var d=!1;
1===b?d=!a.Ct:2===b&&(d=!a.ww);d&&g.EH(c,8)&&(a.player.pauseVideo(),P7(a))},Q7=function(a,b){if(b.key!==a.Nl.key)if(b.key===a.Fi.key)A7();
else{if(a.Bq&&!a.ww&&b!==a.Fi&&"cast-selector-receiver"!==b.key&&g.fE(a.player.T()))nNa(a);else{var c;(c=!g.R(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.N("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.N("SESSION_INDEX")&&!g.N("LOGGED_IN")))||a.Ct||!a.Iq);(c?0:g.fE(a.player.T())||g.jE(a.player.T()))&&oNa(a)}a.Nl=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.R(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.bb(l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ea,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=uKa(c))&&(a.locationInfo=c)}r7("Connecting to: "+g.Fj(b));"cast-selector-receiver"==b.key?(t7(a||null),b=a||null,
N6()?K6().setLaunchParams(b):I6("setLaunchParams called before ready.")):!a&&D7()&&q7()==b.key?T4("yt-remote-connection-change",!0):(A7(),t7(a||null),a=p7().dh(),(b=a5(a,b.key))&&B7(b,1))}},oNa=function(a){a.player.rb().qc()?a.player.pauseVideo():(a.dl=function(b){mNa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.dl));
a.Iq&&a.Iq.Vc();x7()||(F7=!0)},nNa=function(a){a.player.rb().qc()?a.player.pauseVideo():(a.dl=function(b){mNa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.dl));
a.Bq&&a.Bq.Vc();x7()||(F7=!0)},jLa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},B5={"'":"\\'"},pNa={},DKa={gU:"atp",K3:"ska",C2:"que",I0:"mus",J3:"sus",bY:"dsp",V2:"seq",k0:"mic",bX:"dpa",uU:"cds",G0:"mlm"},g5,c5="",XKa=SKa("loadCastFramework")||SKa("loadCastApplicationFramework"),ZKa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(l5,g.F);g.k=l5.prototype;g.k.TL=function(a){this.B=arguments;this.i=!1;this.yb?this.u=g.Sa()+this.Kf:this.yb=g.Pm(this.C,this.Kf)};
g.k.stop=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.G.apply(null,this.B)))};
g.k.va=function(){this.stop();l5.Ld.va.call(this)};
g.k.UL=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null);this.u?(this.yb=g.Pm(this.C,this.u-g.Sa()),this.u=null):this.l?this.i=!0:(this.i=!1,this.G.apply(null,this.B))};g.v(m5,g.F);g.k=m5.prototype;g.k.OD=function(a){this.u=arguments;this.yb||this.l?this.i=!0:n5(this)};
g.k.stop=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.yb||(this.i=!1,n5(this))};
g.k.va=function(){g.F.prototype.va.call(this);this.stop()};p5.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
p5.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var r5=new g.dm;g.v(aLa,g.Kl);t5.prototype.i=null;t5.prototype.getOptions=function(){var a;(a=this.i)||(a={},cLa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var R7;g.Ta(bLa,t5);R7=new bLa;g.k=u5.prototype;g.k.fn=null;g.k.Ui=!1;g.k.Xq=null;g.k.TC=null;g.k.Jq=null;g.k.Sq=null;g.k.Gl=null;g.k.Km=null;g.k.Uo=null;g.k.Le=null;g.k.vu=0;g.k.Yi=null;g.k.Ox=null;g.k.Bl=null;g.k.Cr=-1;g.k.WI=!0;g.k.Kn=!1;g.k.Iy=0;g.k.bx=null;var hLa={},x5={};g.k=u5.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.kS=function(a){a=a.target;var b=this.bx;b&&3==G5(a)?b.OD():this.RJ(a)};
g.k.RJ=function(a){try{if(a==this.Le)a:{var b=G5(this.Le),c=this.Le.G,d=this.Le.getStatus();if(g.ye&&!g.ce(10)||g.Ae&&!g.be("420+")){if(4>b)break a}else if(3>b||3==b&&!g.sg&&!I5(this.Le))break a;this.Kn||4!=b||7==c||(8==c||0>=d?this.i.Ii(3):this.i.Ii(2));C5(this);var e=this.Le.getStatus();this.Cr=e;var f=I5(this.Le);(this.Ui=200==e)?(4==b&&z5(this),this.G?(iLa(this,b,f),g.sg&&this.Ui&&3==b&&(this.B.Oa(this.u,"tick",this.fS),this.u.start())):y5(this,f),this.Ui&&!this.Kn&&(4==b?this.i.Ju(this):(this.Ui=
!1,w5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Bl=3,s5(13)):(this.Bl=0,s5(14)),z5(this),A5(this))}}catch(h){this.Le&&I5(this.Le)}finally{}};
g.k.fS=function(){var a=G5(this.Le),b=I5(this.Le);this.vu<b.length&&(C5(this),iLa(this,a,b),this.Ui&&4!=a&&w5(this))};
g.k.IR=function(a){q5((0,g.C)(this.HR,this,a),0)};
g.k.HR=function(a){this.Kn||(C5(this),y5(this,a),w5(this))};
g.k.kI=function(a){q5((0,g.C)(this.GR,this,a),0)};
g.k.GR=function(a){this.Kn||(z5(this),this.Ui=a,this.i.Ju(this),this.i.Ii(4))};
g.k.cancel=function(){this.Kn=!0;z5(this)};
g.k.QR=function(){this.Xq=null;var a=Date.now();0<=a-this.TC?(2!=this.Sq&&this.i.Ii(3),z5(this),this.Bl=2,s5(18),A5(this)):lLa(this,this.TC-a)};
g.k.getLastError=function(){return this.Bl};g.Ta(E5,g.dm);var sLa=/^https?$/i,qNa=["POST","PUT"];g.k=E5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.V+"; newUri="+a);b=b?b.toUpperCase():"GET";this.V=a;this.u="";this.G=0;this.Fa=b;this.xa=!1;this.B=!0;this.i=this.ra?dLa(this.ra):dLa(R7);this.ma=this.ra?this.ra.getOptions():R7.getOptions();this.i.onreadystatechange=(0,g.C)(this.aI,this);try{S4(H5(this,"Opening Xhr")),this.ya=!0,this.i.open(b,String(a),!0),this.ya=!1}catch(f){S4(H5(this,"Error opening Xhr: "+f.message));rLa(this,f);return}a=
c||"";var e=this.headers.clone();d&&zKa(d,function(f,h){e.set(h,f)});
d=g.bb(e.Gh(),pLa);c=g.A.FormData&&a instanceof g.A.FormData;!g.fb(qNa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.La&&(this.i.responseType=this.La);"withCredentials"in this.i&&this.i.withCredentials!==this.Da&&(this.i.withCredentials=this.Da);try{uLa(this),0<this.J&&(this.Y=oLa(this.i),S4(H5(this,"Will abort after "+this.J+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.i.timeout=this.J,this.i.ontimeout=(0,g.C)(this.PD,this)):this.X=g.Pm(this.PD,this.J,this)),S4(H5(this,"Sending request")),this.L=!0,this.i.send(a),this.L=!1}catch(f){S4(H5(this,"Send error: "+f.message)),rLa(this,f)}};
g.k.PD=function(){"undefined"!=typeof g.m0&&this.i&&(this.u="Timed out after "+this.J+"ms, aborting",this.G=8,H5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(H5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.G=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),F5(this))};
g.k.va=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),F5(this,!0));E5.Ld.va.call(this)};
g.k.aI=function(){this.Ha()||(this.ya||this.L||this.C?tLa(this):this.PQ())};
g.k.PQ=function(){tLa(this)};
g.k.isActive=function(){return!!this.i};
g.k.ue=function(){return 4==G5(this)};
g.k.getStatus=function(){try{return 2<G5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.ue())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=vLa.prototype;g.k.Jy=null;g.k.Pg=null;g.k.dx=!1;g.k.gJ=null;g.k.wv=null;g.k.VA=null;g.k.Ky=null;g.k.eb=null;g.k.qk=-1;g.k.Dr=null;g.k.Or=null;g.k.connect=function(a){this.Ky=a;a=J5(this.i,null,this.Ky);s5(3);this.gJ=Date.now();var b=this.i.J;null!=b?(this.Dr=b[0],(this.Or=b[1])?(this.eb=1,wLa(this)):(this.eb=2,L5(this))):(Q4(a,"MODE","init"),this.Pg=new u5(this,void 0,void 0,void 0),this.Pg.fn=this.Jy,v5(this.Pg,a,!1,null,!0),this.eb=0)};
g.k.PM=function(a){if(a)this.eb=2,L5(this);else{s5(4);var b=this.i;b.tj=b.Ll.qk;S5(b,9)}a&&this.Ii(2)};
g.k.Jz=function(a){return this.i.Jz(a)};
g.k.abort=function(){this.Pg&&(this.Pg.cancel(),this.Pg=null);this.qk=-1};
g.k.QD=function(){return!1};
g.k.dI=function(a,b){this.qk=a.Cr;if(0==this.eb)if(b){try{var c=this.l.parse(b)}catch(d){a=this.i;a.tj=this.qk;S5(a,2);return}this.Dr=c[0];this.Or=c[1]}else a=this.i,a.tj=this.qk,S5(a,2);else if(2==this.eb)if(this.dx)s5(7),this.VA=Date.now();else if("11111"==b){if(s5(6),this.dx=!0,this.wv=Date.now(),a=this.wv-this.gJ,!g.ye||g.ce(10)||500>a)this.qk=200,this.Pg.cancel(),s5(12),K5(this.i,this,!0)}else s5(8),this.wv=this.VA=Date.now(),this.dx=!1};
g.k.Ju=function(){this.qk=this.Pg.Cr;if(this.Pg.Ui)0==this.eb?this.Or?(this.eb=1,wLa(this)):(this.eb=2,L5(this)):2==this.eb&&((!g.ye||g.ce(10)?!this.dx:200>this.VA-this.wv)?(s5(11),K5(this.i,this,!1)):(s5(12),K5(this.i,this,!0)));else{0==this.eb?s5(9):2==this.eb&&s5(10);var a=this.i;this.Pg.getLastError();a.tj=this.qk;S5(a,2)}};
g.k.Tt=function(){return this.i.Tt()};
g.k.isActive=function(){return this.i.isActive()};
g.k.Ii=function(a){this.i.Ii(a)};g.k=M5.prototype;g.k.sj=null;g.k.hs=null;g.k.Eg=null;g.k.Zd=null;g.k.Ly=null;g.k.xv=null;g.k.UE=null;g.k.Ku=null;g.k.jt=0;g.k.OO=0;g.k.Df=null;g.k.Tl=null;g.k.Ck=null;g.k.Sn=null;g.k.Ll=null;g.k.Mx=null;g.k.xq=-1;g.k.OG=-1;g.k.tj=-1;g.k.eq=0;g.k.Rp=0;g.k.Ln=8;g.Ta(yLa,g.Kl);g.Ta(zLa,g.Kl);g.k=M5.prototype;g.k.connect=function(a,b,c,d,e){s5(0);this.Ly=b;this.hs=c||{};d&&void 0!==e&&(this.hs.OSID=d,this.hs.OAID=e);this.C?(q5((0,g.C)(this.mF,this,a),100),DLa(this)):this.mF(a)};
g.k.mF=function(a){this.Ll=new vLa(this);this.Ll.Jy=this.sj;this.Ll.l=this.B;this.Ll.connect(a)};
g.k.QD=function(){return 0==this.eb};
g.k.getState=function(){return this.eb};
g.k.iI=function(a){this.Tl=null;HLa(this,a)};
g.k.hI=function(){this.Ck=null;this.Zd=new u5(this,this.l,"rpc",this.G);this.Zd.fn=this.sj;this.Zd.Iy=0;var a=this.UE.clone();O4(a,"RID","rpc");O4(a,"SID",this.l);O4(a,"CI",this.Mx?"0":"1");O4(a,"AID",this.xq);N5(this,a);if(!g.ye||g.ce(10))O4(a,"TYPE","xmlhttp"),v5(this.Zd,a,!0,this.Ku,!1);else{O4(a,"TYPE","html");var b=this.Zd,c=!!this.Ku;b.Sq=3;b.Gl=P4(a.clone());kLa(b,c)}};
g.k.dI=function(a,b){if(0!=this.eb&&(this.Zd==a||this.Eg==a))if(this.tj=a.Cr,this.Eg==a&&3==this.eb)if(7<this.Ln){try{var c=this.B.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.Ck){if(this.Zd)if(this.Zd.Jq+3E3<this.Eg.Jq)P5(this),this.Zd.cancel(),this.Zd=null;else break a;R5(this);s5(19)}}else this.OG=a[1],0<this.OG-this.xq&&37500>a[2]&&this.Mx&&0==this.Rp&&!this.Sn&&(this.Sn=q5((0,g.C)(this.pP,this),6E3));else S5(this,11)}else b!=pNa.QW.i&&S5(this,11);else if(this.Zd==
a&&P5(this),!g.pc(b))for(a=this.B.parse(b),b=0;b<a.length;b++)c=a[b],this.xq=c[0],c=c[1],2==this.eb?"c"==c[0]?(this.l=c[1],this.Ku=c[2],c=c[3],null!=c?this.Ln=c:this.Ln=6,this.eb=3,this.Df&&this.Df.iF(),this.UE=J5(this,this.Tt()?this.Ku:null,this.Ly),ILa(this)):"stop"==c[0]&&S5(this,7):3==this.eb&&("stop"==c[0]?S5(this,7):"noop"!=c[0]&&this.Df&&this.Df.hF(c),this.Rp=0)};
g.k.pP=function(){null!=this.Sn&&(this.Sn=null,this.Zd.cancel(),this.Zd=null,R5(this),s5(20))};
g.k.Ju=function(a){if(this.Zd==a){P5(this);this.Zd=null;var b=2}else if(this.Eg==a)this.Eg=null,b=1;else return;this.tj=a.Cr;if(0!=this.eb)if(a.Ui)1==b?(b=r5,b.dispatchEvent(new yLa(b,a.Uo?a.Uo.length:0,Date.now()-a.Jq,this.eq)),O5(this),this.u.length=0):ILa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.tj)){if(d=1==b)this.Eg||this.Tl||1==this.eb||2<=this.eq?d=!1:(this.Tl=q5((0,g.C)(this.iI,this,a),JLa(this,this.eq)),this.eq++,d=!0);d=!(d||2==b&&R5(this))}if(d)switch(c){case 1:S5(this,
5);break;case 4:S5(this,10);break;case 3:S5(this,6);break;case 7:S5(this,12);break;default:S5(this,2)}}};
g.k.oN=function(a){if(!g.fb(arguments,this.eb))throw Error("Unexpected channel state: "+this.eb);};
g.k.PS=function(a){a?s5(2):(s5(1),KLa(this,8))};
g.k.Jz=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new E5;a.Da=!1;return a};
g.k.isActive=function(){return!!this.Df&&this.Df.isActive(this)};
g.k.Ii=function(a){var b=r5;b.dispatchEvent(new zLa(b,a))};
g.k.Tt=function(){return!(!g.ye||g.ce(10))};
g.k=LLa.prototype;g.k.iF=function(){};
g.k.hF=function(){};
g.k.gF=function(){};
g.k.vz=function(){};
g.k.PF=function(){return{}};
g.k.isActive=function(){return!0};g.k=MLa.prototype;g.k.isEmpty=function(){return g.gb(this.i)&&g.gb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.fb(this.i,a)||g.fb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.gFa)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.l,a)};
g.k.Gg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Ta(T5,g.F);g.k=T5.prototype;g.k.AR=function(){this.Kf=Math.min(3E5,2*this.Kf);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Kf+15E3*Math.random();g.pn(this.i,a);this.l=g.Sa()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Kf=5E3};g.Ta(U5,LLa);g.k=U5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Sf=function(a){return this.u.Sf(a)};
g.k.W=function(a,b){return this.u.W.apply(this.u,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.Ii(this.u),PLa(this),g.Ii(this.l),this.l=null,this.Y=function(){return""})};
g.k.Ha=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.V="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ma+"/test";b=this.ma+"/bind";var d=new M5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ra),e=this.i;e&&(e.Df=null);d.Df=this;this.i=d;V5(this);if(this.i){d=g.N("ID_TOKEN");var f=this.i.sj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.sj=f}e?(3!=e.getState()&&0==FLa(e)||e.getState(),this.i.connect(a,b,this.G,e.l,e.xq)):c?this.i.connect(a,
b,this.G,c.sessionId,c.arrayId):this.i.connect(a,b,this.G)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Xb(a,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(a):W5(this)&&(V5(this),ELa(this.i,a))};
g.k.iF=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)ELa(this.i,a[b])}this.W("handlerOpened")};
g.k.gF=function(a){var b=2==a&&401==this.i.tj;4==a||b||this.l.start();this.W("handlerError",a,b)};
g.k.vz=function(a){if(!this.l.isActive())this.W("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.PF=function(){var a={v:2};this.V&&(a.gsessionid=this.V);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Xb(a,this.C);return a};
g.k.hF=function(a){"S"==a[0]?this.V=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),CLa(this.i)):this.W("handlerMessage",new NLa(a[0],a[1]))};
g.k.ox=function(a){(this.G.loungeIdToken=a)||this.l.stop();if(this.xa&&this.i){var b=this.i.sj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.sj=b}};
g.k.vS=function(){this.l.isActive();0==FLa(this.i)&&this.connect(this.C,this.B)};X5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
X5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
X5.prototype.C=function(a){a(Error("request timed out"))};var WLa=Date.now(),$5=null,c6=Array(50),b6=-1,d6=!1;g.Ta(e6,g.P);e6.prototype.dh=function(){return this.screens};
e6.prototype.contains=function(a){return!!$4(this.screens,a)};
e6.prototype.get=function(a){return a?a5(this.screens,a):null};
e6.prototype.info=function(a){a6(this.G,a)};g.v(f6,g.P);g.k=f6.prototype;g.k.start=function(){!this.i&&isNaN(this.yb)&&this.rI()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.yb)||(g.wp(this.yb),this.yb=NaN)};
g.k.va=function(){this.stop();g.P.prototype.va.call(this)};
g.k.rI=function(){this.yb=NaN;this.i=g.Bp(Y5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.C)(this.WL,this),onError:(0,g.C)(this.VL,this),onTimeout:(0,g.C)(this.XL,this)})};
g.k.WL=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.B;a.name=this.G;b=-1;this.C&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.W("pairingComplete",new V4(a),b)};
g.k.VL=function(a){this.i=null;a.status&&404==a.status?this.l>=rNa.length?this.W("pairingFailed",Error("DIAL polling timed out")):(a=rNa[this.l],this.yb=g.up((0,g.C)(this.rI,this),a),this.l++):this.W("pairingFailed",Error("Server error "+a.status))};
g.k.XL=function(){this.i=null;this.W("pairingFailed",Error("Server not responding"))};
var rNa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(h6,e6);g.k=h6.prototype;g.k.start=function(){g6(this)&&this.W("screenChange");!g.uv("yt-remote-lounge-token-expiration")&&$La(this);g.wp(this.i);this.i=g.up((0,g.C)(this.start,this),1E4)};
g.k.add=function(a,b){g6(this);XLa(this,a);i6(this,!1);this.W("screenChange");b(a);a.token||$La(this)};
g.k.remove=function(a,b){var c=g6(this);ZLa(this,a)&&(i6(this,!1),c=!0);b(a);c&&this.W("screenChange")};
g.k.Kx=function(a,b,c,d){var e=g6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,i6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.W("screenChange")};
g.k.va=function(){g.wp(this.i);h6.Ld.va.call(this)};
g.k.LN=function(a){g6(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}i6(this,!b);b&&a6(this.G,"Missed "+b+" lounge tokens.")};
g.k.KN=function(a){a6(this.G,"Requesting lounge tokens failed: "+a)};g.v(k6,g.P);g.k=k6.prototype;g.k.start=function(){var a=parseInt(g.uv("yt-remote-fast-check-period")||"0",10);(this.B=g.Sa()-144E5<a?0:a)?n6(this):(this.B=g.Sa()+3E5,g.tv("yt-remote-fast-check-period",this.B),this.TB())};
g.k.isEmpty=function(){return g.Pb(this.i)};
g.k.update=function(){j6("Updating availability on schedule.");var a=this.G(),b=g.Cb(this.i,function(c,d){return c&&!!a5(a,d)},this);
m6(this,b)};
g.k.va=function(){g.wp(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.P.prototype.va.call(this)};
g.k.TB=function(){g.wp(this.u);this.u=NaN;this.l&&this.l.abort();var a=bMa(this);if(R4(a)){var b=Y5(this.C,"/pairing/get_screen_availability");this.l=Z5(this.C,b,{lounge_token:g.Kb(a).join(",")},(0,g.C)(this.jR,this,a),(0,g.C)(this.iR,this))}else m6(this,{}),n6(this)};
g.k.jR=function(a,b){this.l=null;var c=g.Kb(bMa(this));if(g.xb(c,g.Kb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;m6(this,c);n6(this)}else this.Md("Changing Screen set during request."),this.TB()};
g.k.iR=function(a){this.Md("Screen availability failed: "+a);this.l=null;n6(this)};
g.k.Md=function(a){a6("OnlineScreenService",a)};g.Ta(o6,e6);g.k=o6.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.W("screenChange"),this.i.isEmpty()||this.W("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Kx=function(a,b,c,d){this.l.contains(a)?this.l.Kx(a,b,c,d):(a="Updating name of unknown screen: "+a.name,a6(this.G,a),d(Error(a)))};
g.k.dh=function(a){return a?this.screens:g.nb(this.screens,g.Ke(this.u,function(b){return!this.contains(b)},this))};
g.k.RD=function(){return g.Ke(this.dh(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.SD=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new f6(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.Ii(l);e(p6(h,m),n)});
l.subscribe("pairingFailed",function(m){g.Ii(l);f(m)});
l.start();return(0,g.C)(l.stop,l)};
g.k.YL=function(a,b,c,d){g.Bp(Y5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.C)(function(e,f){e=new V4(f.screen||{});if(!e.name||fMa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);fMa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(p6(this,e))},this),
onError:(0,g.C)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.C)(function(){d(Error("pairing request timed out."))},this)})};
g.k.va=function(){g.Ii(this.l);g.Ii(this.i);o6.Ld.va.call(this)};
g.k.RN=function(){hMa(this);this.W("screenChange");this.i.update()};
o6.prototype.dispose=o6.prototype.dispose;g.Ta(r6,g.P);g.k=r6.prototype;g.k.getScreen=function(){return this.B};
g.k.jg=function(a){this.Ha()||(a&&t6(this,""+a),this.B=null,this.W("sessionScreen",null))};
g.k.info=function(a){a6(this.xa,a)};
g.k.TD=function(){return null};
g.k.dC=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.C)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.C)(function(){t6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.va=function(){this.dC("");r6.Ld.va.call(this)};g.v(u6,r6);g.k=u6.prototype;g.k.cC=function(a){if(this.l){if(this.l==a)return;t6(this,"Overriding cast session with new session object");qMa(this);this.ma=!1;this.V="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra);mMa(this,"getMdxSessionStatus")};
g.k.yq=function(a){this.info("launchWithParams no-op for Cast: "+g.Fj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.C)(function(){this.jg()},this),(0,g.C)(function(){this.jg(Error("Failed to stop receiver app."))},this)):this.jg(Error("Stopping cast device without session."))};
g.k.dC=function(){};
g.k.va=function(){this.info("disposeInternal");qMa(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra));this.l=null;r6.prototype.va.call(this)};
g.k.UR=function(a,b){if(!this.Ha())if(b)if(b=o5(b),g.Na(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Fj(b)),a){case "mdxSessionStatus":kMa(this,b);break;case "loungeToken":nMa(this,b);break;default:t6(this,"Unknown youtube message: "+a)}else t6(this,"Unable to parse message.");else t6(this,"No data in message.")};
g.k.eG=function(a,b,c,d){g.wp(this.L);this.L=0;eMa(this.u,this.i.label,a,this.i.friendlyName,(0,g.C)(function(e){e?b(e):0<=d?(t6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.up((0,g.C)(this.eG,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.TD=function(){return this.l};
g.k.ZL=function(a){this.Ha()||a||(t6(this,"Cast session died."),this.jg())};g.v(x6,r6);g.k=x6.prototype;g.k.cC=function(a){this.l=a;this.l.addUpdateListener(this.ya)};
g.k.yq=function(a){this.Ea=a;this.X()};
g.k.stop=function(){xMa(this);this.l?this.l.stop((0,g.C)(this.jg,this,null),(0,g.C)(this.jg,this,"Failed to stop DIAL device.")):this.jg()};
g.k.va=function(){xMa(this);this.l&&this.l.removeUpdateListener(this.ya);this.l=null;r6.prototype.va.call(this)};
g.k.aM=function(a){this.Ha()||a||(t6(this,"DIAL session died."),this.C(),this.C=g.Ia,this.jg())};g.v(B6,r6);B6.prototype.stop=function(){this.jg()};
B6.prototype.cC=function(){};
B6.prototype.yq=function(){g.wp(this.l);this.l=NaN;var a=a5(this.u.dh(),this.i.label);a?s6(this,a):this.jg(Error("No such screen"))};
B6.prototype.va=function(){g.wp(this.l);this.l=NaN;r6.prototype.va.call(this)};g.v(C6,g.P);g.k=C6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.V||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.C)(this.TQ,this);c=new chrome.cast.ApiConfig(c,(0,g.C)(this.eI,this),e,d,a);c.customDialLaunchCallback=(0,g.C)(this.JP,this);chrome.cast.initialize(c,(0,g.C)(function(){this.Ha()||
(chrome.cast.addReceiverActionListener(this.G),TLa(),this.l.subscribe("onlineScreenChange",(0,g.C)(this.UD,this)),this.u=zMa(this),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(f){this.Md("Failed to set initial custom receivers: "+g.Fj(f))},this)),this.W("yt-remote-cast2-availability-change",E6(this)),b(!0))},this),(0,g.C)(function(f){this.Md("Failed to initialize API: "+g.Fj(f));
b(!1)},this))};
g.k.AS=function(a,b){D6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)D6("Unsetting old screen status: "+this.i.i.friendlyName),F6(this,null)}if(a&&b){if(!this.i){c=a5(this.l.dh(),a);if(!c){D6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){D6("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=yMa(this,c);a||(D6("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(a),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(d){this.Md("Failed to set initial custom receivers: "+g.Fj(d))},this)));
D6("setConnectedScreenStatus: new active receiver: "+a.friendlyName);F6(this,new B6(this.l,a),!0)}this.i.dC(b)}else D6("setConnectedScreenStatus: no screen.")};
g.k.BS=function(a){this.Ha()?this.Md("Setting connection data on disposed cast v2"):this.i?this.i.yq(a):this.Md("Setting connection data without a session")};
g.k.cM=function(){this.Ha()?this.Md("Stopping session on disposed cast v2"):this.i?(this.i.stop(),F6(this,null)):D6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.C)(this.eI,this),(0,g.C)(this.mR,this))};
g.k.va=function(){this.l.unsubscribe("onlineScreenChange",(0,g.C)(this.UD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.G);var a=QLa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.Ii(this.i);g.P.prototype.va.call(this)};
g.k.Md=function(a){a6("Controller",a)};
g.k.gI=function(a,b){this.i==a&&(b||F6(this,null),this.W("yt-remote-cast2-session-change",b))};
g.k.QQ=function(a,b){if(!this.Ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),D6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)D6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{D6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.W("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:F6(this,
new B6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:F6(this,new x6(this.l,a,this.C,this.B));break;case chrome.cast.ReceiverType.CAST:F6(this,new u6(this.l,a,this.B));break;default:this.Md("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Md("Stopping receiver w/o session: "+a.friendlyName)}else this.Md("onReceiverAction_ called without receiver.")};
g.k.JP=function(a){if(this.Ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Md("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Md("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return D6("Reselecting dial screen."),
this.W("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Md('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);F6(this,new x6(this.l,b,this.C,this.B))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,y6(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=uMa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.$o(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=vMa(b,c)):a=vMa(b,c)):a=A6(b);return a};
g.k.eI=function(a){if(!this.Ha()){D6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)D6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),F6(this,new u6(this.l,b,this.B),!0);else{this.Md("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=a5(this.l.dh(),c.label);d&&W4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(D6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ii(this.i),this.i=new u6(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.C)(this.gI,this,this.i)),this.i.yq(null));this.i.cC(a)}}};
g.k.bM=function(){return this.i?this.i.TD():null};
g.k.mR=function(a){this.Ha()||(this.Md("Failed to estabilish a session: "+g.Fj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&F6(this,null))};
g.k.TQ=function(a){D6("Receiver availability updated: "+a);if(!this.Ha()){var b=E6(this);this.J=a==chrome.cast.ReceiverAvailability.AVAILABLE;E6(this)!=b&&this.W("yt-remote-cast2-availability-change",E6(this))}};
g.k.UD=function(){this.Ha()||(this.u=zMa(this),D6("Updating custom receivers: "+g.Fj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(){this.Md("Failed to set custom receivers.")},this)),this.W("yt-remote-cast2-availability-change",E6(this)))};
C6.prototype.setLaunchParams=C6.prototype.BS;C6.prototype.setConnectedScreenStatus=C6.prototype.AS;C6.prototype.stopSession=C6.prototype.cM;C6.prototype.getCastSession=C6.prototype.bM;C6.prototype.requestSession=C6.prototype.requestSession;C6.prototype.init=C6.prototype.init;C6.prototype.dispose=C6.prototype.dispose;var L6=[];g.k=Q6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";R6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Hj=a.hasPrevious,this.hasNext=a.hasNext,this.J=a.playerTime,this.G=a.playerTimeAt,this.B=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.L=a.loadedTime,this.u=a.liveIngestionTime,this.l=
!isNaN(this.u))};
g.k.qc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.l?this.C+S6(this):this.C};
g.k.clone=function(){return new Q6(W6(this))};g.v(Y6,g.P);g.k=Y6.prototype;g.k.getState=function(){return this.eb};
g.k.play=function(){$6(this)?(this.i?this.i.play(null,g.Ia,e7(this,"play")):d7(this,"play"),c7(this,1,U6(Z6(this))),this.W("remotePlayerChange")):a7(this,this.play)};
g.k.pause=function(){$6(this)?(this.i?this.i.pause(null,g.Ia,e7(this,"pause")):d7(this,"pause"),c7(this,2,U6(Z6(this))),this.W("remotePlayerChange")):a7(this,this.pause)};
g.k.seekTo=function(a){if($6(this)){if(this.i){var b=Z6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.qc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,e7(this,"seekTo",{newTime:a}))}else d7(this,"seekTo",{newTime:a});c7(this,3,a);this.W("remotePlayerChange")}else a7(this,g.Qa(this.seekTo,a))};
g.k.stop=function(){if($6(this)){this.i?this.i.stop(null,g.Ia,e7(this,"stopVideo")):d7(this,"stopVideo");var a=Z6(this);a.index=-1;a.videoId="";R6(a);b7(this,a);this.W("remotePlayerChange")}else a7(this,this.stop)};
g.k.setVolume=function(a,b){if($6(this)){var c=Z6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.C)(function(){a6("CP","set receiver volume: "+d)},this),(0,g.C)(function(){this.Md("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.C)(function(){a6("CP","set receiver muted: "+b)},this),(0,g.C)(function(){this.Md("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d7(this,"setVolume",e)}c.muted=b;c.volume=a;b7(this,c)}else a7(this,g.Qa(this.setVolume,a,b))};
g.k.VD=function(a,b){if($6(this)){var c=Z6(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Fj(b.style),g.Xb(a,c.trackData));d7(this,"setSubtitlesTrack",a);b7(this,c)}else a7(this,g.Qa(this.VD,a,b))};
g.k.setAudioTrack=function(a,b){$6(this)?(b=b.getLanguageInfo().getId(),d7(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=Z6(this),a.audioTrackId=b,b7(this,a)):a7(this,g.Qa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=Z6(this);c=c||0;var m={videoId:a,currentIndex:c};V6(l,a,c);void 0!==b&&(T6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Fj(h));d7(this,"setPlaylist",m);d||b7(this,l)};
g.k.Xw=function(a,b){if($6(this)){if(a&&b){var c=Z6(this);V6(c,a,b);b7(this,c)}d7(this,"previous")}else a7(this,g.Qa(this.Xw,a,b))};
g.k.nextVideo=function(a,b){if($6(this)){if(a&&b){var c=Z6(this);V6(c,a,b);b7(this,c)}d7(this,"next")}else a7(this,g.Qa(this.nextVideo,a,b))};
g.k.zF=function(){$6(this)?d7(this,"dismissAutoplay"):a7(this,this.zF)};
g.k.dispose=function(){if(3!=this.eb){var a=this.eb;this.eb=3;this.W("proxyStateChange",a,this.eb)}g.P.prototype.dispose.call(this)};
g.k.va=function(){LMa(this);this.u=null;this.B.clear();X6(this,null);g.P.prototype.va.call(this)};
g.k.fC=function(a){if((a!=this.eb||2==a)&&3!=this.eb&&0!=a){var b=this.eb;this.eb=a;this.W("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.gb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.NQ=function(a,b){this.W(a,b)};
g.k.vP=function(a){if(!a)this.ot(null),X6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=Z6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)a6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b7(this,b)}};
g.k.ot=function(a){a6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),MMa(this),this.W("remotePlayerChange")};
g.k.uP=function(a){a?(MMa(this),this.W("remotePlayerChange")):this.ot(null)};
g.k.xC=function(){d7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.CP=function(){var a=IMa();a&&X6(this,a)};
g.k.Md=function(a){a6("CP",a)};g.v(f7,g.P);g.k=f7.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime;b=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);b&&(l.locationInfo=b);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.dc.listId=c);this.dc.videoId=d;this.dc.index=h||0;this.dc.state=3;T6(this.dc,m);this.B="UNSUPPORTED";g7("Connecting with setPlaylist and params: "+g.Fj(l));this.i.connect({method:"setPlaylist",
params:g.Fj(l)},a,LKa())}else g7("Connecting without params"),this.i.connect({},a,LKa());OMa(this)};
g.k.ox=function(a){this.i.ox(a)};
g.k.dispose=function(){this.Ha()||(this.W("beforeDispose"),h7(this,3));g.P.prototype.dispose.call(this)};
g.k.va=function(){i7(this);k7(this);j7(this);g.wp(this.J);this.J=NaN;g.wp(this.L);this.L=NaN;this.u=null;g.aq(this.V);this.V.length=0;this.i.dispose();g.P.prototype.va.call(this);this.B=this.G=this.l=this.dc=this.i=null};
g.k.HN=function(){this.Zp(2)};
g.k.zP=function(){g7("Channel opened");this.ma&&(this.ma=!1,j7(this),this.Y=g.up((0,g.C)(function(){g7("Timing out waiting for a screen.");this.Zp(1)},this),15E3));
PKa(OLa(this.i),this.ya)};
g.k.wP=function(){g7("Channel closed");isNaN(this.C)?f5(!0):f5();this.dispose()};
g.k.xP=function(a,b){f5();isNaN(this.Fs())?(b&&"shortLived"==this.ra&&this.W("browserChannelAuthError",a),g7("Channel error: "+a+" without reconnection"),this.dispose()):(this.ma=!0,g7("Channel error: "+a+" with reconnection in "+this.Fs()+" ms"),h7(this,2))};
g.k.yP=function(a){a.params?g7("Received: action="+a.action+", params="+g.Fj(a.params)):g7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=o5(a.params.devices);this.l=g.Pc(a,function(c){return new U4(c)});
a=!!g.bb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
RMa(this,a);break;case "loungeScreenDisconnected":g.lb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
RMa(this,!1);break;case "remoteConnected":var b=new U4(o5(a.params.device));g.bb(this.l,function(c){return b?c.id==b.id:!1})||vKa(this.l,b);
break;case "remoteDisconnected":b=new U4(o5(a.params.device));g.lb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":TMa(this,a);break;case "nowPlaying":VMa(this,a);break;case "onStateChange":UMa(this,a);break;case "onAdStateChange":WMa(this,a);break;case "onVolumeChanged":XMa(this,a);break;case "onSubtitlesTrackChanged":SMa(this,a);break;case "nowAutoplaying":YMa(this,a);break;case "autoplayDismissed":this.W("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.W("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.W("autoplayModeChange",this.B);"DISABLED"==this.B&&this.W("autoplayDismissed");break;case "onHasPreviousNextChanged":ZMa(this,a);break;case "requestAssistedSignIn":this.W("assistedSignInRequested",a.params.authCode);break;default:g7("Unrecognized action: "+a.action)}};
g.k.rS=function(){if(this.u){var a=this.u;this.u=null;this.dc.videoId!=a&&l7(this,"getNowPlaying")}};
g.k.CN=function(){var a=3;this.Ha()||(a=0,isNaN(this.Fs())?W5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Zp=function(a){g7("Disconnecting with "+a);i7(this);this.W("beforeDisconnect",a);1==a&&f5();PLa(this.i,a);this.dispose()};
g.k.AN=function(){var a=this.dc;this.u&&(a=this.dc.clone(),V6(a,this.u,a.index));return W6(a)};
g.k.CS=function(a){var b=new Q6(a);b.videoId&&b.videoId!=this.dc.videoId&&(this.u=b.videoId,g.wp(this.J),this.J=g.up((0,g.C)(this.rS,this),5E3));var c=[];this.dc.listId==b.listId&&this.dc.videoId==b.videoId&&this.dc.index==b.index||c.push("remoteQueueChange");this.dc.playerState==b.playerState&&this.dc.volume==b.volume&&this.dc.muted==b.muted&&U6(this.dc)==U6(b)&&g.Fj(this.dc.trackData)==g.Fj(b.trackData)||c.push("remotePlayerChange");this.dc.reset(a);g.zb(c,function(d){this.W(d)},this)};
g.k.dG=function(){var a=this.i.G.id,b=g.bb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Fs=function(){var a=this.i;return a.l.isActive()?a.l.l-g.Sa():NaN};
g.k.yN=function(){return this.B||"UNSUPPORTED"};
g.k.zN=function(){return this.G||""};
g.k.dM=function(){if(!isNaN(this.Fs())){var a=this.i.l;g.qn(a.i);a.start()}};
g.k.zS=function(a,b){l7(this,a,b);QMa(this)};
g.k.WD=function(){var a=g.Lo("SID","")||"",b=g.Lo("SAPISID","")||"",c=g.Lo("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.vf(g.Ye(a),2);b=g.vf(g.Ye(b),2);c=g.vf(g.Ye(c),2);return g.vf(g.Ye(a+","+b+","+c),2)};
f7.prototype.subscribe=f7.prototype.subscribe;f7.prototype.unsubscribeByKey=f7.prototype.Sf;f7.prototype.getProxyState=f7.prototype.CN;f7.prototype.disconnect=f7.prototype.Zp;f7.prototype.getPlayerContextData=f7.prototype.AN;f7.prototype.setPlayerContextData=f7.prototype.CS;f7.prototype.getOtherConnectedRemoteId=f7.prototype.dG;f7.prototype.getReconnectTimeout=f7.prototype.Fs;f7.prototype.getAutoplayMode=f7.prototype.yN;f7.prototype.getAutoplayVideoId=f7.prototype.zN;f7.prototype.reconnect=f7.prototype.dM;
f7.prototype.sendMessage=f7.prototype.zS;f7.prototype.getXsrfToken=f7.prototype.WD;g.v(m7,e6);g.k=m7.prototype;g.k.dh=function(a){return this.Jf.$_gs(a)};
g.k.contains=function(a){return!!this.Jf.$_c(a)};
g.k.get=function(a){return this.Jf.$_g(a)};
g.k.start=function(){this.Jf.$_st()};
g.k.add=function(a,b,c){this.Jf.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Jf.$_r(a,b,c)};
g.k.Kx=function(a,b,c,d){this.Jf.$_un(a,b,c,d)};
g.k.va=function(){for(var a=0,b=this.i.length;a<b;++a)this.Jf.$_ubk(this.i[a]);this.i.length=0;this.Jf=null;e6.prototype.va.call(this)};
g.k.eM=function(){this.W("screenChange")};
g.k.uQ=function(){this.W("onlineScreenChange")};
o6.prototype.$_st=o6.prototype.start;o6.prototype.$_gspc=o6.prototype.YL;o6.prototype.$_gsppc=o6.prototype.SD;o6.prototype.$_c=o6.prototype.contains;o6.prototype.$_g=o6.prototype.get;o6.prototype.$_a=o6.prototype.add;o6.prototype.$_un=o6.prototype.Kx;o6.prototype.$_r=o6.prototype.remove;o6.prototype.$_gs=o6.prototype.dh;o6.prototype.$_gos=o6.prototype.RD;o6.prototype.$_s=o6.prototype.subscribe;o6.prototype.$_ubk=o6.prototype.Sf;var z7=null,F7=!1,n7=null,o7=null,E7=null,s7=[];g.v(G7,g.F);g.k=G7.prototype;g.k.va=function(){g.F.prototype.va.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.Ob;a.unsubscribe("proxyStateChange",this.cI,this);a.unsubscribe("remotePlayerChange",this.xt,this);a.unsubscribe("remoteQueueChange",this.Uw,this);a.unsubscribe("previousNextChange",this.ZH,this);a.unsubscribe("nowAutoplaying",this.TH,this);a.unsubscribe("autoplayDismissed",this.tH,this);this.Ob=this.l=null};
g.k.XD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Ob.eb)if(H7(this)){if(!Z6(this.Ob).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":Z6(this.Ob).qc()?this.Ob.pause():this.Ob.play();break;case "control_play":this.Ob.play();break;case "control_pause":this.Ob.pause();break;case "control_seek":this.J.OD(c[0],c[1]);break;case "control_subtitles_set_track":I7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.I.getCurrentTime();J7(this,0===c?void 0:c);break;case "control_seek":J7(this,c[0]);break;case "control_subtitles_set_track":I7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.sP=function(a){this.L.TL(a)};
g.k.iT=function(a){this.XD("control_subtitles_set_track",g.Pb(a)?null:a)};
g.k.lJ=function(){var a=this.I.getOption("captions","track");g.Pb(a)||I7(this,a)};
g.k.Tb=function(a){this.l.Tb(a,this.I.getVideoData().lengthSeconds)};
g.k.fQ=function(){g.Pb(this.B)||jNa(this,this.B);this.C=!1};
g.k.cI=function(a,b){this.u.stop();2===b&&this.fJ()};
g.k.xt=function(){if(H7(this)){this.i.stop();var a=Z6(this.Ob);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Ve=1;break;case 1082:case 1083:this.l.Ve=0;break;default:this.l.Ve=-1}switch(a.playerState){case 1081:case 1:this.Lb(new g.mJ(8));this.eJ();break;case 1085:case 3:this.Lb(new g.mJ(9));break;case 1083:case 0:this.Lb(new g.mJ(2));this.J.stop();this.Tb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Lb(new g.mJ(4));break;case 2:this.Lb(new g.mJ(4));this.Tb(U6(a));
break;case -1:this.Lb(new g.mJ(64));break;case -1E3:this.Lb(new g.mJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=Z6(this.Ob).trackData;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,jNa(this,a));a=Z6(this.Ob);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.V.isActive()||this.KJ()}else iNa(this)};
g.k.ZH=function(){this.I.W("mdxpreviousnextchange")};
g.k.Uw=function(){H7(this)||iNa(this)};
g.k.TH=function(a){isNaN(a)||this.I.W("mdxnowautoplaying",a)};
g.k.tH=function(){this.I.W("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){H7(this)&&this.Ob.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===Z6(this.Ob).playerState?J7(this,a):b&&this.Ob.seekTo(a)};
g.k.KJ=function(){var a=this;if(H7(this)){var b=Z6(this.Ob);this.events.fc(this.X);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.X=this.events.N(this.I,"onVolumeChange",function(c){hNa(a,c)})}};
g.k.eJ=function(){this.i.stop();if(!this.Ob.Ha()){var a=Z6(this.Ob);a.qc()&&this.Lb(new g.mJ(8));this.Tb(U6(a));this.i.start()}};
g.k.fJ=function(){this.u.stop();this.i.stop();var a=this.Ob.u.getReconnectTimeout();2==this.Ob.eb&&!isNaN(a)&&this.u.start()};
g.k.Lb=function(a){this.u.stop();var b=this.G;if(!g.rJ(b,a)){var c=g.U(a,2);c!==g.U(this.G,2)&&this.I.Yo(c);this.G=a;lNa(this.l,b,a)}};g.v(K7,g.V);K7.prototype.Vc=function(){this.i.show()};
K7.prototype.Ab=function(){this.i.hide()};
K7.prototype.l=function(){g.UI("https://support.google.com/youtube/answer/7640706")};
K7.prototype.u=function(){T4("mdx-manual-pairing-popup-ok");this.Ab()};g.v(L7,g.V);L7.prototype.Vc=function(){this.i.show()};
L7.prototype.Ab=function(){this.i.hide()};
L7.prototype.l=function(){T4("mdx-privacy-popup-cancel");this.Ab()};
L7.prototype.u=function(){T4("mdx-privacy-popup-confirm");this.Ab()};g.v(M7,g.V);M7.prototype.l=function(a){kNa(this,a.state)};g.v(N7,g.cP);N7.prototype.C=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.Hm=g.Ab(a,this.i,this),g.dP(this,g.Pc(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.qh(a),this.enable(!0)):this.enable(!1)};
N7.prototype.i=function(a){return a.key};
N7.prototype.ni=function(a){return"cast-selector-receiver"===a?"Cast...":this.Hm[a].name};
N7.prototype.cf=function(a){g.cP.prototype.cf.call(this,a);this.I.setOption("remote","currentReceiver",this.Hm[a]);this.wb.Ab()};g.v(O7,g.mM);g.k=O7.prototype;
g.k.create=function(){var a=this.player.T(),b=g.ID(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.R(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.R(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.R(a.experiments,"enable_cast_short_lived_lounge_token")};cNa(b,a);this.subscriptions.push(g.Zq("yt-remote-before-disconnect",this.rP,this));this.subscriptions.push(g.Zq("yt-remote-connection-change",this.UQ,this));this.subscriptions.push(g.Zq("yt-remote-receiver-availability-change",
this.bI,this));this.subscriptions.push(g.Zq("yt-remote-auto-connect",this.SQ,this));this.subscriptions.push(g.Zq("yt-remote-receiver-resumed",this.RQ,this));this.subscriptions.push(g.Zq("mdx-privacy-popup-confirm",this.iS,this));this.subscriptions.push(g.Zq("mdx-privacy-popup-cancel",this.hS,this));this.subscriptions.push(g.Zq("mdx-manual-pairing-popup-ok",this.BO,this));this.bI()};
g.k.load=function(){this.player.cancelPlayback();g.mM.prototype.load.call(this);this.yh=new G7(this,this.player,this.Ob);var a=(a=gNa())?a.currentTime:0;var b=D7()?new Y6(x7(),void 0):null;0==a&&b&&(a=U6(Z6(b)));0!==a&&this.Tb(a);lNa(this,this.fd,this.fd);this.player.ck(6)};
g.k.unload=function(){this.player.W("mdxautoplaycanceled");this.Nl=this.Fi;g.Ji(this.yh,this.Ob);this.Ob=this.yh=null;g.mM.prototype.unload.call(this);this.player.ck(5);P7(this)};
g.k.va=function(){g.$q(this.subscriptions);g.mM.prototype.va.call(this)};
g.k.Sj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.yh.XD.apply(this.yh,[a].concat(g.na(c)))};
g.k.getAdState=function(){return this.Ve};
g.k.DN=function(){return this.loaded?this.yh.suggestion:null};
g.k.Hj=function(){return this.Ob?Z6(this.Ob).Hj:!1};
g.k.hasNext=function(){return this.Ob?Z6(this.Ob).hasNext:!1};
g.k.Tb=function(a,b){this.PG=a||0;this.player.W("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.PG};
g.k.getProgressState=function(){var a=Z6(this.Ob),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Ue():!a.isAdPlaying()&&this.player.Ue(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.l?a.u+S6(a):a.u,isAtLiveHead:1>=(a.l?a.i+S6(a):a.i)-this.getCurrentTime(),loaded:a.L,seekableEnd:a.l?a.i+S6(a):a.i,seekableStart:0<a.B?a.B+
S6(a):a.B}};
g.k.nextVideo=function(){this.Ob&&this.Ob.nextVideo()};
g.k.Xw=function(){this.Ob&&this.Ob.Xw()};
g.k.rP=function(a){1===a&&(this.GB=this.Ob?Z6(this.Ob):null)};
g.k.UQ=function(){var a=D7()?new Y6(x7(),void 0):null;if(a){var b=this.Nl;this.loaded&&this.unload();this.Ob=a;this.GB=null;b.key!==this.Fi.key&&(this.Nl=b,this.load())}else g.Ii(this.Ob),this.Ob=null,this.loaded&&(this.unload(),(a=this.GB)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,U6(a)));this.player.W("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.bI=function(){var a=[this.Fi],b=a.concat,c=dNa();M6()&&g.uv("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Hm=b.call(a,c);a=y7()||this.Fi;Q7(this,a);this.player.Ma("onMdxReceiversChange")};
g.k.SQ=function(){var a=y7();Q7(this,a)};
g.k.RQ=function(){this.Nl=y7()};
g.k.iS=function(){this.Ct=!0;P7(this);F7=!1;z7&&B7(z7,1);z7=null};
g.k.hS=function(){this.Ct=!1;P7(this);Q7(this,this.Fi);this.Nl=this.Fi;F7=!1;z7=null;this.player.playVideo()};
g.k.BO=function(){this.ww=!0;P7(this);g.tv("yt-remote-manual-pairing-warning-shown",!0,2592E3);F7=!1;z7&&B7(z7,1);z7=null};
g.k.Ne=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Hm;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?O6():Q7(this,b)),this.loaded?this.Nl:this.Fi;case "quickCast":return 2===this.Hm.length&&"cast-selector-receiver"===this.Hm[1].key?(b&&O6(),!0):!1}};
g.k.xC=function(){this.Ob.xC()};
g.k.Wh=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.xM.remote=O7;})(_yt_player);
