// if there is a * after a transcription it has been autogenerated and needs checking

var examples = `

ᨀᨆᨗᨔᨗ|Thursday|kɑmɪːsɪ (kamisi)
ᨄᨉᨚᨕᨂᨛ|prayers|(paddoangeng)
ᨅᨔ ᨕᨘᨁᨗ|Buginese language|(basa ugi)
ᨅᨗᨌᨑ|language|(bicara)
ᨆᨌ|clever|(maca)
ᨍᨘᨆ|Friday|(juma)
ᨒᨄ|lava|(lapa)
ᨓᨕᨙ|water|(wae)
ᨔᨈᨘ|Saturday|(satung)
ᨔᨒᨔ|Tuesday|sɑlɑːsɑ
ᨕᨆᨑᨙᨉᨀᨂᨛ|democracy|(amaradekangəng)
ᨕᨑᨅ|Wednesday|(araba)
ᨕᨔᨘ|dog|(asu)
ᨕᨙᨔᨙᨊᨙ|Monday|eseneŋ (eseneng)
ᨕᨛᨔᨚ ᨕᨖᨕᨗ|Sunday|(əso ahai)

`

