langTag = 'xmr'
window.version = 'v29'
window.scriptName = 'Meroitic Cursive'
window.ghDirectory = 'merc'
window.blockDirectory = 'merc'
window.languageList = ['xmr'] // lang tags for each orthography handled
window.detailsfileList = ['xmr'] // first part of xx-details for each orthography
window.scriptISO = 'merc'
window.webfonts = ["Noto Sans Meroitic WF"]
window.defaultSize = '24px'
hideBlockName = "MEROITIC CURSIVE"
