// if there is a * after a transcription it has been autogenerated and needs checking

var examples = `
ຄ.ສ. 1935 ສະບັບຄົ້ນ|CE 1935 Edition
ຄວາຍ|buffalo
ຄວາຢ|water buffalo|kʷʰáːj
ງົວ|snake|ŋúə
ຈອກ|glass|tɕɔ̏ːk
ຊ້າງ|elephant|sâːŋ
ຍຸງ|mosquito|ɲúŋ
ຕາ|eye|tàː
ຖົງ|stocking|tʰǒŋ
ທຸງ|flag|tʰúŋ
ນົກ|bird|(nōk)
ປະເທດ|country
ປາ|fish|paː
ຝົນ|rain|fǒn
ພູ|mountain|pʰúː
ຢາ|medecine|jaː
ຣະຄັງ|bell|rākʰáŋ
ລະດັບ|level
ລີງ|monkey|líːŋ
ວີ|fan|víː
ສ.ປ.ປ.ລາວ|Lao PDR
ສາມ|three|sam
ຫຍັງ|nothing|hɲ̱äŋ̱ (nyang)
ຫມາ|dog
ຫຼາຍ|more|lāj
ຫ່ານ|goose|hāːn
ເດັກ|child|dék
ເຜິ້ງ|bee|pʰɤ̏ŋ
ເສືອ|tiger|sɯ̌ːə
ເຮືອນ|house|hɯ́ːən
ແບ້|goat|bɛ̑ː
ແມວ|cat|mɛ́ːw
ໂອ|bowl|ʔòː
ໄກ່|chicken|kāi
ໄຂ່|egg|kʰāi
ໄຟ|fire|fáj
ໜຶ່ງ|one|nueng
ໝາ|dog
ອັກສອນລາວ||ʔáksɔ̌ːn láːw (ak sǭn lāw)

`

