// Functions for generating phonological map sections
// These functions are called from local html files in each orthography directory


function initialise () {
	// create the intro and input/output fields
	out = ''
	out += `
<h1>Generate items for map sections</h1>
<p>Input is a space-separated list of characters, generated by UniView. &nbsp;&nbsp; <label><input type="checkbox" id="sort" checked> Sort first?</label></p>

<!--p><textarea id="listin" placeholder="Add a list of characters here." style="height:400px;width:100%;"></textarea></p>

<p>
<button style="font-size: 150%;" onClick="
gatherData(document.getElementById('listin').value);">Go</button>
</p-->

<textarea id="out" style="height:85vh;width:100%;"></textarea>
`
	document.getElementById('intro').innerHTML = out
	
	
	makeTables(lang)

    document.getElementById('out').value = gatherData()
    
    document.getElementById('out').select()
	}





function makeTables (lang) {
    // make the spreadsheetRows object

    if (typeof window.spreadsheet === 'undefined') {
		console.log("Spreadsheet undefined.")
        console.log('%c' + 'Cannot find '+char+' the spreadsheet.', 'color:' + 'red' + ';font-weight:bold;')
		return
		}
    
    // make an object from the spreadsheet
    var temp = window.spreadsheet.split('\n')
    spreadsheet = ''
    window.spreadsheetRows = {}
    for (var x=0; x<temp.length; x++) {
        if (temp[x].trim() == '') continue
        var items = temp[x].split('\t')
        if (items[0] === '') continue

        window.spreadsheetRows[items[0]] = ['0']
        for (let i=1;i<items.length;i++) window.spreadsheetRows[items[0]].push(items[i])
        }
    //console.log(spreadsheetRows) 
    }



function gatherData () {
    // extract the map items
    ipaData = {}
    unwanted = new Set(['d','u','o','a'])
    var status, shape, hex
    
    for (row in spreadsheetRows) {
        if (spreadsheetRows[row][cols.ipaLoc]) {
            //console.log(spreadsheetRows[row][cols.ipaLoc])
            
            if (spreadsheetRows[row][cols.status] && unwanted.has(spreadsheetRows[row][cols.status])) continue
            
            // lowercase the IPA
            spreadsheetRows[row][cols.ipaLoc] = spreadsheetRows[row][cols.ipaLoc].toLowerCase()
            
            // make ipaData array: each unique ipa value points to characters
            items = spreadsheetRows[row][cols.ipaLoc].split(' ')
            for (i=0;i<items.length;i++) {
                console.log(items[i])
                if (typeof ipaData[items[i]] === 'undefined') {
                    ipaData[items[i]] = []
                    ipaData[items[i]].push( row )
                    }
                else {
                    ipaData[items[i]].push( row )
                    }
                }
            }
        }
    
    // create the output
    out = ''
    for (phone in ipaData) {
        for (i=0;i<ipaData[phone].length;i++) {
            char = ipaData[phone][i]
            
            // for the first item in a list of items create mapItem
            //if (ipaData[phone].length > 1 && i === 0) {
            if (i === 0) {
                out += `<div class="mapItem`
                if (spreadsheetRows[char] && spreadsheetRows[char][cols.status]) status = spreadsheetRows[char][cols.status]
                else status = ''
                if (status.includes('r') || status.includes('l')) out += ' uncommon'
                out += `">\n`
                
                out += `<div class="phone"><span class="ipa">${ phone.toLowerCase() }</span></div>\n`

                out += `<div class="map_detail">\n`
                }
            
            
            if (i>0) out += `\n`
            out += `<p class="map_row">`


            // add shaped forms if shape column exists
            if (spreadsheetRows[char] && spreadsheetRows[char][cols.shape]) shape = spreadsheetRows[char][cols.shape]
            else shape = ''
            hex =char.codePointAt(0).toString(16).toUpperCase()
            while (hex.length < 4) hex = '0'+hex

            if (shape === '4') {
                out += `\n<span class="shaping" lang="${ lang }"><span class="hx noname">${ hex }</span><span class="hx fina noname">${ hex }</span><span class="hx medi noname">${ hex }</span><span class="hx init noname">${ hex }</span></span>\n`
                }

            else if (shape === '2') {
                out += `\n<span class="shaping" lang="${ lang }"><span class="hx init noname">${ hex }</span><span class="hx fina noname">${ hex }</span></span>\n`
                }

            else if (shape !== '' && shape !== '0') {
                out += `\n<span class="shaping" lang="${ lang }"><span class="ch noname">${ shape }</span></span>\n`
                }
          

            // add shaped forms if there is an uppercase form
            if (spreadsheetRows[char] && spreadsheetRows[char][cols.uc]) shape = spreadsheetRows[char][cols.uc]
            else shape = ''
            hex =char.codePointAt(0).toString(16).toUpperCase()
            while (hex.length < 4) hex = '0'+hex

            if (shape !== '' && shape !== '0') {
                out += `\n<span class="shaping" lang="${ lang }"><span class="ch noname">${ shape }</span></span>\n`
                }
          

            if (typeof spreadsheetRows[char][cols.map] !== 'undefined') out += `<span class="posn">${ spreadsheetRows[char][cols.map] }</span>\n`
            else out += `<span class="posn">${ spreadsheetRows[char][cols.typeLoc] }</span>\n`
            out += `<span class="ch">${ char }</span> <b>`
            if (spreadsheetRows[char] && spreadsheetRows[char][cols.statusLoc]) out += spreadsheetRows[char][cols.statusLoc]
            out += `</b></p>\n`
            
            
            if (i === ipaData[phone].length-1) {
                out += `</div>\n`
                out += `</div>\n\n` // end of mapitem
                }
            }
        }
    
    return out
    }





