// Functions for generating phonological map sections
// These functions are called from local html files in each orthography directory


function initialise () {
	// create the intro and input/output fields
	out = ''
	out += `
<h1>Generate items for map sections</h1>
<p>Input is a space-separated list of characters, generated by UniView. &nbsp;&nbsp; <label><input type="checkbox" id="sort" checked> Sort first?</label></p>

<!--p><textarea id="listin" placeholder="Add a list of characters here." style="height:400px;width:100%;"></textarea></p-->

<p>
<button style="font-size: 150%;" onClick="
gatherData(document.getElementById('listin').value);">Go</button>
</p>

<textarea id="out" style="height:400px;width:100%;"></textarea>
`
	document.getElementById('intro').innerHTML = out
	
	
	makeTables(lang)

    document.getElementById('out').value = gatherData()
    
    document.getElementById('out').select()
	}





function makeTables (lang) {
    // make the spreadsheetRows object

    if (typeof window.spreadsheet === 'undefined') {
		console.log("Spreadsheet undefined.")
        console.log('%c' + 'Cannot find '+char+' the spreadsheet.', 'color:' + 'red' + ';font-weight:bold;')
		return
		}
    
    // make an object from the spreadsheet
    var temp = window.spreadsheet.split('\n')
    spreadsheet = ''
    window.spreadsheetRows = {}
    for (var x=0; x<temp.length; x++) {
        if (temp[x].trim() == '') continue
        var items = temp[x].split('\t')
        if (items[0] === '') continue

        window.spreadsheetRows[items[0]] = ['0']
        for (let i=1;i<items.length;i++) window.spreadsheetRows[items[0]].push(items[i])
        }
    //console.log(spreadsheetRows) 
    }



function gatherData () {
    // extract the map items
    ipaData = {}
    for (row in spreadsheetRows) {
        if (spreadsheetRows[row][cols.ipaLoc]) {
            //console.log(spreadsheetRows[row][cols.ipaLoc])
            
            items = spreadsheetRows[row][cols.ipaLoc].split(' ')
            for (i=0;i<items.length;i++) {
                console.log(items[i])
                if (typeof ipaData[items[i]] === 'undefined') {
                    ipaData[items[i]] = []
                    ipaData[items[i]].push( row )
                    }
                else {
                    ipaData[items[i]].push( row )
                    }
                }
            }
        }
    
    // create the output
    out = ''
    for (entry in ipaData) {
        out += `<div class="mapItem"`
        if (spreadsheetRows[ipaData[entry][i]] && spreadsheetRows[ipaData[entry][i]][cols.status]) status = spreadsheetRows[ipaData[entry][i]][cols.status]
        else status = ''
        if (status.includes('r') || status.includes('l')) out += ' uncommon'
        out += `>\n`
        out += `<div class="phone"><span class="ipa">${ entry }</span></div>\n`
        out += `<div class="posn">&nbsp;</div>\n`
        out += `<div class="col1">\n`
        for (i=0;i<ipaData[entry].length;i++) {
            out += `<p><span class="ch">${ ipaData[entry][i] }</span></p>\n`
            out += `<p class="example"><span class="eg" lang="${ lang }">xxx</span></p>\n`
            }
        out += `</div>\n`
        out += `</div>\n\n`
        }
    
    return out
    }






