window.langSet = true



reflist = {

"d": {
"authors": "Peter T. Daniels and William Bright",
"title":"The World's Writing Systems",
"publisher":"Oxford University Press",
"isbn":"0-19-507993-0",
"pages":"487-497",
"lang": new Set(['hi']),
},

"ep": {
"authors": "Michael Everson and Pravin Satpute",
"title":"Proposal to add four characters for Kashmiri to the BMP of the UCS",
"url":"https://www.unicode.org/L2/L2008/08250-n3480-kashmiri.pdf",
"lang": new Set(['ks']),
},

"rmcs": {
"authors": "Richard Ishida",
"title":"Ready-made Counter Styles",
"url":"https://www.w3.org/TR/predefined-counter-styles/#arabic-styles",
"lang": new Set(['hi']),
"reviewed":true
},

"l": {
"authors": "Swaran Lata",
"title":"Encoding of additional characters in Unicode for representation of Kashmiri",
"url":"https://www.unicode.org/L2/L2009/09311-kashmiri-ltr-from-swaran-lata.pdf",
"lang": new Set(['ks']),
},

"i": {
"authors": "Swaran Lata, Somnath Chandra, Prashant Verma",
"title":"Indic Layout Requirements",
"url":"https://www.w3.org/TR/ilreq/",
"lang": new Set(['hi']),
},

"mkr": {
"authors": "M. K. Raina",
"title":"How to read and write Kashmiri in Devanagari?",
"url":"http://koshur.org/pdf/Let%20Us%20Learn%20Kashmiri.pdf",
"lang": new Set(['ks']),
"reviewed":true
},

"rt": {
"authors": "M. K. Raina & Neelam Trakru",
"title":"Basic Reader for Kashmiri Language",
"publisher": "Project Zaan",
"url":"http://www.koshur.org/pdf/BasicReader.pdf",
"lang": new Set(['ks']),
},

"sg": {
"authors": "Akshay Sharma, The Sunday Guardian",
"title":"Pandits want official status for Kashmiri written in Devanagari script",
"lang": new Set(['ks']),
"url":"https://www.sundayguardianlive.com/news/7044-pandits-want-official-status-kashmiri-written-devanagari-script",
},

"s": {
"authors": "Rupert Snell & Simon Weightman",
"title":"Teach Yourself Hindi",
"publisher":"Hodder & Stoughton",
"isbn":"978-0-340-86687-0",
"lang": new Set(['hi']),
},

"st": {
"authors": "Santhosh Thottingal",
"title":"Personal correspondence",
"lang": new Set(['hi']),
},

"cldr": {
"url":"https://www.unicode.org/cldr/charts/latest/summary/hi.html",
"authors": "Unicode Consortium",
"title":"CLDR, Hindi",
"lang": new Set(['hi']),
},

"u": {
"authors": "Unicode Consortium",
"title":"The Unicode Standard, Version 13.0",
"sub":"Chapter 12.1: South and Central Asia-I, Devanagari",
"pages":"447-472",
"isbn":"978-1-936213-16-0.",
"url":"https://www.unicode.org/versions/Unicode13.0.0/ch12.pdf",
"lang": new Set(['hi','ks']),
},

"ws": {
"authors": "Wikipedia",
"title":"Devanagari",
"url":"https://en.wikipedia.org/wiki/Devanagari",
"lang": new Set(['hi']),
},

"wp": {
"authors": "Wikipedia",
"title":"Hindustani phonology",
"url":"https://en.wikipedia.org/wiki/Hindustani_phonology",
"lang": new Set(['hi']),
"reviewed":true
},

"wlk": {
"authors": "Wikipedia",
"title":"Kashmiri language",
"url":"https://en.wikipedia.org/wiki/Kashmiri_language",
"lang": new Set(['ks']),
},

}










scriptLanguageList = {
esg:{name:"Gondi, Aheri"},
anr:{name:"Andh"},
anp:{name:"Angika"},
asr:{name:"Asuri"},
aph:{name:"Athpariya"},
awa:{name:"Awadhi"},
bfy:{name:"Bagheli"},
bgq:{name:"Bagri"},
bhj:{name:"Bahing"},
bap:{name:"Bantawa"},
brd:{name:"Baraamu"},
btv:{name:"Bateri"},
byw:{name:"Belhariya"},
bhd:{name:"Bhadrawahi"},
bha:{name:"Bharia"},
bgw:{name:"Bhatri"},
bhi:{name:"Bhilali"},
bhb:{name:"Bhili"},
bho:{name:"Bhojpuri"},
byh:{name:"Bhujel"},
bhu:{name:"Bhunjia"},
kfs:{name:"Bilaspuri"},
biy:{name:"Birhor"},
brx:{name:"Bodo (India)"},
bmj:{name:"Bote-Majhi"},
bra:{name:"Braj"},
tkb:{name:"Buksa"},
bns:{name:"Bundeli"},
bee:{name:"Byangsi"},
rab:{name:"Camling"},
ncb:{name:"Nicobarese, Central"},
cdh:{name:"Chambeali"},
chx:{name:"Chantyal"},
cdm:{name:"Chepang"},
hne:{name:"Chhattisgarhi"},
ctn:{name:"Chhintange"},
cih:{name:"Chinali"},
the:{name:"Tharu, Chitwania"},
cdj:{name:"Churahi"},
daq:{name:"Maria, Dandami"},
thl:{name:"Tharu, Dangaura"},
dry:{name:"Darai"},
dcc:{name:"Deccan"},
dhw:{name:"Dhanwar (Nepal)"},
dhi:{name:"Dhimal"},
dho:{name:"Dhodia"},
dhd:{name:"Dhundari"},
dgo:{name:"Dogri (individual language)"},
doi:{name:"Dogri (macrolanguage)"},
dty:{name:"Dotyali"},
dus:{name:"Dumi"},
raa:{name:"Dungmali"},
duh:{name:"Dungra Bhil"},
pci:{name:"Duruwa"},
ggn:{name:"Eastern Gurung"},
mgp:{name:"Magar, Eastern"},
emg:{name:"Meohang, Eastern"},
taj:{name:"Tamang, Eastern"},
hif:{name:"Hindi, Fiji"},
gbk:{name:"Gaddi"},
kgj:{name:"Kham, Gamale"},
gbl:{name:"Gamit"},
gbm:{name:"Garhwali"},
gom:{name:"Konkani, Goan"},
gon:{name:"Gondi"},
gok:{name:"Gowli"},
gju:{name:"Gujari"},
gvr:{name:"Gurung"},
hlb:{name:"Halbi"},
kjo:{name:"Kinnauri, Harijan"},
hoj:{name:"Haroti"},
bgc:{name:"Haryanvi"},
hin:{name:"Hindi", url:"hi.html"},
hoc:{name:"Ho"},
scp:{name:"Hyolmo"},
clk:{name:"Idu-Mishmi"},
jns:{name:"Jaunsari"},
jee:{name:"Jerung"},
jul:{name:"Jirel"},
jml:{name:"Jumli"},
kfr:{name:"Kachhi"},
syw:{name:"Kagate"},
bjj:{name:"Kanauji"},
xnr:{name:"Kangri"},
kas:{name:"Kashmiri", url:"ks.html"},
tkt:{name:"Tharu, Kathoriya"},
klr:{name:"Khaling"},
khn:{name:"Khandesi"},
khr:{name:"Kharia"},
kfk:{name:"Kinnauri"},
thq:{name:"Tharu, Kochila"},
ksz:{name:"Kodaku"},
kkt:{name:"Koi"},
knn:{name:"Konkani (individual language)"},
kok:{name:"Konkani (macrolanguage)"},
kfq:{name:"Korku"},
vkp:{name:"Creole Portuguese, Korlai"},
kfp:{name:"Korwa"},
kff:{name:"Koya"},
kyw:{name:"Kudmali"},
kex:{name:"Kukna"},
kfx:{name:"Pahari, Kullu"},
kle:{name:"Kulung (Nepal)"},
kfy:{name:"Kumaoni"},
kra:{name:"Kumhali"},
kru:{name:"Kurukh"},
lmn:{name:"Lambadi"},
lhm:{name:"Lhomi"},
lif:{name:"Limbu"},
lbr:{name:"Lohorung"},
loy:{name:"Loke"},
mag:{name:"Magahi"},
bfz:{name:"Pahari, Mahasu"},
mai:{name:"Maithili"},
mjz:{name:"Majhi"},
mkb:{name:"Mal Paharia"},
mup:{name:"Malvi"},
nmm:{name:"Manangba"},
mjl:{name:"Mandeali"},
mar:{name:"Marathi"},
mrr:{name:"Maria (India)"},
rwr:{name:"Marwari (India)"},
mwr:{name:"Marwari"},
mke:{name:"Mawchi"},
mtr:{name:"Mewari"},
wtm:{name:"Mewati"},
nwx:{name:"Newar, Middle"},
mrg:{name:"Mising"},
unx:{name:"Munda"},
unr:{name:"Mundari"},
nbt:{name:"Na"},
ncd:{name:"Nachering"},
npi:{name:"Nepali (individual language)"},
nep:{name:"Nepali (macrolanguage)"},
kxl:{name:"Kurux, Nepali"},
new:{name:"Newari"},
noe:{name:"Nimadi"},
noi:{name:"Noiri"},
gno:{name:"Gondi, Northern"},
kfb:{name:"Kolami, Northwestern"},
tmk:{name:"Tamang, Northwestern"},
pli:{name:"Pali"},
plp:{name:"Palpa"},
tdb:{name:"Panchpargania"},
pgg:{name:"Pangwali"},
pkh:{name:"Pankhu"},
lae:{name:"Pattani"},
bfb:{name:"Bareli, Pauri"},
pum:{name:"Puma"},
suv:{name:"Puroik"},
raj:{name:"Rajasthani"},
rjs:{name:"Rajbanshi"},
rji:{name:"Raji"},
gra:{name:"Garasia, Rajput"},
thr:{name:"Tharu, Rana"},
bgd:{name:"Bareli, Rathwi"},
jnl:{name:"Rawat"},
sck:{name:"Sadri"},
rav:{name:"Sampang"},
san:{name:"Sanskrit"},
sat:{name:"Santali"},
skr:{name:"Saraiki"},
onp:{name:"Sartang"},
psu:{name:"Prākrit, Sauraseni"},
saz:{name:"Saurashtra"},
mjt:{name:"Sauria Paharia"},
swv:{name:"Shekhawati"},
xsr:{name:"Sherpa"},
kip:{name:"Kham, Sheshi"},
snd:{name:"Sindhi"},
srx:{name:"Sirmauri"},
ghe:{name:"Ghale, Southern"},
tsf:{name:"Southwestern Tamang"},
sbu:{name:"Bhoti, Stod"},
suz:{name:"Sunwar"},
sgj:{name:"Surgujia"},
sjp:{name:"Surjapuri"},
twm:{name:"Monpa, Tawang"},
ths:{name:"Thakali"},
thf:{name:"Thangmi"},
tdh:{name:"Thulung"},
tij:{name:"Tilung"},
lbf:{name:"Tinani"},
txo:{name:"Toto"},
vah:{name:"Varhadi-Nagpuri"},
vav:{name:"Varli"},
vas:{name:"Vasavi"},
wbr:{name:"Wagdi"},
wme:{name:"Wambule"},
nnp:{name:"Naga, Wancho"},
vay:{name:"Wayu"},
mrd:{name:"Magar, Western"},
raf:{name:"Meohang, Western"},
mut:{name:"Muria, Western"},
kjl:{name:"Kham, Western Parbate"},
tdg:{name:"Tamang, Western"},
ybh:{name:"Yakha"},
ybi:{name:"Yamphu"},
}











